### ISSUE TITLE
[Bug]: GLB larger than 2GB

### ISSUE THREAD

**Issue by ExacoMvm** [AssetRipper/AssetRipper#1007]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

EFT

### Which Unity version did this occur on?

2019.4.39f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Can't merge a buffer larger than 2GB

### Relevant log output

```
ExportProgress : Exporting 'Shopping_Mall_2'
[Error] : System.InvalidOperationException: Can't merge a buffer larger than 2Gb
   at SharpGLTF.Schema2.ModelRoot.MergeBuffers()
   at SharpGLTF.Scenes.SceneBuilder.ToGltf2(IEnumerable`1 srcScenes, SceneBuilderSchema2Settings settings)
   at SharpGLTF.Scenes.SceneBuilder.ToGltf2()
   at AssetRipper.Export.UnityProjects.Models.GlbModelExporter.ExportBinary(IEnumerable`1 assets, Boolean isScene) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Models\GlbModelExporter.cs:line 106
   at AssetRipper.Export.UnityProjects.Models.GlbSceneModelExportCollection.ExportScene(IExportContainer container, String folderPath, String filePath, String sceneName) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Models\GlbSceneModelExportCollection.cs:line 15
   at AssetRipper.Export.UnityProjects.Project.SceneExportCollection.Export(IExportContainer container, String projectDirectory) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Project\SceneExportCollection.cs:line 44
   at AssetRipper.Export.UnityProjects.ProjectExporter.Export(GameBundle fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\ProjectExporter.cs:line 277
   at AssetRipper.Export.UnityProjects.ProjectExporter.Export(GameBundle fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\ProjectExporter.cs:line 183
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Func`2 filter, Action`1 onBeforeExport) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 185
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Action`1 onBeforeExport) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 164
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, MainWindowViewModel vm, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIExportManager.cs:line 46

```

**Comment by ExacoMvm** [comment]
```
System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.22631.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.3.3.1
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Mon Aug 28 04:21:16 UTC 2023
System : UTC Compile Time: Mon Aug  7 02:10:48 UTC 2023
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level0
General : StreamingAssetsMode: Ignore
General : DefaultVersion: 0.0.0a0
General : ExportRootPath: C:\Users\exaco\Desktop\AssetRipper\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Glb
General : ScriptExportMode: Hybrid
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Texture2D
General : TerrainExportMode: Mesh
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: True
General : IgnoreEngineAssets: True
General : Attempting to read files from C:\Games\EFT
Import : PC game structure has been found at 'C:\Games\EFT'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level10' has been found
Import : Game file 'level100' has been found
Import : Game file 'level101' has been found


... after ~106K of lines ...

ExportProgress : Exporting 'RoadSplineGenerator GenerateLods'
ExportProgress : Exporting 'RoadSplineGenerator GenerateLods'
ExportProgress : Exporting 'RoadSplineGenerator Generate'
ExportProgress : Exporting 'Shopping_Mall_2'
[Error] : System.InvalidOperationException: Can't merge a buffer larger than 2Gb
   at SharpGLTF.Schema2.ModelRoot.MergeBuffers()
   at SharpGLTF.Scenes.SceneBuilder.ToGltf2(IEnumerable`1 srcScenes, SceneBuilderSchema2Settings settings)
   at SharpGLTF.Scenes.SceneBuilder.ToGltf2()
   at AssetRipper.Export.UnityProjects.Models.GlbModelExporter.ExportBinary(IEnumerable`1 assets, Boolean isScene) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Models\GlbModelExporter.cs:line 106
   at AssetRipper.Export.UnityProjects.Models.GlbSceneModelExportCollection.ExportScene(IExportContainer container, String folderPath, String filePath, String sceneName) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Models\GlbSceneModelExportCollection.cs:line 15
   at AssetRipper.Export.UnityProjects.Project.SceneExportCollection.Export(IExportContainer container, String projectDirectory) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Project\SceneExportCollection.cs:line 44
   at AssetRipper.Export.UnityProjects.ProjectExporter.Export(GameBundle fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\ProjectExporter.cs:line 277
   at AssetRipper.Export.UnityProjects.ProjectExporter.Export(GameBundle fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\ProjectExporter.cs:line 183
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Func`2 filter, Action`1 onBeforeExport) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 185
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Action`1 onBeforeExport) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 164
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, MainWindowViewModel vm, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIExportManager.cs:line 46


```

**Comment by ds5678** [comment]
Quite simply, the scene is too big
