### ISSUE TITLE
[Bug]: Error Reading QualitySettings and PlayerSettings from globalgamemanagers

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#1023]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[Game](https://steamdb.info/app/880940/)

### Which Unity version did this occur on?

2021.3.30f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hi,

It looks like these 2 Unity project settings assets: can't be read from globalmanagers :
QualitySettings 
PlayerSettings

Game exports fine, but WITHOUT those 2 (important) files...
(raw files are in the 'UnreadableAssets' folder)
```
extract from the log:
Import [Error] : Error during reading of asset type PlayerSettings. V: 2021.3.30f1 P: StandaloneWin64Player N: globalgamemanagers Path: 
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at AssetRipper.IO.Endian.EndianSpanReader.ReadInt64() in F:\_DEV2\AssetRipper-master\Source\AssetRipper.IO.Endian\EndianSpanReader.g.cs:line 57
   at AssetRipper.SourceGenerated.Subclasses.PPtr_Object.PPtr_Object_5_0_0.ReadRelease(EndianSpanReader& reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList`1 value, EndianSpanReader& reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_129.PlayerSettings_2021_3_28.ReadRelease(EndianSpanReader& reader)
   at AssetRipper.Import.AssetCreation.GameAssetFactory.ReadNormalObject(IUnityObjectBase asset, ReadOnlyArraySegment`1 assetData) in F:\_DEV2\AssetRipper-master\Source\AssetRipper.Import\AssetCreation\GameAssetFactory.cs:line 155

Import [Error] : Error during reading of asset type QualitySettings. V: 2021.3.30f1 P: StandaloneWin64Player N: globalgamemanagers Path: 
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at AssetRipper.IO.Endian.EndianSpanReader.ReadUtf8String() in F:\_DEV2\AssetRipper-master\Source\AssetRipper.IO.Endian\EndianSpanReader.cs:line 97
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_Utf8StringAlign(EndianSpanReader& reader)
   at AssetRipper.SourceGenerated.Subclasses.QualitySetting.QualitySetting_2019_3_0_a6.ReadRelease(EndianSpanReader& reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList`1 value, EndianSpanReader& reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_47.QualitySettings_2019_3_0_a6.ReadRelease(EndianSpanReader& reader)
   at AssetRipper.Import.AssetCreation.GameAssetFactory.ReadNormalObject(IUnityObjectBase asset, ReadOnlyArraySegment`1 assetData) in F:\_DEV2\AssetRipper-master\Source\AssetRipper.Import\AssetCreation\GameAssetFactory.cs:line 155
```
I can provide files the globalgamemanagers files if needed.

Kind regards,
Z

**Comment by ds5678** [comment]
Z, for errors like this, you need to be patient. That version is only a week old, and I haven't dumped any type trees since August 20th. This will be fixed automatically with the next source gen dll.

**Comment by Zbuffers** [comment]
HA OK ;)
I didn't know, sorry for spamming ;)
Thanks for the info !
