### ISSUE TITLE
[Bug]: AnimatorControllers before Unity 5 cannot be exported correctly

### ISSUE THREAD

**Issue by GZHYBFHHJ** [AssetRipper/AssetRipper#1028]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Not Applicable

### Which Unity version did this occur on?

4.6.2p2

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

If using 0.1.9.9 version, AnimatorControllers before Unity 5 are exported correctly:
![AssetRipper_0199](https://github.com/AssetRipper/AssetRipper/assets/82015237/3d3b12a4-7753-46d8-9558-e6c19d90ebd6)
But if using 0.3.2.0 and newer version, these AnimatorControllers' default states are wrong, and the transitions from "Any State" are not exported:
![AssetRipper_0340](https://github.com/AssetRipper/AssetRipper/assets/82015237/add118f2-eb7f-487e-ad1b-484bb4dcf926)
And some AnimatorTransitions without conditions show this warning (also print in console) because "Has Exit Time" is false:
![warn](https://github.com/AssetRipper/AssetRipper/assets/82015237/30dbee75-a862-4779-893e-1694d7dfe72b)

**Comment by ds5678** [comment]
I don't understand what you're asking for other than to "make it work well."

Everytime I've bumped the first nonzero version number, there were significant changes, mostly for the better. `0.2.0.0` drastically reduced the maintenance overhead for the project and enabled exporting to the original Unity version. 

Comparing `0.3.4.0` to `0.1.9.9` is like comparing apples to oranges. `0.3.4.0` exports to `4.6.2p2`. `0.1.9.9` exports to `2017.3.0`.

Are you bumping the Unity version? I feel like those screenshots aren't from Unity 4. Bumping the Unity version is a probable cause for your experience.

> using 0.3.2.0 and newer version

Is there something special about 0.3.2.0 in regards to this issue?

**Comment by GZHYBFHHJ** [comment]
I was porting an old iOS game to other platforms.

> Are you bumping the Unity version? I feel like those screenshots aren't from Unity 4. Bumping the Unity version is a probable cause for your experience.

Yes, those screenshots are from Unity 2021.3. but even though I'm using Unity 5.6.7f1, it's still like that. (I can't use Unity 4 because it can't seem to connect to license server)

**Comment by ds5678** [comment]
It sounds like you're asking for #696

**Comment by GZHYBFHHJ** [comment]
I later solved the license server problem, but when I opened any AnimatorController, the console printed the error "clipCount == internalClipCount" and all the transitions in it disappeared.
So I can't confirm if that is caused by bumping the Unity version. Maybe I can send the IPA file link to better troubleshoot the issue?

**Comment by ds5678** [comment]
I am not doing in-depth investigations at this time.

**Comment by GZHYBFHHJ** [comment]
Ok, I looked at the source code.

**Comment by ds5678** [comment]
> Ok, I looked at the source code.

What does this mean?

**Comment by GZHYBFHHJ** [comment]
Oops, I accidentally sent it out.
But what I want to express is
https://github.com/AssetRipper/AssetRipper/blob/78c3e9a101b272db611fe824f9eff327f9ccbfb7/Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs#L271C4-L273C87
So I know why transitions from "Any State" are not exported.

**Comment by GZHYBFHHJ** [comment]
Oops, I accidentally sent it out.
But what I want to express is
https://github.com/AssetRipper/AssetRipper/blob/78c3e9a101b272db611fe824f9eff327f9ccbfb7/Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs#L271C4-L273C87
So I know why transitions from "Any State" are not exported.

**Comment by ds5678** [comment]
If you can find out how these any state transitions are stored in the editor on Unity 4, that would help me know how to export them better because (as you linked) they are currently discarded.

**Comment by GZHYBFHHJ** [comment]
Assets in Unity 4 Editor are saved in binary format instead of YAML. But despite this I used another tool to view.
I observed the data of AnimatorControllers and found that in `m_OrderedTransitions`, the transitions where `first` is empty are any state transitions (also their `m_SrcState` is empty).
But I'm not sure if that's the case. This is the result I got from the AnimatorController saved in Unity 4.7.2, and in any AnimatorControllers exported from the game, there is no case where `first` in `m_OrderedTransitions` is empty.

**Comment by ds5678** [comment]
Thank you for helping. Let me know if this works for you.

**Comment by GZHYBFHHJ** [comment]
It threw an exception:
```
System.NotSupportedException: Specified method is not supported.
   at AssetRipper.Assets.Generics.PPtrAccessList`2.GetAccessList() in E:\wuyihuan\AssetRipperGithub\AssetRipper\Source\AssetRipper.Assets\Generics\PPtrAccessList.cs:line 74
   at AssetRipper.Assets.Generics.PPtrAccessList`2.Add(TTarget item) in E:\wuyihuan\AssetRipperGithub\AssetRipper\Source\AssetRipper.Assets\Generics\PPtrAccessList.cs:line 49
   at AssetRipper.Processing.AnimatorControllers.VirtualAnimationFactory.CreateAnimatorStateMachine(ProcessedAssetCollection virtualFile, IAnimatorController controller, Int32 stateMachineIndex) in E:\wuyihuan\AssetRipperGithub\AssetRipper\Source\AssetRipper.Processing\AnimatorControllers\VirtualAnimationFactory.cs:line 292
   at AssetRipper.Processing.AnimatorControllers.AnimatorControllerProcessor.Process(IAnimatorController controller, ProcessedAssetCollection processedCollection) in E:\wuyihuan\AssetRipperGithub\AssetRipper\Source\AssetRipper.Processing\AnimatorControllers\AnimatorControllerProcessor.cs:line 39
   at AssetRipper.Processing.AnimatorControllers.AnimatorControllerProcessor.Process(GameData gameData) in E:\wuyihuan\AssetRipperGithub\AssetRipper\Source\AssetRipper.Processing\AnimatorControllers\AnimatorControllerProcessor.cs:line 28
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in E:\wuyihuan\AssetRipperGithub\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 119
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in E:\wuyihuan\AssetRipperGithub\AssetRipper\Source\AssetRipper.GUI\Managers\UIImportManager.cs:line 21
```

**Comment by ds5678** [comment]
It should be good now.

**Comment by GZHYBFHHJ** [comment]
"Any State Transitions" issue has been resolved.

> these AnimatorControllers' default states are wrong
> some AnimatorTransitions without conditions show this warning (also print in console) because "Has Exit Time" is false

I will solve these issues through pull request.

**Comment by ds5678** [comment]
Is everything alright?

**Comment by ds5678** [comment]
[AssetRipper.SourceGenerated.zip](https://github.com/AssetRipper/AssetRipper/files/12643261/AssetRipper.SourceGenerated.zip)

That might help you.
