### ISSUE TITLE
[Bug]: System.ArgumentException: Unknown attribute 4152472025 for VisualEffect

### ISSUE THREAD

**Issue by Alidai** [AssetRipper/AssetRipper#1047]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

1336490 - Against the Storm

### Which Unity version did this occur on?

0.3.4.0

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Tried to extract assets from "resources.assets" file.

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19045.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.3.4.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Sat Sep 23 08:40:42 UTC 2023
System : UTC Compile Time: Tue Sep  5 05:23:26 UTC 2023
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : DefaultVersion: 0.0.0a0
General : ExportRootPath: D:\Desktop\AssetRipper_win_x64\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Hybrid
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: False
General : IgnoreEngineAssets: False
General : Attempting to read files from D:\SteamLibrary\steamapps\common\Against the Storm\Against the Storm_Data\resources.assets
Import : Game file 'resources.assets' has been found
Import : Mixed game structure has been found at D:\SteamLibrary\steamapps\common\Against the Storm\Against the Storm_Data\resources.assets
Import : Files use the 'Unknown' scripting backend.
General : Finished reading files
General : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Lighting Data Assets
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
[Error] : System.ArgumentException: Unknown attribute 4152472025 for VisualEffect
   at AssetRipper.Processing.AnimationClips.CustomCurveResolver.ToAttributeName(BindingCustomType type, UInt32 attribute, String path) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\CustomCurveResolver.cs:line 338
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.AddCustomCurve(IAnimationClipBindingConstant bindings, IGenericBinding binding, String path, Single time, Single value) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 235
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessStreams(IReadOnlyList`1 streamFrames, IAnimationClipBindingConstant bindings, Single sampleRate) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 125
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessInner() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 59
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Convert(IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 112
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Process(GameData gameData) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 76
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 119
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIImportManager.cs:line 21

General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : DefaultVersion: 0.0.0a0
General : ExportRootPath: D:\Desktop\AssetRipper_win_x64\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Jpeg
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: False
General : IgnoreEngineAssets: False
General : Attempting to read files from D:\SteamLibrary\steamapps\common\Against the Storm\Against the Storm_Data\resources.assets
Import : Game file 'resources.assets' has been found
Import : Mixed game structure has been found at D:\SteamLibrary\steamapps\common\Against the Storm\Against the Storm_Data\resources.assets
Import : Files use the 'Unknown' scripting backend.
General : Finished reading files
General : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Lighting Data Assets
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
[Error] : System.ArgumentException: Unknown attribute 4152472025 for VisualEffect
   at AssetRipper.Processing.AnimationClips.CustomCurveResolver.ToAttributeName(BindingCustomType type, UInt32 attribute, String path) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\CustomCurveResolver.cs:line 338
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.AddCustomCurve(IAnimationClipBindingConstant bindings, IGenericBinding binding, String path, Single time, Single value) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 235
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessStreams(IReadOnlyList`1 streamFrames, IAnimationClipBindingConstant bindings, Single sampleRate) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 125
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessInner() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 59
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Convert(IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 112
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Process(GameData gameData) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 76
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 119
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIImportManager.cs:line 21

**Comment by ds5678** [comment]
`0.3.4.0` is not a Unity version. I need to know the Unity version. You can find it by dropping `resources.assets` into a hex editor.

https://hexed.it/

**Comment by Alidai** [comment]
Dropped it into the hex editor, is there a line I’m searching for specifically? Searching for “Unity Ver” or any variants of it doesn’t give me anything, and searching just “unity” gives me hundreds of hits.Sorry for my ignorance, the best coding I can do is a wikitable. Sent from Mail for Windows From: Jeremy PrittsSent: Saturday, 23 September 2023 14:08To: AssetRipper/AssetRipperCc: Alidai; AuthorSubject: Re: [AssetRipper/AssetRipper] [Bug]: System.ArgumentException: Unknown attribute 4152472025 for VisualEffect (Issue #1047) 0.3.4.0 is not a Unity version. I need to know the Unity version. You can find it by dropping resources.assets into a hex editor.https://hexed.it/—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Alidai** [comment]
> `0.3.4.0` is not a Unity version. I need to know the Unity version. You can find it by dropping `resources.assets` into a hex editor.
> 
> https://hexed.it/

![image](https://github.com/AssetRipper/AssetRipper/assets/44840984/f6d7c8eb-de4e-45bf-bf2b-16c2255068e6)
Can't find it in the hexeditor, but I think it's this version?

**Comment by ds5678** [comment]
That's it

**Comment by Alidai** [comment]
> That's it

Thanks for taking the time to help, I really appreciate it! :)
