### ISSUE TITLE
[Bug]: Invalid version format: 2020.2.1f3-Wayforward

### ISSUE THREAD

**Issue by RQWorldblender** [AssetRipper/AssetRipper#1050]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Linux x64

### Which game did this occur on?

Advance Wars 1+2: Re-Boot Camp (Nintendo Switch)
https://www.nintendo.com/store/products/advance-wars-1-plus-2-re-boot-camp-switch/ - Nintendo eShop page

### Which Unity version did this occur on?

2020.2.1f3-Wayforward (this fork seems to be in-house by WayForward)

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

AssetRipper cannot correctly parse the version, due to it being appended with '-Wayforward'. I should be able to open the resources.assets without other issues otherwise. I may be able to get around this with a hex editor, but i don't know how.

### Relevant log output

[Error] : System.ArgumentException: Invalid version format: 2020.2.1f3-Wayforward (Parameter 'version')
   at AssetRipper.Primitives.UnityVersion.Parse(String version, Nullable`1& customEngine)
   at AssetRipper.Primitives.UnityVersion.Parse(String version)
   at AssetRipper.IO.Files.SerializedFiles.Parser.SerializedFileMetadata.Read(SerializedReader reader) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.IO.Files/SerializedFiles/Parser/SerializedFileMetadata.cs:line 77
   at AssetRipper.IO.Files.SerializedFiles.Parser.SerializedFileMetadata.Read(SmartStream stream, SerializedFileHeader header) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.IO.Files/SerializedFiles/Parser/SerializedFileMetadata.cs:line 52
   at AssetRipper.IO.Files.SerializedFiles.SerializedFile.Read(SmartStream stream) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.IO.Files/SerializedFiles/SerializedFile.cs:line 92
   at AssetRipper.IO.Files.Scheme`1.Read(SmartStream stream, String filePath, String fileName) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.IO.Files/Scheme.cs:line 14
   at AssetRipper.IO.Files.Scheme`1.AssetRipper.IO.Files.IScheme.Read(SmartStream stream, String filePath, String fileName) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.IO.Files/Scheme.cs:line 18
   at AssetRipper.IO.Files.SchemeReader.ReadFile(SmartStream stream, String filePath, String fileName) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.IO.Files/SchemeReader.cs:line 47
   at AssetRipper.IO.Files.SchemeReader.LoadFile(String filePath) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.IO.Files/SchemeReader.cs:line 32
   at AssetRipper.Assets.Bundles.GameBundle.LoadFilesAndDependencies(IEnumerable`1 paths, IDependencyProvider dependencyProvider) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Assets/Bundles/GameBundle.FromPaths.cs:line 66
   at AssetRipper.Assets.Bundles.GameBundle.InitializeFromPaths(IEnumerable`1 paths, AssetFactoryBase assetFactory, IDependencyProvider dependencyProvider, IResourceProvider resourceProvider, UnityVersion defaultVersion) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Assets/Bundles/GameBundle.FromPaths.cs:line 32
   at AssetRipper.Assets.Bundles.GameBundle.FromPaths(IEnumerable`1 paths, AssetFactoryBase assetFactory, IDependencyProvider dependencyProvider, IResourceProvider resourceProvider, UnityVersion defaultVersion) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Assets/Bundles/GameBundle.FromPaths.cs:line 24
   at AssetRipper.Import.Structure.GameStructure.InitializeGameCollection(UnityVersion defaultVersion) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Import/Structure/GameStructure.cs:line 79
   at AssetRipper.Import.Structure.GameStructure..ctor(List`1 paths, CoreConfiguration configuration) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Import/Structure/GameStructure.cs:line 39
   at AssetRipper.Import.Structure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Import/Structure/GameStructure.cs:line 59
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Export.UnityProjects/Ripper.cs:line 112
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in /home/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.GUI/Managers/UIImportManager.cs:line 21

**Comment by ds5678** [comment]
I'm nearly certain this doesn't happen on the latest commit.

**Comment by RQWorldblender** [comment]
> I'm nearly certain this doesn't happen on the latest commit.

Thanks for letting me know. Now I need to figure out how to compile this program on Ubuntu Linux. Or maybe you can tell me how do I build from source?
What's the commit that fixed my issue, if you can remember?

**Comment by ds5678** [comment]
AssetRipper has continuous integration. Just download a build.

**Comment by RQWorldblender** [comment]
> AssetRipper has continuous integration. Just download a build.

At first I downloaded the Electron UI version which still failed with a different error, but then I eventually found the Skia GUI version, which eventually fixed my issue. It was a build from yesterday, so you're right about that some commit of yours since the last release 3 weeks ago fixed this very issue I had. Now I can continue my ripping process. Thanks again! I hope the next release will eventually fix this issue.
