### ISSUE TITLE
[Bug]: Bundle Read Error

### ISSUE THREAD

**Issue by BubblePlayzTHEREAL** [AssetRipper/AssetRipper#1056]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[Robot Tag](https://www.meta.com/experiences/5918504334849265/)

### Which Unity version did this occur on?

I don't know because its an apk and it doesn't show it.

### Is the game Mono or IL2Cpp?

Not Sure

### Describe the issue.

I imported the files from a .apk but it's not working.

### Relevant log output

```
System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19045.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.3.4.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Sat Sep 30 14:26:32 UTC 2023
System : UTC Compile Time: Tue Sep  5 05:23:26 UTC 2023
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : DefaultVersion: 0.0.0a0
General : ExportRootPath: C:\Users\Test\Desktop\unity ripper\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Hybrid
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: False
General : IgnoreEngineAssets: False
General : Attempting to read files from C:\Users\Test\Downloads\ROBOT_TAG
[Error] : System.Exception: Read 445 but expected 448 while reading bundle metadata
   at AssetRipper.IO.Files.BundleFiles.FileStream.FileStreamBundleFile.ReadMetadata(Stream stream, Int32 metadataSize) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\BundleFiles\FileStream\FileStreamBundleFile.cs:line 116
   at AssetRipper.IO.Files.BundleFiles.FileStream.FileStreamBundleFile.ReadFileStreamMetadata(Stream stream, Int64 basePosition) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\BundleFiles\FileStream\FileStreamBundleFile.cs:line 62
   at AssetRipper.IO.Files.BundleFiles.FileStream.FileStreamBundleFile.Read(SmartStream stream) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\BundleFiles\FileStream\FileStreamBundleFile.cs:line 32
   at AssetRipper.IO.Files.BundleFiles.FileStream.FileStreamBundleFile..ctor(String filePath) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\BundleFiles\FileStream\FileStreamBundleFile.cs:line 23
   at AssetRipper.Import.Structure.Platforms.PlatformGameStructure.GetUnityVersionFromBundleFile(String filePath) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\Platforms\PlatformGameStructure.cs:line 330
   at AssetRipper.Import.Structure.Platforms.PlatformGameStructure.GetUnityVersionFromDataDirectory(String dataDirectoryPath) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\Platforms\PlatformGameStructure.cs:line 344
   at AssetRipper.Import.Structure.Platforms.AndroidGameStructure..ctor(String rootPath, String obbPath) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\Platforms\AndroidGameStructure.cs:line 36
   at AssetRipper.Import.Structure.Platforms.PlatformChecker.CheckAndroid(List`1 paths, AndroidGameStructure& gameStructure) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\Platforms\PlatformChecker.cs:line 142
   at AssetRipper.Import.Structure.Platforms.PlatformChecker.CheckPlatform(List`1 paths, PlatformGameStructure& platformStructure, MixedGameStructure& mixedStructure) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\Platforms\PlatformChecker.cs:line 24
   at AssetRipper.Import.Structure.GameStructure..ctor(List`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure.cs:line 25
   at AssetRipper.Import.Structure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure.cs:line 59
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 112
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIImportManager.cs:line 21


```

**Comment by ds5678** [comment]
The error is unrelated to it being an apk.

**Comment by BubblePlayzTHEREAL** [comment]
> The error is unrelated to it being an apk.

What went wrong then?

**Comment by ds5678** [comment]
Not sure. It could be:
* Custom Unity Engine
* Unity 2023
* AssetRipper bug
* Improperly modified file

**Comment by ds5678** [comment]
I require a unity project that reproduces the problem before I investigate this further. Feel free to reopen the issue if it can be provided.
