### ISSUE TITLE
[Bug]: System.ArgumentException: AssetCollection on specific assets il2cpp game

### ISSUE THREAD

**Issue by AF-Source** [AssetRipper/AssetRipper#1092]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

MacOS x64

### Which game did this occur on?

https://play.google.com/store/apps/details?id=com.criticalforceentertainment.criticalops

### Which Unity version did this occur on?

2022.3.10

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

After importing all files, exporting fails on a specific asset(a few of them actually) due to "System.ArgumentException: AssetCollection with index 859057713 was not found in dependencies (Parameter 'fileIndex')". I tried this both on the latest stable and alpha release. Both of them failed in similar fashion.

### Relevant log output

ExportProgress : Exporting 'Engine 2022.3.10f1'
ExportProgress : Exporting 'CriticalForceLogo_compressed'
ExportProgress : Exporting 'CFRenderPipeline'
ExportProgress : Exporting 'EmptyLoadingScene'
ExportProgress : Exporting 'Start'
ExportProgress : Exporting 'PlayerSettings'
[Error] : System.ArgumentException: AssetCollection with index 859057713 was not found in dependencies (Parameter 'fileIndex')
   at AssetRipper.Assets.Collections.AssetCollection.ThrowIfFileIndexOutOfRange(Int32 fileIndex) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Assets/Collections/AssetCollection.cs:line 319
   at AssetRipper.Assets.Collections.AssetCollection.TryGetAsset(Int32 fileIndex, Int64 pathID, IUnityObjectBase& asset) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Assets/Collections/AssetCollection.cs:line 271
   at AssetRipper.SourceGenerated.Helpers.PPtrHelper.TryGetAsset[T](AssetCollection collection, Int32 fileID, Int64 pathID, T& asset)
   at AssetRipper.SourceGenerated.Helpers.PPtrHelper.ExportYaml[T](IPPtr`1 pptr, IExportContainer container, Int32 classID)
   at AssetRipper.SourceGenerated.Subclasses.PPtr_Object.PPtr_Object_5_0_0.ExportYamlEditor(IExportContainer container)
   at AssetRipper.SourceGenerated.Helpers.ExportYamlEditorMethods.ExportYamlEditor_Array_PPtr_Object_5_0_0(AssetList`1 value, IExportContainer container)
   at AssetRipper.SourceGenerated.Classes.ClassID_129.PlayerSettings_2022_3_3.ExportYamlEditor(IExportContainer container)
   at AssetRipper.Assets.UnityObjectBase.ExportYamlDocument(IExportContainer container) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Assets/UnityObjectBase.cs:line 34
   at AssetRipper.Export.UnityProjects.Project.YamlExporterBase.Export(IExportContainer container, IUnityObjectBase asset, String path) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Export.UnityProjects/Project/YamlExporterBase.cs:line 20
   at AssetRipper.Export.UnityProjects.Project.ManagerExportCollection.Export(IExportContainer container, String projectDirectory) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Export.UnityProjects/Project/ManagerExportCollection.cs:line 21
   at AssetRipper.Export.UnityProjects.ProjectExporter.Export(GameBundle fileCollection, IEnumerable`1 files, CoreConfiguration options) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Export.UnityProjects/ProjectExporter.cs:line 277
   at AssetRipper.Export.UnityProjects.ProjectExporter.Export(GameBundle fileCollection, CoreConfiguration options) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Export.UnityProjects/ProjectExporter.cs:line 183
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Func`2 filter, Action`1 onBeforeExport) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Export.UnityProjects/Ripper.cs:line 186
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Action`1 onBeforeExport) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Export.UnityProjects/Ripper.cs:line 165
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, MainWindowViewModel vm, String toRoot, Action onSuccess, Action`1 onError) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.GUI/Managers/UIExportManager.cs:line 46

**Comment by ds5678** [comment]
This is likely not my fault. I suspect it is caused by a custom engine.

**Comment by AF-Source** [comment]
@ds5678 What do you mean custom engine? If so is it possible to suppress the errors and continue without an error crashing the entire process?

**Comment by ds5678** [comment]
> What do you mean custom engine?

It means your game company paid Unity a lot of money, so they could change the source code.

> is it possible to suppress the errors

Of course it's *possible*. Almost everything is possible in software development.

> an error crashing the entire process

This error would never happen for a normal game.

**Comment by AF-Source** [comment]
@ds5678 I don't believe that it would be a custom engine or anything like that. Although could be some encryption or whatever. Regardless, are there any options to suppress the errors in the tool to rip the other assets? If not I will just patch the source to have a try catch instead.

**Comment by ds5678** [comment]
I am almost certain it's a custom engine.

**Comment by AF-Source** [comment]
So my best bet would be patching your source to try catch those errors? @ds5678

**Comment by ds5678** [comment]
Yes
