### ISSUE TITLE
[Bug]: Import : Could not initialize assembly manager. Switching to the 'Unknown' scripting backend.

### ISSUE THREAD

**Issue by ItzFAILURE** [AssetRipper/AssetRipper#1096]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Eternal Return

### Which Unity version did this occur on?

2022.38f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Import : Could not initialize assembly manager. Switching to the 'Unknown' scripting backend.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Cpp2IL.Core.Utils.X86Utils.GetRawManagedOrCaCacheGenMethodBody(UInt64 ptr, Boolean isCaGen) in /_/Cpp2IL.Core/Utils/X86Utils.cs:line 39
   at Cpp2IL.Core.InstructionSets.X86InstructionSet.GetRawBytesForMethod(MethodAnalysisContext context, Boolean isAttributeGenerator) in /_/Cpp2IL.Core/InstructionSets/X86InstructionSet.cs:line 17
   at Cpp2IL.Core.Model.Contexts.MethodAnalysisContext..ctor(Il2CppMethodDefinition definition, TypeAnalysisContext parent) in /_/Cpp2IL.Core/Model/Contexts/MethodAnalysisContext.cs:line 94
   at Cpp2IL.Core.Model.Contexts.TypeAnalysisContext.<.ctor>b__42_0(Il2CppMethodDefinition m) in /_/Cpp2IL.Core/Model/Contexts/TypeAnalysisContext.cs:line 115
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at Cpp2IL.Core.Model.Contexts.TypeAnalysisContext..ctor(Il2CppTypeDefinition il2CppTypeDefinition, AssemblyAnalysisContext containingAssembly) in /_/Cpp2IL.Core/Model/Contexts/TypeAnalysisContext.cs:line 115
   at Cpp2IL.Core.Model.Contexts.AssemblyAnalysisContext..ctor(Il2CppAssemblyDefinition assemblyDefinition, ApplicationAnalysisContext appContext) in /_/Cpp2IL.Core/Model/Contexts/AssemblyAnalysisContext.cs:line 63
   at Cpp2IL.Core.Model.Contexts.ApplicationAnalysisContext..ctor(Il2CppBinary binary, Il2CppMetadata metadata, Single metadataVersion) in /_/Cpp2IL.Core/Model/Contexts/ApplicationAnalysisContext.cs:line 93
   at Cpp2IL.Core.Cpp2IlApi.OnLibInitialized() in /_/Cpp2IL.Core/Cpp2IlApi.cs:line 102
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in /_/Cpp2IL.Core/Cpp2IlApi.cs:line 70
   at AssetRipper.Import.Structure.Assembly.Managers.IL2CppManager.Initialize(PlatformGameStructure gameStructure) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\Assembly\Managers\IL2CppManager.cs:line 79
   at AssetRipper.Import.Structure.GameStructure.InitializeAssemblyManager(CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure.cs:line 105

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13330393/AssetRipper.log)

**Comment by ds5678** [comment]
https://github.com/SamboyCoding/Cpp2IL/issues
