### ISSUE TITLE
[Bug]: System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'capacity')

### ISSUE THREAD

**Issue by VisualEhrmanntraut** [AssetRipper/AssetRipper#1104]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest pre-release of AssetRipper.

### Which release are you using?

MacOS x64

### Which game did this occur on?

https://steamdb.info/app/531510/info/

### Which Unity version did this occur on?

2017.4.17f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

```Info Export: Decompiling Assembly-CSharp
Error Export: System.AggregateException: One or more errors occurred. (Error decompiling @06001E5A GAKCNDCIPAE.FBBOADGEKFI) (Error decompiling @0600237B GADAMKIHCFL.OEAKLOPDCNJ)
Error Export:  ---> Error decompiling @06001E5A GAKCNDCIPAE.FBBOADGEKFI
Error Export: in assembly "Assembly-CSharp"
Error Export:  ---> System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'capacity')
Error Export:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) in offset 0
Error Export:    at System.Collections.Generic.List`1..ctor(Int32 capacity) in offset 10
Error Export:    at ICSharpCode.Decompiler.IL.Transforms.SwitchOnStringTransform.ExtractStringValuesFromInitBlock(Block block, List`1& values, Block& blockAfterInit, IType dictionaryType, IField dictionaryField, Boolean isHashtablePattern) in SwitchOnStringTransform.cs:line 790
Error Export:    at ICSharpCode.Decompiler.IL.Transforms.SwitchOnStringTransform.MatchLegacySwitchOnStringWithDict(InstructionCollection`1 instructions, Int32& i) in SwitchOnStringTransform.cs:line 604
Error Export:    at ICSharpCode.Decompiler.IL.Transforms.SwitchOnStringTransform.Run(ILFunction function, ILTransformContext context) in SwitchOnStringTransform.cs:line 72
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1737
Error Export: -- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1773
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1622
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.<>c__DisplayClass74_0.<DoDecompile>g__DoDecompileMember|0(IEntity entity, RecordDecompiler recordDecompiler, PartialTypeInfo partialType) in CSharpDecompiler.cs:line 1493
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1364
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in CSharpDecompiler.cs:line 652
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 950
Error Export:    at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
Error Export:    at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
Error Export:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
Error Export:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
Error Export:    at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
Error Export:    at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 35
Error Export:    --- End of inner exception stack trace ---
Error Export:    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
Error Export:    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
Error Export: --- End of stack trace from previous location ---
Error Export:    at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
Error Export:    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
Error Export:    at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 body)
Error Export:    at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>g__ProcessFiles|3(List`1 files) in /_/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs:line 255
Error Export:    at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.WriteCodeFilesInProject(PEFile module, IList`1 partialTypes, CancellationToken cancellationToken) in /_/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs:line 221
Error Export:    at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken) in /_/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs:line 154
Error Export:    at AssetRipper.Export.UnityProjects.Scripts.ScriptDecompiler.DecompileWholeProject(WholeProjectDecompiler decompiler, AssemblyDefinition assembly, String outputFolder) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Export.UnityProjects/Scripts/ScriptDecompiler.cs:line 44
Error Export:    at AssetRipper.Export.UnityProjects.Scripts.ScriptExportCollection.Export(IExportContainer container, String projectDirectory) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Export.UnityProjects/Scripts/ScriptExportCollection.cs:line 83
Error Export:    at AssetRipper.Export.UnityProjects.ProjectExporter.Export(GameBundle fileCollection, IEnumerable`1 files, CoreConfiguration options) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Export.UnityProjects/ProjectExporter.cs:line 267
Error Export:    at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Func`2 filter, Action`1 onBeforeExport) in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.Export.UnityProjects/Ripper.cs:line 186
Error Export:    at AssetRipper.GUI.Electron.Program.<>c.<<CreateMenu>b__7_5>d.MoveNext() in /Users/runner/work/AssetRipper/AssetRipper/Source/AssetRipper.GUI.Electron/Program.cs:line 250
Error Export:  ---> (Inner Exception #1) Error decompiling @0600237B GADAMKIHCFL.OEAKLOPDCNJ
Error Export: in assembly "Assembly-CSharp"
Error Export:  ---> System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'capacity')
Error Export:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) in offset 0
Error Export:    at System.Collections.Generic.List`1..ctor(Int32 capacity) in offset 10
Error Export:    at ICSharpCode.Decompiler.IL.Transforms.SwitchOnStringTransform.ExtractStringValuesFromInitBlock(Block block, List`1& values, Block& blockAfterInit, IType dictionaryType, IField dictionaryField, Boolean isHashtablePattern) in SwitchOnStringTransform.cs:line 790
Error Export:    at ICSharpCode.Decompiler.IL.Transforms.SwitchOnStringTransform.MatchLegacySwitchOnStringWithDict(InstructionCollection`1 instructions, Int32& i) in SwitchOnStringTransform.cs:line 604
Error Export:    at ICSharpCode.Decompiler.IL.Transforms.SwitchOnStringTransform.Run(ILFunction function, ILTransformContext context) in SwitchOnStringTransform.cs:line 72
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1737
Error Export: -- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1773
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1622
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.<>c__DisplayClass74_0.<DoDecompile>g__DoDecompileMember|0(IEntity entity, RecordDecompiler recordDecompiler, PartialTypeInfo partialType) in CSharpDecompiler.cs:line 1493
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1364
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in CSharpDecompiler.cs:line 652
Error Export:    at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 950
Error Export:    at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
Error Export:    at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
Error Export:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
Error Export:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
Error Export:    at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
Error Export:    at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 35<---
Error Export: 
Error Export: 
```

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13390729/AssetRipper.log)

**Comment by ds5678** [comment]
It's an upstream issue. There's nothing I can do other than stop using ILSpy.

**Comment by VisualEhrmanntraut** [comment]
Oh.

**Comment by ds5678** [comment]
Closing as more-or-less "unfixable." The only way this will be resolved is if I make my own decompiler, or if ILSpy makes theirs work better.
