### ISSUE TITLE
[Bug]: [Unknown attribute 1173142787 for ParticleSystem]

### ISSUE THREAD

**Issue by Jab-Punch** [AssetRipper/AssetRipper#1112]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Nickelodeon All Star Brawl 2

### Which Unity version did this occur on?

2022.3.5f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Error stops AssetRipper from proceeding: [Unknown attribute 1173142787 for ParticleSystem]

I am aware a similar issue to this has been resolved, #1025. However, I see no suggestion on how to fix the error from my own system.

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19045.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.3.4.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Thu Nov 23 05:33:28 UTC 2023
System : UTC Compile Time: Tue Sep  5 05:23:26 UTC 2023
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : DefaultVersion: 0.0.0a0
General : ExportRootPath: D:\Downloads\Unity Studio\2023\AssetRipper_win_x64\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Hybrid
General : ScriptLanguageVersion: CSharp9_0
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: False
General : IgnoreEngineAssets: False
General : Attempting to read files from F:\Jesse's Portfolio\Mirror Of Dusk Content\Research\Full Research\Nick_Brawl_2\Nickelodeon All-Star Brawl 2\Nickelodeon All-Star Brawl 2_Data\globalgamemanagers
Import : Game file 'globalgamemanagers' has been found
Import : Mixed game structure has been found at F:\Jesse's Portfolio\Mirror Of Dusk Content\Research\Full Research\Nick_Brawl_2\Nickelodeon All-Star Brawl 2\Nickelodeon All-Star Brawl 2_Data\globalgamemanagers
Import : Files use the 'Unknown' scripting backend.
Import [Error] : Error during reading of asset type QualitySettings. V: 2022.3.5f1 P: StandaloneWin64Player N: globalgamemanagers Path: 
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at AssetRipper.IO.Endian.EndianSpanReader.ReadInt32() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Endian\EndianSpanReader.g.cs:line 39
   at AssetRipper.SourceGenerated.Subclasses.MipmapLimitSettings.MipmapLimitSettings.ReadRelease(EndianSpanReader& reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList`1 value, EndianSpanReader& reader)
   at AssetRipper.SourceGenerated.Subclasses.QualitySetting.QualitySetting_2022_2_0_b3.ReadRelease(EndianSpanReader& reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList`1 value, EndianSpanReader& reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_47.QualitySettings_2022_2_0_b3.ReadRelease(EndianSpanReader& reader)
   at AssetRipper.Import.AssetCreation.GameAssetFactory.ReadNormalObject(IUnityObjectBase asset, ReadOnlyArraySegment`1 assetData) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\AssetCreation\GameAssetFactory.cs:line 155

General : Finished reading files
General : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Lighting Data Assets
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
[Error] : System.ArgumentException: Unknown attribute 1173142787 for ParticleSystem
   at AssetRipper.Processing.AnimationClips.CustomCurveResolver.ToAttributeName(BindingCustomType type, UInt32 attribute, String path) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\CustomCurveResolver.cs:line 364
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.AddCustomCurve(IAnimationClipBindingConstant bindings, IGenericBinding binding, String path, Single time, Single value) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 223
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessStreams(IReadOnlyList`1 streamFrames, IAnimationClipBindingConstant bindings, Single sampleRate) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 125
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessInner() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 59
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Convert(IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 112
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Process(GameData gameData) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 85
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 119
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIImportManager.cs:line 21

**Comment by ds5678** [comment]
>how to fix the error from my own system.

Download a more recent build, such as the prerelease from a week or two ago.
