### ISSUE TITLE
[Bug]: Bugs in AnimationClip Recovery

### ISSUE THREAD

**Issue by GZHYBFHHJ** [AssetRipper/AssetRipper#1290]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Linux x64

### Which Unity version did this occur on?

5.5.1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

After #1210, some bugs in 5.5.0 AnimationClip recovery have been fixed (such as a bug about right angled AnimationCurve in boolean value?)
But I also encountered the following two bugs:
1. NaN value
![7c1c6fc2-3452-4b9a-a750-e7e0dfb1f1c2](https://github.com/AssetRipper/AssetRipper/assets/82015237/32081e1b-c203-49b5-8a10-c38e0acf37f6)
This bug didn't appear before the improvements pr

2. uh I don't know how to explain it so I put these images here:
![image](https://github.com/AssetRipper/AssetRipper/assets/82015237/b2010fb3-ef4b-4c00-9f96-a97f08fc9440)
It might actually look like this:
![image](https://github.com/AssetRipper/AssetRipper/assets/82015237/98c83885-d2ee-4465-abb3-49b4dc302b47)
It should be:
![image](https://github.com/AssetRipper/AssetRipper/assets/82015237/d22e416e-96c3-443b-bcfd-84b94fadd713)

**Comment by ds5678** [comment]
cc: @FACS01-01

**Comment by FACS01-01** [comment]
do you have the original .anim files so I can test it? or AssetBundles
if you send them, also tell me the name of that first AnimationClip

**Comment by GZHYBFHHJ** [comment]
@FACS01-01 Here are the assets files of them
[assets_files.zip](https://github.com/AssetRipper/AssetRipper/files/14969277/assets_files.zip)

**Comment by GZHYBFHHJ** [comment]
NaN bug is fixed in #1321. I'm not sure if the second bug can be fixed (it still happens).
also, the animation recovery does not work with Unity version changing. It throws an exception:
```
System.ArgumentException: Binding with index 6 hasn't been found (Parameter 'index')
         at AssetRipper.Processing.AnimationClips.AnimationClipConverter.GetBinding(Int32 index) in /home/gzhybfhhj/Programs/AssetRipperGithub/AssetRipper/Source/AssetRipper.Processing/AnimationClips/AnimationClipConverter.cs:line 567
         at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessConstant(IConstantClip constant, Int32 preConstantCurves, Single lastFrame) in /home/gzhybfhhj/Programs/AssetRipperGithub/AssetRipper/Source/AssetRipper.Processing/AnimationClips/AnimationClipConverter.cs:line 209
         at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessInner() in /home/gzhybfhhj/Programs/AssetRipperGithub/AssetRipper/Source/AssetRipper.Processing/AnimationClips/AnimationClipConverter.cs:line 68
         at AssetRipper.Processing.AnimationClips.AnimationClipConverter.Process(IAnimationClip clip, PathChecksumCache checksumCache) in /home/gzhybfhhj/Programs/AssetRipperGithub/AssetRipper/Source/AssetRipper.Processing/AnimationClips/AnimationClipConverter.cs:line 49
         at AssetRipper.Processing.Editor.EditorFormatProcessor.Convert(IUnityObjectBase asset) in /home/gzhybfhhj/Programs/AssetRipperGithub/AssetRipper/Source/AssetRipper.Processing/Editor/EditorFormatProcessor.cs:line 112
         at AssetRipper.Processing.Editor.EditorFormatProcessor.Process(GameData gameData) in /home/gzhybfhhj/Programs/AssetRipperGithub/AssetRipper/Source/AssetRipper.Processing/Editor/EditorFormatProcessor.cs:line 76
         at AssetRipper.Export.UnityProjects.ExportHandler.Process(GameData gameData) in /home/gzhybfhhj/Programs/AssetRipperGithub/AssetRipper/Source/AssetRipper.Export.UnityProjects/ExportHandler.cs:line 53
         at AssetRipper.Export.UnityProjects.ExportHandler.LoadAndProcess(IReadOnlyList`1 paths) in /home/gzhybfhhj/Programs/AssetRipperGithub/AssetRipper/Source/AssetRipper.Export.UnityProjects/ExportHandler.cs:line 128
         at AssetRipper.GUI.Web.GameFileLoader.LoadAndProcess(IReadOnlyList`1 paths) in /home/gzhybfhhj/Programs/AssetRipperGithub/AssetRipper/Source/AssetRipper.GUI.Web/GameFileLoader.cs:line 47
         at AssetRipper.GUI.Web.Pages.Commands.LoadFolder.AssetRipper.GUI.Web.Pages.ICommand.Execute(HttpRequest request) in /home/gzhybfhhj/Programs/AssetRipperGithub/AssetRipper/Source/AssetRipper.GUI.Web/Pages/Commands.cs:line 61
         at AssetRipper.GUI.Web.Pages.Commands.HandleCommand[T](HttpContext context) in /home/gzhybfhhj/Programs/AssetRipperGithub/AssetRipper/Source/AssetRipper.GUI.Web/Pages/Commands.cs:line 102
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by ds5678** [comment]
Version changing is extremely experimental and will likely never be compatible with animation recovery.

**Comment by ds5678** [comment]
Are there any remaining errors blocking the closure of this issue?

**Comment by GZHYBFHHJ** [comment]
All bugs are fixed! Thanks

Also, I have a question about AnimationClip root motion curves. `m_HasGenericRootTransform` and `m_GenerateMotionCurves` exist in initial export of 5.5.1 AnimationClips, but seems that they are always zero. And in Unity 2017 Editor, generate root motion curves button shows in them.

**Comment by ds5678** [comment]
I'm not at home, so I can't check, but they might be editor only fields. If they are, then there is nothing stored for those fields in the game data.

**Comment by ds5678** [comment]
m_HasGenericRootTransform
Sometimes Editor Only: 5 to 2018.3

m_GenerateMotionCurves
Editor Only
