### ISSUE TITLE
[Bug]:I have an error load sucess but export fail 

### ISSUE THREAD

**Issue by urolzeen** [AssetRipper/AssetRipper#135]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2018.3.14f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

![image](https://user-images.githubusercontent.com/11881216/136781591-71847170-c7a7-48df-9c09-0a3d951bbdd3.png)

### Relevant log output

Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level2' has been found
Import : Mixed game structure has been found for 1 path(s)
Import : Files use the 'Mono' scripting backend.
Import [Warning] : Null UV0 for Icosphere
Import [Warning] : Null UV0 for icosahedron
Import [Warning] : Null UV0 for pyramid
Import : Assembly 'UnityEngine.IMGUIModule' has been loaded
Import : Assembly 'UnityEngine.CoreModule' has been loaded
Import : Assembly 'UnityEngine.TextRenderingModule' has been loaded
Import : Assembly 'mscorlib' has been loaded
Import : Assembly 'DOTween' has been loaded
Import : Assembly 'UnityEngine' has been loaded
Import : Assembly 'Assembly-CSharp' has been loaded
Import : Assembly 'UnityEngine.UI' has been loaded
Import : Assembly 'UnityEngine.AudioModule' has been loaded
Import : Assembly 'UnityEngine.PhysicsModule' has been loaded
General : Finished reading files
General [Error] : Unhandled app-level fatal exception!
System.ArgumentException: Value does not fall within the expected range.
   at Avalonia.Win32.Interop.UnmanagedMethods.IShellItem.GetDisplayName(UInt32 sigdnName, IntPtr& ppszName)
   at Avalonia.Win32.SystemDialogImpl.GetAbsoluteFilePath(IShellItem shellItem) in /_/src/Windows/Avalonia.Win32/SystemDialogImpl.cs:line 153
   at Avalonia.Win32.SystemDialogImpl.<>c__DisplayClass2_0.<ShowFolderDialogAsync>b__0() in /_/src/Windows/Avalonia.Win32/SystemDialogImpl.cs:line 142
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at AssetRipper.GUI.MainWindowViewModel.ExportAll() in /home/runner/work/AssetRipper/AssetRipper/AssetRipperGUI/MainWindow.ViewModel.cs:line 201
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 265
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 194
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, CancellationToken token) in /_/src/Avalonia.Controls/DesktopApplicationExtensions.cs:line 57
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, Window mainWindow) in /_/src/Avalonia.Controls/DesktopApplicationExtensions.cs:line 46
   at AssetRipper.GUI.App.AppMain(Application app, String[] args) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperGUI/App.axaml.cs:line 31
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 158
   at AssetRipper.GUI.Program.Main(String[] args) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperGUI/Program.cs:line 12

**Comment by ds5678** [comment]
Does this still happen for you on the latest alpha?

**Comment by ds5678** [comment]
Closing due to no response
