### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ghostx128** [AssetRipper/AssetRipper#142]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

0.1.7.1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Start error flash back

### Relevant log output

Unhandled exception. System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'name')
en_GB is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at System.Globalization.CultureInfo..ctor(String name)
   at AssetRipper.GUI.LocalizationManager.<>c.<Init>b__13_2(String code) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperGUI/LocalizationManager.cs:line 42
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at AssetRipper.GUI.LocalizationManager.Init() in /home/runner/work/AssetRipper/AssetRipper/AssetRipperGUI/LocalizationManager.cs:line 42
   at AssetRipper.GUI.MainWindow..ctor() in /home/runner/work/AssetRipper/AssetRipper/AssetRipperGUI/MainWindow.axaml.cs:line 27
   at AssetRipper.GUI.App.AppMain(Application app, String[] args) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperGUI/App.axaml.cs:line 34
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 158
   at AssetRipper.GUI.Program.Main(String[] args) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperGUI/Program.cs:line 12

**Comment by ghostx128** [comment]
> @ghostx128这对你有用吗？ https://nightly.link/ds5678/AssetRipper/workflows/publish/master/AssetRipperGUI_win64.zip
 Yes Startup work is normal
