### ISSUE TITLE
[Bug]:  Error in parsing BuildSettings and UnityConnectSettings for 2022.3.12f1

### ISSUE THREAD

**Issue by hsb4657** [AssetRipper/AssetRipper#1432]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

MacOS x64

### Which Unity version did this occur on?

2022.3.12f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.
```
Import [Error] : Error during reading of asset type BuildSettings. V: 2022.3.12f1 P: StandaloneWin64Player N: globalgamemanagers Path: 
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at AssetRipper.IO.Endian.EndianSpanReader.ReadInt32()
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Int32(AssetList`1 value, EndianSpanReader& reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_141.BuildSettings_2022_2_2.ReadRelease(EndianSpanReader& reader)
   at AssetRipper.Assets.UnityAssetBaseExtensions.Read(IUnityAssetBase asset, EndianSpanReader& reader, TransferInstructionFlags flags) in /Users/huangshaobin/IdeaProjects/AssetRipper/Source/AssetRipper.Assets/IUnityAssetBase.cs:line 58
   at AssetRipper.Assets.UnityObjectBaseExtensions.Read(IUnityObjectBase asset, EndianSpanReader& reader) in /Users/huangshaobin/IdeaProjects/AssetRipper/Source/AssetRipper.Assets/IUnityObjectBase.cs:line 103
   at AssetRipper.Import.AssetCreation.GameAssetFactory.TryReadNormalObject(AssetInfo assetInfo, ReadOnlyArraySegment`1 assetData, UnityVersion version, String& error) in /Users/huangshaobin/IdeaProjects/AssetRipper/Source/AssetRipper.Import/AssetCreation/GameAssetFactory.cs:line 135
Import [Error] : Error during reading of asset type UnityConnectSettings. V: 2022.3.12f1 P: StandaloneWin64Player N: globalgamemanagers Path: 
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at AssetRipper.IO.Endian.EndianSpanReader.ReadUtf8String()
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_Utf8StringAlign(EndianSpanReader& reader)
   at AssetRipper.SourceGenerated.Subclasses.CrashReportingSettings.CrashReportingSettings_2018_3.ReadRelease(EndianSpanReader& reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_310.UnityConnectSettings_2022_2_0_b8.ReadRelease(EndianSpanReader& reader)
   at AssetRipper.Assets.UnityAssetBaseExtensions.Read(IUnityAssetBase asset, EndianSpanReader& reader, TransferInstructionFlags flags) in /Users/huangshaobin/IdeaProjects/AssetRipper/Source/AssetRipper.Assets/IUnityAssetBase.cs:line 58
   at AssetRipper.Assets.UnityObjectBaseExtensions.Read(IUnityObjectBase asset, EndianSpanReader& reader) in /Users/huangshaobin/IdeaProjects/AssetRipper/Source/AssetRipper.Assets/IUnityObjectBase.cs:line 103
   at AssetRipper.Import.AssetCreation.GameAssetFactory.TryReadNormalObject(AssetInfo assetInfo, ReadOnlyArraySegment`1 assetData, UnityVersion version, String& error) in /Users/huangshaobin/IdeaProjects/AssetRipper/Source/
```
### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/16441920/AssetRipper.log)

**Comment by ds5678** [comment]
What game is this?

**Comment by ds5678** [comment]
I suspect this game uses a customized engine. The parsing code for engine asset types has proven to be very consistent and reliable.
