### ISSUE TITLE
[Bug]: General [Error] : System.ArgumentException: Unknown attribute 1173142787 for ParticleSystem

### ISSUE THREAD

**Issue by JordanCouturier** [AssetRipper/AssetRipper#1462]
### Are you on the latest version of AssetRipper?

No, I need to download a newer version and try again.

### Which release are you using?

Unselected

### Which Unity version did this occur on?

No idea

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

When the script starts, I get several errors:

`Import : Unable to read MonoBehaviour Structure, because script Base layout mismatched binary content (ArgumentOutOfRangeException).`

And :

```
General : System.ArgumentException: Unknown attribute 1173142787 for ParticleSystem
   at AssetRipper.Processing.AnimationClips.CustomCurveResolver.ToAttributeName(BindingCustomType type, UInt32 attribute, String path) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\CustomCurveResolver.cs:line 364
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.AddCustomCurve(IAnimationClipBindingConstant bindings, IGenericBinding binding, String path, Single time, Single value) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 223
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessStreams(IReadOnlyList`1 streamFrames, IAnimationClipBindingConstant bindings, Single sampleRate) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 125
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessInner() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 59
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Convert(IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 112
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Process(GameData gameData) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 85
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 119
   at AssetRipper.GUI.ConsoleApp.Run(IReadOnlyList`1 filesToExport, String outputDirectory) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\ConsoleApp.cs:line 128
   at AssetRipper.GUI.ConsoleApp.ParseArgumentsAndRun(String[] args) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\ConsoleApp.cs:line 43
```

### Relevant log output

General : Finished reading files
General : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Lighting Data Assets
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
General [Error] : System.ArgumentException: Unknown attribute 1173142787 for ParticleSystem
   at AssetRipper.Processing.AnimationClips.CustomCurveResolver.ToAttributeName(BindingCustomType type, UInt32 attribute, String path) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\CustomCurveResolver.cs:line 364
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.AddCustomCurve(IAnimationClipBindingConstant bindings, IGenericBinding binding, String path, Single time, Single value) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 223
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessStreams(IReadOnlyList`1 streamFrames, IAnimationClipBindingConstant bindings, Single sampleRate) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 125
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessInner() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 59
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Convert(IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 112
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Process(GameData gameData) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 85
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 119
   at AssetRipper.GUI.ConsoleApp.Run(IReadOnlyList`1 filesToExport, String outputDirectory) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\ConsoleApp.cs:line 128
   at AssetRipper.GUI.ConsoleApp.ParseArgumentsAndRun(String[] args) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\ConsoleApp.cs:line 43

**Comment by JordanCouturier** [comment]
[AssetRipper.log](https://github.com/user-attachments/files/16737050/AssetRipper.log)

**Comment by JordanCouturier** [comment]
[AssetRipper.log](https://github.com/user-attachments/files/16737085/AssetRipper.log)

**Comment by ds5678** [comment]
This should not happen on the latest version.
