### ISSUE TITLE
[Bug]: Error decompiling System.Web.dll (My Horse Friends)

### ISSUE THREAD

**Issue by KoleckOLP** [AssetRipper/AssetRipper#1553]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

My Horse Friends

### Which Unity version did this occur on?

4.1.0f4

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I open the game folder in Asset Ripper and click Export Primary. The game exports for a while and fails, with the error log bellow

### Relevant log output

```
In a moment, a line will appear: "Now listening on:" followed by a url.
Open that url in any web browser to access the AssetRipper user interface.

info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://127.0.0.1:58645
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\dokumenty\Stažené\151124\AssetRipper_win_x64
General : Configuration Settings:
General : ExportRootPath: D:\dokumenty\Stažené\151124\AssetRipper_win_x64\Ripped
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : DefaultVersion: 0.0.0a0
General : TargetVersion: 0.0.0a0
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: True
General : EnableAssetDeduplication: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : LightmapTextureExportFormat: Yaml
General : ScriptExportMode: Hybrid
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TextExportMode: Parse
Import : Attempting to read files from D:\dokumenty\Stažené\151124\My Horse Friends\Game
Import : PC game structure has been found at 'D:\dokumenty\Stažené\151124\My Horse Friends\Game'
Import : Collecting game files...
Import : Game file 'mainData' has been found
Import : Collecting Streaming Assets...
Import : Files use the 'Mono' scripting backend.
Import : During Mono initialization, found 38 assemblies
Import : Finished reading files
Processing : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
Processing : Lighting Data Assets
Processing : Finished processing assets
Export : Starting export
Export : Attempting to export assets to D:\dokumenty\Stažené\151124\MHFG\MHFG_primary...
ExportProgress : Exporting 'ArrowMaterial'
ExportProgress : Exporting 'FallVaporFallingRainbow'
ExportProgress : Exporting 'FallVaporRainbow'
ExportProgress : Exporting 'Stars'
ExportProgress : Exporting 'Vapor'
ExportProgress : Exporting 'VaporSplash'
ExportProgress : Exporting 'Light Material'
ExportProgress : Exporting 'Shadow'
ExportProgress : Exporting 'arrow_animation2'
ExportProgress : Exporting 'RainbowSimpleFall'
ExportProgress : Exporting 'VaporStronger'
ExportProgress : Exporting 'Stars'
ExportProgress : Exporting 'FallVapor'
ExportProgress : Exporting 'Light'
ExportProgress : Exporting 'WaveMesh002'
ExportProgress : Exporting 'SandWetStraight'
ExportProgress : Exporting 'SandWetUpCurve'
ExportProgress : Exporting 'SandWetDownCurve'
ExportProgress : Exporting 'BreakingWave'
ExportProgress : Exporting 'Arrow'
ExportProgress : Exporting 'RidingHallColliders'
ExportProgress : Exporting 'CWCamera'
ExportProgress : Exporting 'CWControlAreaTexture'
ExportProgress : Exporting 'BreakingWavesRoot'
ExportProgress : Exporting 'FallParticles'
ExportProgress : Exporting 'GlowParticles'
ExportProgress : Exporting 'WaveParticles'
ExportProgress : Exporting 'Projector'
ExportProgress : Exporting 'Normal-DiffuseFast'
ExportProgress : Exporting 'Normal-Bumped'
ExportProgress : Exporting 'Normal-Glossy'
ExportProgress : Exporting 'Normal-BumpSpec'
ExportProgress : Exporting 'Normal-DiffuseDetail'
ExportProgress : Exporting 'Normal-VertexLit'
ExportProgress : Exporting 'Normal-Diffuse'
ExportProgress : Exporting 'Normal-Parallax'
ExportProgress : Exporting 'Normal-ParallaxSpec'
ExportProgress : Exporting 'Illumin-Diffuse'
ExportProgress : Exporting 'Illumin-Bumped'
ExportProgress : Exporting 'Illumin-Glossy'
ExportProgress : Exporting 'Illumin-BumpSpec'
ExportProgress : Exporting 'Illumin-VertexLit'
ExportProgress : Exporting 'Illumin-Parallax'
ExportProgress : Exporting 'Illumin-ParallaxSpec'
ExportProgress : Exporting 'Reflect-Diffuse'
ExportProgress : Exporting 'Reflect-Bumped'
ExportProgress : Exporting 'Reflect-Glossy'
ExportProgress : Exporting 'Reflect-BumpSpec'
ExportProgress : Exporting 'Reflect-VertexLit'
ExportProgress : Exporting 'Reflect-BumpNolight'
ExportProgress : Exporting 'Reflect-BumpVertexLit'
ExportProgress : Exporting 'Reflect-Parallax'
ExportProgress : Exporting 'Reflect-ParallaxSpec'
ExportProgress : Exporting 'Alpha-Diffuse'
ExportProgress : Exporting 'Alpha-Bumped'
ExportProgress : Exporting 'Alpha-Glossy'
ExportProgress : Exporting 'Alpha-BumpSpec'
ExportProgress : Exporting 'Alpha-VertexLit'
ExportProgress : Exporting 'Alpha-Parallax'
ExportProgress : Exporting 'Alpha-ParallaxSpec'
ExportProgress : Exporting 'AlphaTest-VertexLit'
ExportProgress : Exporting 'AlphaTest-Diffuse'
ExportProgress : Exporting 'AlphaTest-Bumped'
ExportProgress : Exporting 'AlphaTest-Glossy'
ExportProgress : Exporting 'AlphaTest-BumpSpec'
ExportProgress : Exporting 'Shadow-ScreenBlur'
ExportProgress : Exporting 'Camera-DepthTexture'
ExportProgress : Exporting 'Camera-DepthNormalTexture'
ExportProgress : Exporting 'Internal-PrePassLighting'
ExportProgress : Exporting 'Internal-PrePassCollectShadows'
ExportProgress : Exporting 'Internal-CombineDepthNormals'
ExportProgress : Exporting 'Internal-BlitCopy'
ExportProgress : Exporting 'Shadow-ScreenBlurRotated'
ExportProgress : Exporting 'Internal-Clear'
ExportProgress : Exporting 'Shader'
ExportProgress : Exporting 'Flare'
ExportProgress : Exporting 'Internal-Flare'
ExportProgress : Exporting 'skybox cubed'
ExportProgress : Exporting 'Skybox'
ExportProgress : Exporting 'Internal-Halo'
ExportProgress : Exporting 'Particle Add'
ExportProgress : Exporting 'Particle AddMultiply'
ExportProgress : Exporting 'Particle AddSmooth'
ExportProgress : Exporting 'Particle Alpha Blend'
ExportProgress : Exporting 'Particle Multiply'
ExportProgress : Exporting 'Particle MultiplyDouble'
ExportProgress : Exporting 'Particle Premultiply Blend'
ExportProgress : Exporting 'Particle VertexLit Blended'
ExportProgress : Exporting 'Internal-GUITextureClip'
ExportProgress : Exporting 'Internal-GUITextureClipText'
ExportProgress : Exporting 'Internal-GUITexture'
ExportProgress : Exporting 'Internal-GUITextureBlit'
ExportProgress : Exporting 'Soft'
ExportProgress : Exporting 'Font Material'
ExportProgress : Exporting 'Font'
ExportProgress : Exporting 'Arial'
ExportProgress : Failed to export 'Arial'
ExportProgress : Exporting 'Font Texture'
ExportProgress : Exporting 'pSphere1'
ExportProgress : Exporting 'Cube'
ExportProgress : Exporting 'pCylinder1'
ExportProgress : Exporting 'pPlane1'
ExportProgress : Exporting 'polySurface2'
ExportProgress : Exporting 'Cylinder'
ExportProgress : Exporting 'Sphere'
ExportProgress : Exporting 'Capsule'
ExportProgress : Exporting 'Plane'
ExportProgress : Exporting 'Default-Particle'
ExportProgress : Exporting 'Default-Particle'
ExportProgress : Exporting 'Default-Diffuse'
ExportProgress : Exporting 'UnityWatermark-small'
ExportProgress : Exporting 'EscToExit_back'
ExportProgress : Exporting 'EscToExit_Text'
ExportProgress : Exporting 'UnitySplash'
ExportProgress : Exporting 'UnitySplash2'
ExportProgress : Exporting 'UnitySplash3'
ExportProgress : Exporting 'UnitySplashBack'
ExportProgress : Exporting 'UnityWatermark-trial'
ExportProgress : Exporting 'UnityWatermark-beta'
ExportProgress : Exporting 'UnityWatermark-edu'
ExportProgress : Exporting 'UnityWatermark-dev'
ExportProgress : Exporting 'WarningSign'
ExportProgress : Exporting 'UnityWatermark-DebugFlashPlayer'
ExportProgress : Exporting 'UnityWatermark-proto'
ExportProgress : Exporting 'UnityWatermarkPlugin-beta'
ExportProgress : Exporting 'VertexLit'
ExportProgress : Exporting 'WavingGrass'
ExportProgress : Exporting 'WavingGrassBillboard'
ExportProgress : Exporting 'AddPass'
ExportProgress : Exporting 'FirstPass'
ExportProgress : Exporting 'BillboardTree'
ExportProgress : Exporting 'AlphaTest-SoftEdgeUnlit'
ExportProgress : Exporting 'GameSkin'
ExportProgress : Exporting 'box'
ExportProgress : Exporting 'button active'
ExportProgress : Exporting 'button hover'
ExportProgress : Exporting 'button on hover'
ExportProgress : Exporting 'button on'
ExportProgress : Exporting 'button'
ExportProgress : Exporting 'horizontal scrollbar thumb'
ExportProgress : Exporting 'horizontal scrollbar'
ExportProgress : Exporting 'horizontalslider'
ExportProgress : Exporting 'slider thumb active'
ExportProgress : Exporting 'slider thumb'
ExportProgress : Exporting 'slidert humb hover'
ExportProgress : Exporting 'toggle active'
ExportProgress : Exporting 'toggle hover'
ExportProgress : Exporting 'toggle on hover'
ExportProgress : Exporting 'toggle on'
ExportProgress : Exporting 'toggle on active'
ExportProgress : Exporting 'toggle'
ExportProgress : Exporting 'vertical scrollbar thumb'
ExportProgress : Exporting 'vertical scrollbar'
ExportProgress : Exporting 'verticalslider'
ExportProgress : Exporting 'window on'
ExportProgress : Exporting 'window'
ExportProgress : Exporting 'textfield'
ExportProgress : Exporting 'textfield on'
ExportProgress : Exporting 'textfield hover'
ExportProgress : Exporting 'ScriptExportCollection'
System.AggregateException: One or more errors occurred. (Error decompiling @060039F9 System.Web.UI.WebControls.XmlHierarchyData.XmlHierarchyDataPropertyDescriptor.SetValue)
 ---> Error decompiling @060039F9 System.Web.UI.WebControls.XmlHierarchyData.XmlHierarchyDataPropertyDescriptor.SetValue
in assembly "D:\dokumenty\Stažené\151124\MHFG\MHFG_primary\Assemblies\System.Web.dll"
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'targetBlock')

-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](TaskReplicator.ReplicatableUserAction`1, ParallelOptions, Boolean) + 0x14d
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1, ParallelOptions, Action`1, Action`2, Action`3, Func`4, Func`5, Func`1, Action`1) + 0x31e
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection, CancellationToken, Exception) + 0x30
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1, ParallelOptions, Action`1, Action`2, Action`3, Func`4, Func`5, Func`1, Action`1) + 0x4cd
   at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1, ParallelOptions, Action`1) + 0x55
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>g__ProcessFiles|3(List`1) + 0xec
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.WriteCodeFilesInProject(PEFile, IList`1, CancellationToken) + 0x1c8
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.DecompileProject(PEFile, String, TextWriter, CancellationToken) + 0xd0
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.DecompileProject(PEFile, String, CancellationToken) + 0xc4
   at AssetRipper.Export.PrimaryContent.Scripts.ScriptExportCollection.Export(String) + 0x49c
   at AssetRipper.Export.PrimaryContent.PrimaryContentExporter.Export(GameBundle, CoreConfiguration) + 0xd2
   at AssetRipper.GUI.Web.GameFileLoader.ExportPrimaryContent(String) + 0x104
   at AssetRipper.GUI.Web.Pages.Commands.ExportPrimaryContent.<AssetRipper-GUI-Web-Pages-ICommand-Execute>d__0.MoveNext() + 0x191
--- End of stack trace from previous location ---
   at AssetRipper.GUI.Web.Pages.Commands.<HandleCommand>d__7`1.MoveNext() + 0x56
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.<Invoke>d__5.MoveNext() + 0xaa
--- End of stack trace from previous location ---
   at AssetRipper.GUI.Web.ErrorHandlingMiddleware.<InvokeAsync>d__0.MoveNext() + 0x4e
   ```

**Comment by epicEaston197** [comment]
I've had the same problem with inscryption and Outer Wilds really annoying I'm stuck with the low quality version of the planets because it couldn't fully export lol

**Comment by ds5678** [comment]
@epicEaston197 can you paste your stack trace too?

**Comment by epicEaston197** [comment]
> @epicEaston197 can you paste your stack trace too?

```
System.AggregateException: One or more errors occurred. (Error decompiling @06001E1B Rewired.ControllerMapWithAxes.ElementAssignmentConflicts) (Error decompiling @0600217F Rewired.Player.ControllerHelper.ConflictCheckingHelper.EIAMTeYTzkpYuqceTkIDhqNYXBX) (Error decompiling @0600138C Rewired.Data.UserData.rhVUPGaJJCJHUMOXsDTCuinQFRsB)
 ---> Error decompiling @06001E1B Rewired.ControllerMapWithAxes.ElementAssignmentConflicts
in assembly "C:\Easton's Stuff\Temp\New folder (2)\Assemblies\Rewired_Core.dll"
 ---> System.NullReferenceException: Object reference not set to an instance of an object.

-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](TaskReplicator.ReplicatableUserAction`1, ParallelOptions, Boolean) + 0x14d
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1, ParallelOptions, Action`1, Action`2, Action`3, Func`4, Func`5, Func`1, Action`1) + 0x266
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection, CancellationToken, Exception) + 0x30
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1, ParallelOptions, Action`1, Action`2, Action`3, Func`4, Func`5, Func`1, Action`1) + 0x3ec
   at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1, ParallelOptions, Action`1) + 0x55
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>g__ProcessFiles|3(List`1) + 0xec
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.WriteCodeFilesInProject(MetadataFile, IList`1, CancellationToken) + 0x1c8
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.DecompileProject(MetadataFile, String, TextWriter, CancellationToken) + 0xd2
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.DecompileProject(MetadataFile, String, CancellationToken) + 0xc4
   at AssetRipper.Export.PrimaryContent.Scripts.ScriptExportCollection.Export(String, FileSystem) + 0x558
   at AssetRipper.Export.PrimaryContent.PrimaryContentExporter.Export(GameBundle, CoreConfiguration, FileSystem) + 0xe0
   at AssetRipper.GUI.Web.GameFileLoader.ExportPrimaryContent(String) + 0x123
   at AssetRipper.GUI.Web.Pages.Commands.ExportPrimaryContent.<AssetRipper-GUI-Web-Pages-ICommand-Execute>d__0.MoveNext() + 0x191
--- End of stack trace from previous location ---
   at AssetRipper.GUI.Web.Pages.Commands.<HandleCommand>d__7`1.MoveNext() + 0x56
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.<Invoke>d__5.MoveNext() + 0xaa
--- End of stack trace from previous location ---
   at AssetRipper.GUI.Web.ErrorHandlingMiddleware.<InvokeAsync>d__0.MoveNext() + 0x4e
 ---> (Inner Exception #1) Error decompiling @0600217F Rewired.Player.ControllerHelper.ConflictCheckingHelper.EIAMTeYTzkpYuqceTkIDhqNYXBX
in assembly "C:\Easton's Stuff\Temp\New folder (2)\Assemblies\Rewired_Core.dll"
 ---> System.NullReferenceException: Object reference not set to an instance of an object.

-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)<---

 ---> (Inner Exception #2) Error decompiling @0600138C Rewired.Data.UserData.rhVUPGaJJCJHUMOXsDTCuinQFRsB
in assembly "C:\Easton's Stuff\Temp\New folder (2)\Assemblies\Rewired_Core.dll"
 ---> System.NullReferenceException: Object reference not set to an instance of an object.

-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)<---
```

**Comment by epicEaston197** [comment]
This could be completely unrelated with this issue I just took line one and put it into the Github search and this was the first issue that popped up and it was the only issue that popped up

**Comment by ds5678** [comment]
It is loosely related. If you search for Rewired, you'll notice that obfuscated binaries often decompile poorly in ILSpy. You should make a separate issue.

**Comment by ds5678** [comment]
In regards to System.Web.dll failing to decompile, I'm not sure why we even want to decompile this file. It's a system library, so it shouldn't need decompiled at all.

**Comment by epicEaston197** [comment]
> It is loosely related. If you search for Rewired, you'll notice that obfuscated binaries often decompile poorly in ILSpy. You should make a separate issue.

The thing is I don't know any technical details all that I know is I have an error I went to make a separate issue and I will I just don't know what to name it or the technical details I need to describe like should it be like "1. own outer wilds 2. try to rip files from it?"

**Comment by ds5678** [comment]
Just do your best.

**Comment by ds5678** [comment]
@epicEaston197 Are you still encountering the problem?

**Comment by ds5678** [comment]
I submitted a pull request to ILSpy that fixes this problem, but I don't know how long it'll take them to merge and do a release.
