### ISSUE TITLE
[Bug]: Failed to load game content: No data left

### ISSUE THREAD

**Issue by Q4st** [AssetRipper/AssetRipper#168]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2018.4.28f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

Prompt when I unpack the weapon accessories in Takov ：Failed to load game content: No data left

[https://drive.google.com/file/d/12cCn_ZXERe7jqdgkzcckGIzS3fqxGSpO/view?usp=sharing](sample)

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19041.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.1.8.1
System : AssetRipper Build Type: Release x64 Published
System : Current UTC Time: 2021/11/10 15:42:50
System : Loading locale en_US.json
: Language English (United Kingdom) isActive False
: Language English (United States) isActive True
: Language español isActive False
: Language Indonesia isActive False
: Language italiano isActive False
: Language português (Brasil) isActive False
: Language 中文（简体） isActive False
System : Available languages: en_GB, en_US, es, id, it, pt_BR, zh_Hans
General : Attempting to read files from C:\Users\LiangZ\Desktop\mag_ak_izhmash_6l29_556x45_30.bundle
Import : Game file 'mag_ak_izhmash_6l29_556x45_30.bundle' has been found
Import : Mixed game structure has been found for 1 path(s)
[Error] : System.Exception: No data left
   at AssetRipper.Core.Extensions.StreamExtensions.CopyStream(Stream _this, Stream dstStream, Int64 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Extensions\StreamExtensions.cs:line 62
   at AssetRipper.Core.Parser.Files.BundleFile.IO.BundleFileBlockReader.ReadEntry(Node entry) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\IO\BundleFileBlockReader.cs:line 110
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadFileStreamData(Stream stream, Int64 basePosition, Int64 headerSize) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\BundleFileScheme.cs:line 214
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\BundleFileScheme.cs:line 60
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\BundleFileScheme.cs:line 40
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\SchemeReader.cs:line 58
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\SchemeReader.cs:line 20
   at AssetRipper.Core.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 113
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 61
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 40
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 32
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 103
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIImportManager.cs:line 24

**Comment by cyberangel67** [comment]
Have also seen this error with Addressables in Unity 2019.4

**Comment by ds5678** [comment]
If this issue can be reproduced with files compiled from a test Unity project, I'll reconsider looking into it.
