### ISSUE TITLE
[Bug]: Error

### ISSUE THREAD

**Issue by vale7z4387ruwrejmhsr** [AssetRipper/AssetRipper#226]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2018.2.21

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

i tried to export the game content and it says 
Failed to export game content: Value cannot be null

### Relevant log output

System.ArgumentNullException: Value cannot be null.
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at Mono.Cecil.Cil.CodeReader.PatchRawCode(ByteBuffer buffer, Int32 code_size, CodeWriter writer)
   at Mono.Cecil.Cil.CodeReader.PatchRawFatMethod(ByteBuffer buffer, CodeWriter writer, Int32& code_size, MetadataToken& local_var_token)
   at Mono.Cecil.Cil.CodeReader.PatchRawMethodBody(MethodDefinition method, CodeWriter writer, Int32& code_size, MetadataToken& local_var_token)
   at Mono.Cecil.Cil.CodeWriter.WriteUnresolvedMethodBody(MethodDefinition method)
   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddNestedTypes(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(Stream stream)
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver.CreatePEFile(AssemblyDefinition assembly) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 42
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver..ctor(ReadOnlySpan`1 assemblies) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 20
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver..ctor(IAssemblyManager manager) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 15
   at AssetRipper.Library.Exporters.Scripts.ScriptDecompiler..ctor(IAssemblyManager assemblyManager) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptDecompiler.cs:line 18
   at AssetRipper.Library.Exporters.Scripts.ScriptExporter.Export(IExportContainer container, IEnumerable`1 assets, String dirPath, Action`3 callback) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptExporter.cs:line 91
   at AssetRipper.Library.Exporters.Scripts.ScriptExportCollection.Export(IProjectAssetContainer container, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptExportCollection.cs:line 81
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 149
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 68
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 91
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, IEnumerable`1 assets) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 144
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 128
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 46

**Comment by ds5678** [comment]
Closed in favor of #227

**Comment by ds5678** [comment]
As a work-around, you can disable script export
