### ISSUE TITLE
[Bug]: Could not initialize container!

### ISSUE THREAD

**Issue by vale7z4387ruwrejmhsr** [AssetRipper/AssetRipper#230]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2018.3.9

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

i was trying to export the audio files to wav files and it gave me a error saying Could not initialize container!

### Relevant log output

System.ArgumentException: Could not initialize container!
   at NAudio.Vorbis.VorbisSampleProvider..ctor(Stream sourceStream, Boolean closeOnDispose)
   at NAudio.Vorbis.VorbisWaveReader..ctor(Stream sourceStream, Boolean closeOnDispose)
   at AssetRipper.Library.Exporters.Audio.AudioConverter.OggToWav(Byte[] oggData) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Audio\AudioConverter.cs:line 12
   at AssetRipper.Library.Exporters.Audio.AudioClipExporter.Export(IExportContainer container, IUnityObjectBase asset, String path) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Audio\AudioClipExporter.cs:line 33
   at AssetRipper.Core.Project.Collections.AssetExportCollection.ExportInner(IProjectAssetContainer container, String filePath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetExportCollection.cs:line 92
   at AssetRipper.Core.Project.Collections.AssetExportCollection.Export(IProjectAssetContainer container, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetExportCollection.cs:line 58
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 157
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 68
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 90
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, IEnumerable`1 assets) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 144
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 128
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 45

**Comment by ds5678** [comment]
If you export as ogg, do the audio files play?

**Comment by vale7z4387ruwrejmhsr** [comment]
well some do but some just don't and the one's that do not play unity says that the ones that don't play the original size is 0 B wich i guess means bytes

**Comment by ds5678** [comment]
I just pushed 0f1229b636e3ddca2f6e2f2c24e637ff7bd73b50 which should fix this, though your unplayable files will still be unplayable

**Comment by ds5678** [comment]
Did it work for you?

**Comment by vale7z4387ruwrejmhsr** [comment]
nope same thing still

**Comment by ds5678** [comment]
fixed in a1e4bf3cd405c5885d524f5a1b05433e1aec62e1
