### ISSUE TITLE
[Bug]: SerializedFileHeader.IsSerializedFileHeader: uint filesize argument overflows

### ISSUE THREAD

**Issue by arigo** [AssetRipper/AssetRipper#236]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Console Version Windows x64

### Which Unity version did this occur on?

2020.1.17

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

```
General : System.OverflowException: Arithmetic operation resulted in an overflow.
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.IsSerializedFile(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 66
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\SchemeReader.cs:line 77
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\SchemeReader.cs:line 22
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.AddDependencySchemes(Func`2 dependencyCallback) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructureProcessor.cs:line 69```

This comes from the cast of the stream's Length to a uint.  The game in questions has got a 5 GB file, so that cast overflows.  I suggest to change the signature of `SerializedFileHeader.IsSerializedFileHeader()` so that it takes a `long filesize` argument directly, so that the failing cast is no longer necessary.  On recent Unity versions it's possible that the files are more than 4GB, and the format generation >= 22 can contain a full 64-bit size value which we want to check against.

### Relevant log output

_No response_

**Comment by ds5678** [comment]
Thank you for reporting
