### ISSUE TITLE
[Bug]: Error during reading of asset type TerrainData

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#241]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest pre-release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2021.2.4f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hi,

I saw that Unity Version 2021.2+ is not (yet ?) supported, so maybe this isn't relevant.
Anyway, here is the error I get when loading a Unity 2021.2.4f1 game.

MessageBox: Error
Check log for more details.

I think it is a read error when trying to read TreeInstances...

Windows 10 4x64
using code from 26/01/2022 (commit 1272e48)

Hope this can be usefull
Regards,
Zbuffer

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19042.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.1.8.1
System : AssetRipper Build Type: Debug x64 Compiled
System : UTC Current Time: 26/01/2022 10:56:44
System : UTC Compile Time: Unknown
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : IgnoreStreamingAssets: False
General : ExportPath: F:\_DEV2\AssetRipper-master\Bins\AssetRipperGUI\DebugWindows\Ripped
General : ExportDependencies: False
General : IgnoreAssetBundleContentPaths: False
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshCoordinateSpace: Unity
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: CSharp7_3
General : SpriteExportMode: Native
General : TerrainExportMode: Native
General : TextExportMode: Parse
General : Attempting to read files from E:\Games\Mon Bazou\Mon Bazou_Data
Import : PC data directory found. Setting root to parent directory
Import : PC game structure has been found at 'E:\Games\Mon Bazou\Mon Bazou_Data'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level2' has been found
Import : Collecting Streaming Assets...
Import : Files use the 'Mono' scripting backend.
Import : During Mono initialization, found 108 assemblies
Import : Resource file 'sharedassets0.assets.resS' has been loaded
[Error] : SerializedFileException: v:2021.2.4f1 p:StandaloneWin64Player t:TerrainData n:sharedassets0.assets
Path:E:\Games\Mon Bazou\Mon Bazou_Data\sharedassets0.assets
Message: Error during reading of asset type TerrainData
Inner: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T](Boolean allowAlignment) in F:\_DEV2\AssetRipper-master\AssetRipperCommon\IO\Asset\AssetReader.cs:line 51
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]() in F:\_DEV2\AssetRipper-master\AssetRipperCommon\IO\Asset\AssetReader.cs:line 45
   at AssetRipper.Core.Classes.TerrainData.TreeDatabase.Read(AssetReader reader) in F:\_DEV2\AssetRipper-master\AssetRipperCore\Classes\TerrainData\TreeDatabase.cs:line 16
   at AssetRipper.Core.Classes.TerrainData.DetailDatabase.Read(AssetReader reader) in F:\_DEV2\AssetRipper-master\AssetRipperCore\Classes\TerrainData\DetailDatabase.cs:line 77
   at AssetRipper.Core.Classes.TerrainData.TerrainData.Read(AssetReader reader) in F:\_DEV2\AssetRipper-master\AssetRipperCore\Classes\TerrainData\TerrainData.cs:line 49
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in F:\_DEV2\AssetRipper-master\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 364
StackTrace:    at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in F:\_DEV2\AssetRipper-master\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 369
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, ObjectInfo& info) in F:\_DEV2\AssetRipper-master\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 331
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadData(Stream stream) in F:\_DEV2\AssetRipper-master\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 262
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in F:\_DEV2\AssetRipper-master\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 54
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in F:\_DEV2\AssetRipper-master\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 44
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in F:\_DEV2\AssetRipper-master\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 44
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadSerializedFiles() in F:\_DEV2\AssetRipper-master\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 30
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.ProcessSchemes(GameCollection fileCollection) in F:\_DEV2\AssetRipper-master\AssetRipperCommon\Structure\GameStructure\GameStructureProcessor.cs:line 92
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in F:\_DEV2\AssetRipper-master\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 79
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in F:\_DEV2\AssetRipper-master\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 39
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in F:\_DEV2\AssetRipper-master\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 31
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in F:\_DEV2\AssetRipper-master\AssetRipperLibrary\Ripper.cs:line 116
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in F:\_DEV2\AssetRipper-master\AssetRipperGUI\Managers\UIImportManager.cs:line 24

**Comment by ds5678** [comment]
I am nearing completion on #164. When that's done, this should be fixed by default.

**Comment by Zbuffers** [comment]
Great to hear that ! ;)

**Comment by ds5678** [comment]
Closing due to redundancy
