### ISSUE TITLE
[Bug]: Failed to load game content: Error during reading of asset type Shader

### ISSUE THREAD

**Issue by Brofotet** [AssetRipper/AssetRipper#250]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2021.1.0f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Error during reading asset type Shader
Please help

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19042.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.1.8.1
System : AssetRipper Build Type: Release x64 Published
System : Current UTC Time: 31.01.2022 21:25:13
System : Loading locale en_US.json
: Language English (United Kingdom) isActive False
: Language English (United States) isActive True
: Language español isActive False
: Language Indonesia isActive False
: Language italiano isActive False
: Language português (Brasil) isActive False
: Language 中文（简体） isActive False
System : Available languages: en_GB, en_US, es, id, it, pt_BR, zh_Hans
General : Attempting to read files from D:\Games\Beholder 3 v10.11.2021\Beholder3_Data
Import : PC data directory found. Setting root to parent directory
Import : PC game structure has been found at 'D:\Games\Beholder 3 v10.11.2021\Beholder3_Data'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level10' has been found
Import : Game file 'level11' has been found
Import : Game file 'level12' has been found
Import : Game file 'level13' has been found
Import : Game file 'level14' has been found
Import : Game file 'level15' has been found
Import : Game file 'level16' has been found
Import : Game file 'level17' has been found
Import : Game file 'level18' has been found
Import : Game file 'level2' has been found
Import : Game file 'level3' has been found
Import : Game file 'level4' has been found
Import : Game file 'level5' has been found
Import : Game file 'level6' has been found
Import : Game file 'level7' has been found
Import : Game file 'level8' has been found
Import : Game file 'level9' has been found
Import : Collecting Streaming Assets...
Import : Asset bundle 'localization-assets-shared_assets_all' has been found
Import : Asset bundle 'localization-locales_assets_all' has been found
Import : Asset bundle 'localization-stringtables_assets_all' has been found
Import : Files use the 'Unknown' scripting backend.
[Error] : SerializedFileException: v:2021.1.0f1 p:StandaloneWin64Player t:Shader n:unity default resources
Path:D:\Games\Beholder 3 v10.11.2021\Beholder3_Data\Resources\unity default resources
Message: Error during reading of asset type Shader
Inner: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 71
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedProgramParameters.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\SerializedShader\SerializedProgramParameters.cs:line 22
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedProgram.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\SerializedShader\SerializedProgram.cs:line 18
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedPass.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\SerializedShader\SerializedPass.cs:line 50
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 75
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 75
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedShader.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\SerializedShader\SerializedShader.cs:line 30
   at AssetRipper.Core.Classes.Shader.Shader.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\Shader.cs:line 96
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 331
StackTrace:    at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 335
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, ObjectInfo& info) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 313
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadData(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 262
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 38
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 44
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 44
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadSerializedFiles() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 30
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.ProcessSchemes(GameCollection fileCollection) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructureProcessor.cs:line 92
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 80
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 40
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 32
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 103
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIImportManager.cs:line 24

General : Attempting to read files from D:\Games\Beholder 3 v10.11.2021
Import : PC game structure has been found at 'D:\Games\Beholder 3 v10.11.2021'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level10' has been found
Import : Game file 'level11' has been found
Import : Game file 'level12' has been found
Import : Game file 'level13' has been found
Import : Game file 'level14' has been found
Import : Game file 'level15' has been found
Import : Game file 'level16' has been found
Import : Game file 'level17' has been found
Import : Game file 'level18' has been found
Import : Game file 'level2' has been found
Import : Game file 'level3' has been found
Import : Game file 'level4' has been found
Import : Game file 'level5' has been found
Import : Game file 'level6' has been found
Import : Game file 'level7' has been found
Import : Game file 'level8' has been found
Import : Game file 'level9' has been found
Import : Collecting Streaming Assets...
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import : Files use the 'Unknown' scripting backend.
Import : Resource file 'globalgamemanagers.assets.resS' has been loaded
[Error] : SerializedFileException: v:2021.1.0f1 p:StandaloneWin64Player t:Shader n:globalgamemanagers.assets
Path:D:\Games\Beholder 3 v10.11.2021\Beholder3_Data\globalgamemanagers.assets
Message: Error during reading of asset type Shader
Inner: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at AssetRipper.Core.Classes.Shader.Parameters.VectorParameter.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\Parameters\VectorParameter.cs:line 28
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 75
   at AssetRipper.Core.Classes.Shader.Parameters.ConstantBuffer.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\Parameters\ConstantBuffer.cs:line 33
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 75
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedProgramParameters.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\SerializedShader\SerializedProgramParameters.cs:line 23
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedProgram.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\SerializedShader\SerializedProgram.cs:line 18
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedPass.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\SerializedShader\SerializedPass.cs:line 49
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 75
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 75
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedShader.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\SerializedShader\SerializedShader.cs:line 30
   at AssetRipper.Core.Classes.Shader.Shader.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\Shader.cs:line 96
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 331
StackTrace:    at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 335
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, ObjectInfo& info) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 313
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadData(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 262
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 38
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 44
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadSerializedFiles() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 30
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.ProcessSchemes(GameCollection fileCollection) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructureProcessor.cs:line 92
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 80
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 40
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 32
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 103
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIImportManager.cs:line 24

General : Attempting to read files from D:\Games\Beholder 3 v10.11.2021\Beholder3_Data
Import : PC data directory found. Setting root to parent directory
Import : PC game structure has been found at 'D:\Games\Beholder 3 v10.11.2021\Beholder3_Data'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level10' has been found
Import : Game file 'level11' has been found
Import : Game file 'level12' has been found
Import : Game file 'level13' has been found
Import : Game file 'level14' has been found
Import : Game file 'level15' has been found
Import : Game file 'level16' has been found
Import : Game file 'level17' has been found
Import : Game file 'level18' has been found
Import : Game file 'level2' has been found
Import : Game file 'level3' has been found
Import : Game file 'level4' has been found
Import : Game file 'level5' has been found
Import : Game file 'level6' has been found
Import : Game file 'level7' has been found
Import : Game file 'level8' has been found
Import : Game file 'level9' has been found
Import : Collecting Streaming Assets...
Import : Asset bundle 'localization-assets-shared_assets_all' has been found
Import : Asset bundle 'localization-locales_assets_all' has been found
Import : Asset bundle 'localization-stringtables_assets_all' has been found
Import : Files use the 'Mono' scripting backend.
Import : During Mono initialization, found 151 assemblies
[Error] : SerializedFileException: v:2021.1.0f1 p:StandaloneWin64Player t:Shader n:unity default resources
Path:D:\Games\Beholder 3 v10.11.2021\Beholder3_Data\Resources\unity default resources
Message: Error during reading of asset type Shader
Inner: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 71
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedProgramParameters.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\SerializedShader\SerializedProgramParameters.cs:line 22
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedProgram.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\SerializedShader\SerializedProgram.cs:line 18
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedPass.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\SerializedShader\SerializedPass.cs:line 50
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 75
   at AssetRipper.Core.IO.Asset.AssetReader.ReadAssetArray[T]() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 75
   at AssetRipper.Core.Classes.Shader.SerializedShader.SerializedShader.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\SerializedShader\SerializedShader.cs:line 30
   at AssetRipper.Core.Classes.Shader.Shader.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Shader\Shader.cs:line 96
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 335
StackTrace:    at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 335
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, ObjectInfo& info) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 312
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadData(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 262
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 38
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 44
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 44
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadSerializedFiles() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameProcessorContext.cs:line 30
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.ProcessSchemes(GameCollection fileCollection) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructureProcessor.cs:line 92
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 80
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 40
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 32
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 103
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIImportManager.cs:line 24

**Comment by ds5678** [comment]
I just pushed a new release. Can you try with that?

**Comment by Brofotet** [comment]
All worked! Thanks!
