### ISSUE TITLE
[Enhancement]: User Specification for Stripped Unity Version

### ISSUE THREAD

**Issue by 11-59pm** [AssetRipper/AssetRipper#252]
I'm trying to rip anim files from the game named "IDOLY PRIDE" - which is a mobile phone game based on Unity

![image](https://user-images.githubusercontent.com/50797622/152381117-be94577f-e45b-4689-9446-aeaed5d123b7.png)
This seems to be based on Unity version 2020.3.18f1 when viewed on HEX editor

However, when I try to load files on AssetRipper, it displays the CAB-number, however with this error message on console, and the program cannot grab the file type properly. It seems that the program does not seem to get the version of the file properly.

The program displays 
![image](https://user-images.githubusercontent.com/50797622/152385094-85e0e146-3296-4246-aa35-97441c813a71.png)

The logs are :
> Import : Game file 'mot_adv_chr_ai_appr-001_in.unity3d' has been found
Import : Mixed game structure has been found at %MYPATH%mot_adv_chr_ai_appr-001_in.unity3d
Import : Files use the 'Unknown' scripting backend.
Error during reading of asset type MonoScript. V: 0.0.0f0 P: Android N: cab-e35dce446cf765ff5db70a6b6e702377 Path: %MYPATH%mot_adv_chr_ai_appr-001_in.unity3d
System.Exception: End of stream. Read 71, expected 1761607680 bytes
   at AssetRipper.Core.IO.Endian.EndianReader.ReadStringBuffer(Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Endian\EndianReader.cs:line 548
   at AssetRipper.Core.IO.Asset.AssetReader.ReadString() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 29
   at AssetRipper.Core.Classes.MonoScript.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\MonoScript.cs:line 122
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 360

> Error during reading of asset type MonoBehaviour. V: 0.0.0f0 P: Android N: cab-e35dce446cf765ff5db70a6b6e702377 Path: %MYPATH%mot_adv_chr_ai_appr-001_in.unity3d
System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at AssetRipper.Core.IO.Asset.AssetReader.ReadString() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 30
   at AssetRipper.Core.Classes.MonoBehaviour.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\MonoBehaviour.cs:line 26
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 360

> Error during reading of asset type AssetBundle. V: 0.0.0f0 P: Android N: cab-e35dce446cf765ff5db70a6b6e702377 Path: %MYPATH%mot_adv_chr_ai_appr-001_in.unity3d
System.Exception: End of stream. Read 166, expected 55745 bytes
   at AssetRipper.Core.IO.Endian.EndianReader.ReadStringBuffer(Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Endian\EndianReader.cs:line 548
   at AssetRipper.Core.IO.Asset.AssetReader.ReadString() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 29
   at AssetRipper.Core.IO.Extensions.AssetReaderExtensions.ReadKVPStringTArray[T](AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Extensions\AssetReaderExtensions.cs:line 61
   at AssetRipper.Core.Classes.AssetBundle.AssetBundle.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\AssetBundle\AssetBundle.cs:line 84
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 360

> Error during reading of asset type AnimationClip. V: 0.0.0f0 P: Android N: cab-e35dce446cf765ff5db70a6b6e702377 Path: %MYPATH%mot_adv_chr_ai_appr-001_in.unity3d
System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at AssetRipper.Core.IO.Extensions.IDictionaryReadAssetExtensions.Read[T](IDictionary`2 _this, AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Extensions\IDictionaryReadAssetExtensions.cs:line 122
   at AssetRipper.Core.Classes.AnimationClip.AnimationClip.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\AnimationClip\AnimationClip.cs:line 200
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 360

> Error during reading of asset type AnimationClip. V: 0.0.0f0 P: Android N: cab-e35dce446cf765ff5db70a6b6e702377 Path: %MYPATH%mot_adv_chr_ai_appr-001_in.unity3d
System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at AssetRipper.Core.IO.Extensions.IDictionaryReadAssetExtensions.Read[T](IDictionary`2 _this, AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Extensions\IDictionaryReadAssetExtensions.cs:line 122
   at AssetRipper.Core.Classes.AnimationClip.AnimationClip.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\AnimationClip\AnimationClip.cs:line 200
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 360

In other asset-viewer programs like AssetStudio or UABEA, the program has a UI which enables to manually set the engine version when opening heavily serialized assets like this (with Unity version stripped) - so I think it would be helpful to add such a function also in this one. 
![image](https://user-images.githubusercontent.com/50797622/152382773-2f2b2064-90e2-4172-a2d5-c389061ed003.png)

The other asset bundle from the same game without version specified
![image](https://user-images.githubusercontent.com/50797622/152382371-8937a048-d23e-469b-b2b4-6beac54b4f0f.png)

The other asset bundle from the same game with version specified (ver : 2020.3.18f1)
![image](https://user-images.githubusercontent.com/50797622/152382235-39396d10-1ac4-4d9f-9f11-cbe16585d717.png)

Here are the assets I tried to open : 
https://drive.google.com/file/d/1XrFeQCRVngfX0s-V73n-mG9ttbvrH5pj/view?usp=sharing
https://drive.google.com/file/d/1oIYfdyNexck830vAP5qdoEO9rymEn3Bo/view?usp=sharing

Best regards.
Thanks for making a wonderful tool

**Comment by 11-59pm** [comment]
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/7996276/AssetRipper.log)

**Comment by ds5678** [comment]
Note for later: the serialized files inside an asset bundle can have stripped versions even if the bundle itself does not have a stripped version.

**Comment by ds5678** [comment]
With a54cae1e35f2d5b6be6d83c883f01febc9cbea02 implemented, this has been reduced to a UI problem.

**Comment by ds5678** [comment]
@qq1010903229 It will be part of the new UI (#919 ). Be patient.
