### ISSUE TITLE
[Bug]: Object's type Material isn't assignable from SkinnedMeshRenderer

### ISSUE THREAD

**Issue by amadare42** [AssetRipper/AssetRipper#265]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

Unity 2017.2.2

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Continuation of https://github.com/mafaca/UtinyRipper/issues/1190 issue.
Error occurred during ripping resources from For The King game.
As suggested in beforementioned issue, I put _2017_2_2f1.dll into VersionSpecificAssemblies directory, logs are attached.

### Relevant log output

``[Error] : System.Exception: Object's type Material isn't assignable from SkinnedMeshRenderer
   at AssetRipper.Core.Classes.Misc.PPtr.FindAsset[T](IPPtr`1 pptr, IAssetContainer file) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Classes\Misc\PPtr.cs:line 78
   at AssetRipper.Core.Classes.Misc.PPtr.ExportYAML[T](IPPtr`1 pptr, IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Classes\Misc\PPtr.cs:line 37
   at AssetRipper.Core.Classes.Misc.PPtr`1.ExportYAML(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Classes\Misc\PPtr.cs:line 218
   at AssetRipper.Core.Classes.ParticleSystem.Shape.ShapeModule.ExportYAML(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\ParticleSystem\Shape\ShapeModule.cs:line 278
   at AssetRipper.Core.Classes.ParticleSystem.ParticleSystem.ExportYAMLRoot(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\ParticleSystem\ParticleSystem.cs:line 305
   at AssetRipper.Core.Classes.Object.Object.ExportYAML(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Object\Object.cs:line 42
   at AssetRipper.Core.UnityObjectBase.ExportYAMLDocument(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\UnityObjectBase.cs:line 52
   at AssetRipper.Core.Project.Exporters.YamlExporterBase.Export(IExportContainer container, IEnumerable`1 assets, String path) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Exporters\YamlExporterBase.cs:line 46
   at AssetRipper.Core.Project.Collections.AssetsExportCollection.ExportInner(ProjectAssetContainer container, String filePath, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetsExportCollection.cs:line 34
   at AssetRipper.Core.Project.Collections.AssetExportCollection.Export(ProjectAssetContainer container, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetExportCollection.cs:line 58
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 157
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 68
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 88
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 151
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 132
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 55``

**Comment by ds5678** [comment]
Are certain your unity version is 2017.2.2f1? Your incomplete log suggests otherwise.

**Comment by amadare42** [comment]
Here is screenshot from executable properties (first entry is file version, second is product version):
![image](https://user-images.githubusercontent.com/3945692/153722648-408e4276-d54c-4f2c-be4e-4a2dafdbe75b.png)

Here is full log. It is really mentioned 2017.3.0f3 version
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8054220/AssetRipper.log)

**Comment by ds5678** [comment]
I just made a commit to include some additional information in the log. If you would use this new alpha build, it'll help narrow down the problem.

https://nightly.link/AssetRipper/AssetRipper/workflows/publish/master/AssetRipperGUI_win64.zip

**Comment by amadare42** [comment]
Took around and hour to finish and still same error
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8054565/AssetRipper.log)
.

**Comment by ds5678** [comment]
> VersionManager : Loading version handlers...
> VersionManager : No assemblies to load.

It says you didn't put the assembly into the folder

**Comment by amadare42** [comment]
Whoops, sorry. I just assumed that your changes in alpha version made dll not required. Anyway, I ran tool once again with _2017_2_2f1.dll in place, log looks the same. I'll try once again with _2017_3_0f3.dll as well, not sure if that will make any difference.
[_AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8054631/_AssetRipper.log)

**Comment by ds5678** [comment]
I started typing before you responded. This won't unfortunately work for you because your Unity version is `2017.2.2p2` and the version specific assemblies currently require an exact match due to their partial implementation.

I'm closing this because there's only two possibilities:
* Your game uses a custom Unity engine, and therefore it is unsupported.
* It's a simple read error, and therefore it'll get fixed by #164 automatically.
