### ISSUE TITLE
[Bug]: UnityWeb bundle ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by binlib** [AssetRipper/AssetRipper#273]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

5.3.6p8

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Issue happens when trying to load scene bundle. I've added some logging and could not figure out the issue.
Loading the file works fine with UABE

### Relevant log output

[Error] : System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at AssetRipper.Core.IO.Endian.EndianReader.ReadUInt32() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Endian\EndianReader.cs:line 69
   at AssetRipper.Core.Parser.Files.BundleFile.Parser.BundleScene.Read(EndianReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\Parser\BundleScene.cs:line 14
   at AssetRipper.Core.IO.Endian.EndianReader.ReadEndianArray[T]() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Endian\EndianReader.cs:line 500
   at AssetRipper.Core.Parser.Files.BundleFile.Header.BundleRawWebHeader..ctor(EndianReader reader, BundleVersion generation) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\Header\BundleRawWebHeader.cs:line 32
   at AssetRipper.Core.Parser.Files.BundleFile.Header.BundleHeader.Read(EndianReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\Header\BundleHeader.cs:line 47
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadHeader(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\BundleFileScheme.cs:line 72
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\BundleFileScheme.cs:line 47
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\BundleFileScheme.cs:line 40
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\SchemeReader.cs:line 54
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\SchemeReader.cs:line 19
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.AddScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructureProcessor.cs:line 29
   at AssetRipper.Core.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 125
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 60
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 40
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 32
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 116
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIImportManager.cs:line 24

**Comment by binlib** [comment]
Full log file:
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8104211/AssetRipper.log)

The bundle file
https://easyupload.io/2eqis3

**Comment by ds5678** [comment]
I was able to reproduce the error

**Comment by ds5678** [comment]
If this issue can be reproduced with files compiled from a test Unity project, I'll reconsider looking into it.
