### ISSUE TITLE
[Bug?]: Can't load content from Alpha Ace.

### ISSUE THREAD

**Issue by WauzzBR** [AssetRipper/AssetRipper#279]
**Are you on the latest version of AssetRipper?**

Yes, I'm on the latest alpha-build of AssetRipper.

**Which release are you using?**

GUI Version Windows x64

**Which Unity version did this occur on?**
Unsure (It's a really recent game so recent unity version?)

**Is the game Mono or IL2Cpp?**
IL2Cpp

**Describe the issue.**
When loading the content of a mobile game called "Alpha Ace" (stored in .ab files), AssetRipper prints out this error: System.ArgumentNullException: Value cannot be null. (Parameter 'version'), and files don't get loaded. (The game's data is encrypted, maybe that's why?)

**Relevant log output**

[Error] : System.ArgumentNullException: Value cannot be null. (Parameter 'version')
   at AssetRipper.Core.Parser.Files.UnityVersion.Parse(String version) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\UnityVersion.cs:line 93
   at AssetRipper.Core.Parser.Files.BundleFile.Header.BundleHeader.Read(EndianReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\Header\BundleHeader.cs:line 41
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadHeader(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\BundleFileScheme.cs:line 72
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\BundleFileScheme.cs:line 47
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\BundleFile\BundleFileScheme.cs:line 40
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\SchemeReader.cs:line 54
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\SchemeReader.cs:line 19
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.AddScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructureProcessor.cs:line 29
   at AssetRipper.Core.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 125
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 58
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 40
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 32
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 116
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIImportManager.cs:line 24
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8137267/AssetRipper.log)

**Comment by ds5678** [comment]
Your game uses a highly customized Unity engine and is therefore unsupported by AssetRipper.
