### ISSUE TITLE
[Bug]: vorbis_synthesis_headerin threw error code -132

### ISSUE THREAD

**Issue by zlondrej** [AssetRipper/AssetRipper#285]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.34f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Export was aborted due to the thrown exception which is thrown from `Fmod5Sharp` library (https://github.com/SamboyCoding/Fmod5Sharp/blob/96071d50dc294dadd8abdd328dfdcede3e356c0a/Fmod5Sharp/FmodVorbis/FmodVorbisRebuilder.cs#L234).

The error code corresponds to `OV_ENOTVORBIS = -132` (https://xiph.org/vorbis/doc/libvorbis/vorbis_synthesis_headerin.html).

### Relevant log output

```
ExportedFile : 'transparant_smoke' exported
ExportedFile : 'rainDrop' exported
ExportedFile : 'Water Splash' exported
Import : Resource file 'sharedassets3.assets.resS' has been loaded
ExportedFile : 'dust_splash' exported
ExportedFile : 'raindrop' exported
ExportedFile : 'smoke' exported
[Error] : System.Exception: vorbis_synthesis_headerin threw error code -132
   at Fmod5Sharp.FmodVorbis.FmodVorbisRebuilder.Checked(Int32 result, String name)
   at Fmod5Sharp.FmodVorbis.FmodVorbisRebuilder.RebuildOggFile(FmodSample sample)
   at Fmod5Sharp.FmodSample.RebuildAsStandardFileFormat(Byte[]& data, String& fileExtension)
   at AssetRipper.Library.Exporters.Audio.AudioClipDecoder.TryGetDecodedAudioClipData(Byte[] rawData, Byte[]& decodedData, String& fileExtension) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Audio\AudioClipDecoder.cs:line 70
   at AssetRipper.Library.Exporters.Audio.AudioClipDecoder.TryGetDecodedAudioClipData(IAudioClip audioClip, Byte[]& decodedData, String& fileExtension) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Audio\AudioClipDecoder.cs:line 55
   at AssetRipper.Library.Exporters.Audio.AudioClipExporter.Export(IExportContainer container, IUnityObjectBase asset, String path) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Audio\AudioClipExporter.cs:line 26
   at AssetRipper.Core.Project.Collections.AssetExportCollection.ExportInner(ProjectAssetContainer container, String filePath, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetExportCollection.cs:line 99
   at AssetRipper.Core.Project.Collections.AssetExportCollection.Export(ProjectAssetContainer container, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetExportCollection.cs:line 58
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 157
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 68
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 90
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 151
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 132
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 55
```

**Comment by ds5678** [comment]
What game is this?

**Comment by zlondrej** [comment]
Escape from Tarkov. I haven't been able to extract this game entirely using neither CMD or GUI.
