### ISSUE TITLE
[Bug]: System.OverflowException: at AssetRipper.Core.Utils.ObjectUtils.GenerateExportID

### ISSUE THREAD

**Issue by zlondrej** [AssetRipper/AssetRipper#301]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.34f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Asset ripper crashes almost immediately after extraction starts. Did not happen with previous version.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8205989/AssetRipper.log)

```
Export : Attempting to export assets to D:\EFT-full-export\EscapeFromTarkov...
Export : Starting pre-export
Export : Starting export
Export : Game files have these Unity versions: 2019.4.34f1
Export : Exporting to Unity version 2019.4.34f1
Export : Preparing for export...
Import [Warning] : Assembly 'UnityEngine.TestRunner' hasn't been found
Import : Resource file 'sharedassets2.resource' has been loaded
Import : Resource file 'resources.resource' has been loaded
[Error] : System.OverflowException: Arithmetic operation resulted in an overflow.
   at AssetRipper.Core.Utils.ObjectUtils.GenerateExportID(IUnityObjectBase asset, Func`2 duplicateChecker) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Utils\ObjectUtils.cs:line 28
   at AssetRipper.Core.Project.Collections.AssetsExportCollection.GenerateExportID(IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetsExportCollection.cs:line 54
   at AssetRipper.Core.Project.Collections.AssetsExportCollection.AddAsset(IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetsExportCollection.cs:line 59
   at AssetRipper.Core.Project.Collections.PrefabExportCollection..ctor(IAssetExporter assetExporter, IAssetContainer file, IPrefabInstance prefab) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\PrefabExportCollection.cs:line 26
   at AssetRipper.Core.Project.Collections.PrefabExportCollection..ctor(IAssetExporter assetExporter, VirtualSerializedFile virtualFile, IGameObject root) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\PrefabExportCollection.cs:line 20
   at AssetRipper.Core.Project.Collections.PrefabExportCollection..ctor(IAssetExporter assetExporter, VirtualSerializedFile virtualFile, IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\PrefabExportCollection.cs:line 18
   at AssetRipper.Core.Project.Exporters.SceneYamlExporter.CreateCollection(VirtualSerializedFile virtualFile, IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Exporters\SceneYamlExporter.cs:line 22
   at AssetRipper.Core.Project.ProjectExporter.CreateCollection(VirtualSerializedFile file, IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Project\ProjectExporter.cs:line 97
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 112
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 68
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 90
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 151
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 132
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 55
```

**Comment by ds5678** [comment]
I have an idea of what might have happened. 

Are you familiar with the `UnknownAssets` folder in the exported files? I want to know what asset types it contained when you ran this in the previous version.

**Comment by zlondrej** [comment]
Yep, I saw those before.

```
$ ls -al
total 1180
drwxr-xr-x 1 jondr 197613 0 Feb 28 21:17 ./
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:18 ../
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:23 AudioHighPassFilter/
drwxr-xr-x 1 jondr 197613 0 Feb 28 20:02 AudioLowPassFilter/
drwxr-xr-x 1 jondr 197613 0 Feb 28 20:02 AudioMixerController/
drwxr-xr-x 1 jondr 197613 0 Feb 28 20:02 AudioMixerGroupController/
drwxr-xr-x 1 jondr 197613 0 Feb 28 20:02 AudioMixerSnapshotController/
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:23 AudioReverbFilter/
drwxr-xr-x 1 jondr 197613 0 Feb 28 21:52 BillboardAsset/
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:28 BillboardRenderer/
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:28 CharacterJoint/
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:26 Cloth/
drwxr-xr-x 1 jondr 197613 0 Feb 28 20:02 ComputeShader/
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:18 DelayedCallManager/
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:18 PlayerSettings/
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:26 Projector/
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:18 RuntimeInitializeOnLoadManager/
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:18 ScriptMapper/
drwxr-xr-x 1 jondr 197613 0 Feb 28 21:52 SpeedTreeWindAsset/
drwxr-xr-x 1 jondr 197613 0 Feb 28 20:02 StreamingController/
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:18 StreamingManager/
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:28 Tree/
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:18 VFXManager/
drwxr-xr-x 1 jondr 197613 0 Feb 28 20:28 VideoClip/
drwxr-xr-x 1 jondr 197613 0 Feb 28 19:26 VideoPlayer/
```

```
$ ls -al *
AudioHighPassFilter:
total 5
drwxr-xr-x 1 jondr 197613  0 Feb 28 19:23 ./
drwxr-xr-x 1 jondr 197613  0 Feb 28 21:17 ../
-rw-r--r-- 1 jondr 197613 24 Feb 28 19:23 UnknownObject.bytes

AudioLowPassFilter:
total 5
drwxr-xr-x 1 jondr 197613  0 Feb 28 20:02 ./
drwxr-xr-x 1 jondr 197613  0 Feb 28 21:17 ../
-rw-r--r-- 1 jondr 197613 64 Feb 28 20:02 UnknownObject.bytes

AudioMixerController:
total 12
drwxr-xr-x 1 jondr 197613    0 Feb 28 20:02 ./
drwxr-xr-x 1 jondr 197613    0 Feb 28 21:17 ../
-rw-r--r-- 1 jondr 197613 4848 Feb 28 20:02 UnknownObject.bytes

AudioMixerGroupController:
total 35
drwxr-xr-x 1 jondr 197613   0 Feb 28 20:02 ./
drwxr-xr-x 1 jondr 197613   0 Feb 28 21:17 ../
-rw-r--r-- 1 jondr 197613 188 Feb 28 20:02 UnknownObject.bytes
-rw-r--r-- 1 jondr 197613  52 Feb 28 20:02 UnknownObject_0.bytes
-rw-r--r-- 1 jondr 197613  44 Feb 28 20:02 UnknownObject_1.bytes
-rw-r--r-- 1 jondr 197613  40 Feb 28 20:02 UnknownObject_10.bytes
-rw-r--r-- 1 jondr 197613  44 Feb 28 20:02 UnknownObject_11.bytes
-rw-r--r-- 1 jondr 197613 100 Feb 28 20:02 UnknownObject_12.bytes
-rw-r--r-- 1 jondr 197613  48 Feb 28 20:02 UnknownObject_13.bytes
-rw-r--r-- 1 jondr 197613  44 Feb 28 20:02 UnknownObject_14.bytes
-rw-r--r-- 1 jondr 197613  76 Feb 28 20:02 UnknownObject_15.bytes
-rw-r--r-- 1 jondr 197613  48 Feb 28 20:02 UnknownObject_16.bytes
-rw-r--r-- 1 jondr 197613  48 Feb 28 20:02 UnknownObject_17.bytes
-rw-r--r-- 1 jondr 197613  52 Feb 28 20:02 UnknownObject_18.bytes
-rw-r--r-- 1 jondr 197613  40 Feb 28 20:02 UnknownObject_19.bytes
-rw-r--r-- 1 jondr 197613  44 Feb 28 20:02 UnknownObject_2.bytes
-rw-r--r-- 1 jondr 197613  52 Feb 28 20:02 UnknownObject_20.bytes
-rw-r--r-- 1 jondr 197613  52 Feb 28 20:02 UnknownObject_21.bytes
-rw-r--r-- 1 jondr 197613  48 Feb 28 20:02 UnknownObject_22.bytes
-rw-r--r-- 1 jondr 197613  92 Feb 28 20:02 UnknownObject_23.bytes
-rw-r--r-- 1 jondr 197613  44 Feb 28 20:02 UnknownObject_24.bytes
-rw-r--r-- 1 jondr 197613  52 Feb 28 20:02 UnknownObject_25.bytes
-rw-r--r-- 1 jondr 197613  48 Feb 28 20:02 UnknownObject_3.bytes
-rw-r--r-- 1 jondr 197613  40 Feb 28 20:02 UnknownObject_4.bytes
-rw-r--r-- 1 jondr 197613  44 Feb 28 20:02 UnknownObject_5.bytes
-rw-r--r-- 1 jondr 197613  40 Feb 28 20:02 UnknownObject_6.bytes
-rw-r--r-- 1 jondr 197613  44 Feb 28 20:02 UnknownObject_7.bytes
-rw-r--r-- 1 jondr 197613  48 Feb 28 20:02 UnknownObject_8.bytes
-rw-r--r-- 1 jondr 197613  72 Feb 28 20:02 UnknownObject_9.bytes

AudioMixerSnapshotController:
total 7
drwxr-xr-x 1 jondr 197613  0 Feb 28 20:02 ./
drwxr-xr-x 1 jondr 197613  0 Feb 28 21:17 ../
-rw-r--r-- 1 jondr 197613 40 Feb 28 20:02 UnknownObject.bytes
-rw-r--r-- 1 jondr 197613 40 Feb 28 20:02 UnknownObject_0.bytes
-rw-r--r-- 1 jondr 197613 40 Feb 28 20:02 UnknownObject_1.bytes

AudioReverbFilter:
total 15
drwxr-xr-x 1 jondr 197613  0 Feb 28 19:23 ./
drwxr-xr-x 1 jondr 197613  0 Feb 28 21:17 ../
-rw-r--r-- 1 jondr 197613 76 Feb 28 19:19 UnknownObject.bytes
-rw-r--r-- 1 jondr 197613 76 Feb 28 19:19 UnknownObject_0.bytes
-rw-r--r-- 1 jondr 197613 76 Feb 28 19:19 UnknownObject_1.bytes
-rw-r--r-- 1 jondr 197613 76 Feb 28 19:19 UnknownObject_2.bytes
-rw-r--r-- 1 jondr 197613 76 Feb 28 19:19 UnknownObject_3.bytes
-rw-r--r-- 1 jondr 197613 76 Feb 28 19:19 UnknownObject_4.bytes
-rw-r--r-- 1 jondr 197613 76 Feb 28 19:23 UnknownObject_5.bytes

...
```

**Comment by ds5678** [comment]
> drwxr-xr-x 1 jondr 197613 0 Feb 28 20:02 StreamingController/

It is as I suspected. This an unintended side effect of #298. I will consider some options and do something about this for `0.1.9.6`.

**Comment by ds5678** [comment]
mafaca wrote that code, not me. I need to decide how best to handle this situation.

As a workaround, you can comment out this line:
https://github.com/AssetRipper/AssetRipper/blob/master/AssetRipperCore/Parser/Asset/AssetFactory.cs#L241

**Comment by zlondrej** [comment]
@ds5678 Saw your fix, but I just have a question: What's the point of using class prefix? Is it to just reduce ID collisions, but otherwise unnecessary? In which case, why not keep it simple go with purely random or sequential IDs then?

```
	if (classID > MaxPrefixedClassId)
	{
		do
		{
			//Checked for StreamingController on 2018.2.5f1
			//Small class id's use the below format
			//Whereas this uses random id's
			exportID = GenerateInternalID();
		}
		while (duplicateChecker(exportID));
	}
```

**Comment by ds5678** [comment]
Unity uses a class prefix, so copying them prevents bugs outside of AssetRipper.

**Comment by zlondrej** [comment]
Thanks for explaining. But if that's a case I googled the Unity class ID list (https://docs.unity3d.com/Manual/ClassIDReference.html) and the largest mentioned unused ID is `2147483647`, which is pretty much `INT_MAX`. Which leads me to conclusion, that you should really use upper half of `long int` for class ID (as opposed to only ~4 base 10 digits), and lower portion for unique identifier.

```csharp
long prefix = classID << 32; // Bitshift class ID to upper half of `long`, IDs should always be less than `Int32.MaxValue`
ulong persistentValue = 0;
do
{
	ulong value = unchecked((uint)GenerateInternalID()); // Conversion to `uint` ensures there will be no interference with `prefix`, and internal ID will take only lower half of `long` (of course you could just make `GenerateInternalID()` return `uint` directly instead)
	persistentValue = unchecked(persistentValue + value);
	exportID = prefix + (long)(persistentValue);
}
while (duplicateChecker(exportID));
```

**Comment by ds5678** [comment]
No, that would deviate from Unity behavior and possibly break stuff outside of AssetRipper

**Comment by ds5678** [comment]
Possible, but unlikely since it aligns with Unity behavior.
