### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cyberangel67** [AssetRipper/AssetRipper#332]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

I believe it is Unity 2019 something, not 100% certain

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Getting the following exception

System.Exception: Object's type Shader isn't assignable from Mesh
   at AssetRipper.Core.Classes.Misc.PPtr.FindAsset[T](IPPtr`1 pptr, IAssetContainer file) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Classes\Misc\PPtr.cs:line 78
   at AssetRipper.Core.Classes.Misc.PPtr.ExportYAML[T](IPPtr`1 pptr, IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Classes\Misc\PPtr.cs:line 37
   at AssetRipper.Core.Classes.Misc.PPtr`1.ExportYAML(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Classes\Misc\PPtr.cs:line 218
   at AssetRipper.Core.Classes.MeshCollider.MeshCollider.ExportYAMLRoot(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\MeshCollider\MeshCollider.cs:line 115
   at AssetRipper.Core.Classes.Object.Object.ExportYAML(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\Object\Object.cs:line 40
   at AssetRipper.Core.UnityObjectBase.ExportYAMLDocument(IExportContainer container) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\UnityObjectBase.cs:line 56
   at AssetRipper.Core.Project.Exporters.YamlExporterBase.Export(IExportContainer container, IEnumerable`1 assets, String path) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Exporters\YamlExporterBase.cs:line 46
   at AssetRipper.Core.Project.Collections.AssetsExportCollection.ExportInner(ProjectAssetContainer container, String filePath, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetsExportCollection.cs:line 34
   at AssetRipper.Core.Project.Collections.AssetExportCollection.Export(ProjectAssetContainer container, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetExportCollection.cs:line 58
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 157
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 68
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 90
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 151
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 132
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 55

**Comment by cyberangel67** [comment]
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8353350/AssetRipper.log)

Not sure why the log wasn't attached

**Comment by ds5678** [comment]
Either the game uses a custom unity engine, or this will be fixed by #164

**Comment by cyberangel67** [comment]
Not sure what you mean by Custom Unity Engine, the version of Unity is Unity 2019.4 downloaded from Unity's website.

**Comment by ds5678** [comment]
Did you make the game?

**Comment by cyberangel67** [comment]
No, but I know the person who did. He has been streaming it on Twitch for the last few years. And I wasn't getting this error with the version of AssetRipper 4 weeks ago.

**Comment by ds5678** [comment]
Then it's probably a side effect of #281

**Comment by cyberangel67** [comment]
Well again, I was not getting this error on a version of AssetRipper 4 weeks ago, so even if it is a side affect, you can at least see what has changed since then... Maybe :)
