### ISSUE TITLE
[Bug]: Error during reading of asset type AssetBundle

### ISSUE THREAD

**Issue by drkhodakarami** [AssetRipper/AssetRipper#371]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2017.4.x

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

trying to import a big game, during reading of the unity3d assets i get lots of this error

`Error during reading of asset type AssetBundle. V: 2017.4.18f234 P: StandaloneWin64Player N: cab-e5578f5a1b83c67ff5517dbc7ae435e1 Path: G:\Rip\7740463532170773312_1326063884.unity3d
System.Exception: End of stream. Read 12, expected 1953066613 bytes
   at AssetRipper.Core.IO.Endian.EndianReader.ReadStringBuffer(Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Endian\EndianReader.cs:line 548
   at AssetRipper.Core.IO.Asset.AssetReader.ReadString() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 29
   at AssetRipper.Core.Classes.AssetBundle.AssetBundle.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\AssetBundle\AssetBundle.cs:line 109
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFiles\SerializedFile.cs:line 360`

### Relevant log output

the file is too big and won't upload, i will copy paste important parts : 

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19044.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.1.9.9
System : AssetRipper Build Type: Release x64 Published
System : UTC Current Time: 5/5/2022 3:27:25 PM
System : UTC Compile Time: Tue Apr 12 04:15:07 UTC 2022
VersionManager : Loading version handlers...
VersionManager : Finished loading version handlers.
Plugin : Loading plugins...
Plugin : Finished loading plugins.
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level4
General : StreamingAssetsMode: Extract
General : ExportRootPath: G:\{   UNITY 3D   }\Genshin Impact Models\Asset Ripper\Ripped
General : ExportDependencies: False
General : IgnoreAssetBundleContentPaths: False
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshCoordinateSpace: Unity
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: CSharp8_0
General : ShaderExportMode: Dummy
General : SpriteExportMode: Texture2D
General : TerrainExportMode: Native
General : TextExportMode: Parse
General : Attempting to read files from G:\{   UNITY 3D   }\Genshin Impact Models\Ripped Assets\4.6 Files\Decrypted HI3 Files
Import : Asset bundle '10000371647740111328_4106352052' has been found
Import : Asset bundle '10000771190871668190_3245236776' has been found
Import : Asset bundle '1000097465707062242_85662291' has been found
Import : Asset bundle '10001382389601581317_691889169' has been found
Import : Asset bundle '10001468634260994461_2709866339' has been found
.
.
.
This goes on until the whole bundles are found (86500 files!) then

Import : Mixed game structure has been found at G:\{   UNITY 3D   }\Genshin Impact Models\Ripped Assets\4.6 Files\Decrypted HI3 Files
Import [Warning] : Dependency 'library/unity default resources' wasn't found
Import [Warning] : Dependency 'resources/unity_builtin_extra' wasn't found
Import : Files use the 'Unknown' scripting backend.
Import [Warning] : 'buildplayer-streaming_....sharedassets' is incompatible with version of the game collection
Import [Warning] : 'buildplayer-streaming_..._outside_am' is incompatible with version of the game collection

and more warnings like that one

Import [Warning] : 'buildplayer-....._erodedlandsingleraid' is incompatible with version of the game collection

and finally I start getting lots of the reported error on different unity3d bundles like this

[Error] : Error during reading of asset type AssetBundle. V: 2017.4.18f234 P: StandaloneWin64Player N: cab-0b584b0caf7346ce26f2b62a0b1f4a1c Path: G:\Rip\10000371647740111328_4106352052.unity3d
System.Exception: End of stream. Read 12, expected 1768846638 bytes
   at AssetRipper.Core.IO.Endian.EndianReader.ReadStringBuffer(Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Endian\EndianReader.cs:line 548
   at AssetRipper.Core.IO.Asset.AssetReader.ReadString() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\IO\Asset\AssetReader.cs:line 29
   at AssetRipper.Core.Classes.AssetBundle.AssetBundle.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Classes\AssetBundle\AssetBundle.cs:line 109
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFiles\SerializedFile.cs:line 360

**Comment by ds5678** [comment]
It is very likely that your game uses a custom unity engine and modified asset formats.

**Comment by drkhodakarami** [comment]
Thanks
