### ISSUE TITLE
[Bug]: Bundle File Reading Alignment Issue

### ISSUE THREAD

**Issue by NoahHahm** [AssetRipper/AssetRipper#382]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version MacOS x64

### Which Unity version did this occur on?

2021.3.2f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

[Android.zip](https://github.com/AssetRipper/AssetRipper/files/8657134/Android.zip)

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Unix 12.3.1
System : Operating System: MacOS x64
System : AssetRipper Version: 0.1.9.9
System : AssetRipper Build Type: Release x64 Published
System : UTC Current Time: 2022. 5. 10. 오전 2:54:20
System : UTC Compile Time: Tue Apr 12 04:13:35 UTC 2022
VersionManager : Loading version handlers...
VersionManager : No assemblies to load.
Plugin : Loading plugins...
Plugin : Finished loading plugins.
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: /Users/noah/Downloads/AssetRipperGUI_mac64 (1)/Ripped
General : ExportDependencies: False
General : IgnoreAssetBundleContentPaths: False
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshCoordinateSpace: Unity
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Native
General : TerrainExportMode: Native
General : TextExportMode: Parse
General : Attempting to read files from /Users/noah/Downloads/q879798239999123/assetbundles/Android
Import : Game file 'Android' has been found
Import : Mixed game structure has been found at /Users/noah/Downloads/q879798239999123/assetbundles/Android
[Error] : System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpCompress.Compressors.LZMA.LZ.OutWindow.Create(Int32 windowSize)
   at SharpCompress.Compressors.LZMA.LzmaStream..ctor(Byte[] properties, Stream inputStream, Int64 inputSize, Int64 outputSize, Stream presetDictionary, Boolean isLzma2)
   at AssetRipper.Core.Parser.Files.BundleFile.SevenZipHelper.DecompressLZMAStream(Byte[] properties, Stream compressedStream, Int64 headlessSize, Stream decompressedStream, Int64 decompressedSize) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCommon/Parser/Files/BundleFile/SevenZipHelper.cs:line 66
   at AssetRipper.Core.Parser.Files.BundleFile.SevenZipHelper.DecompressLZMAStream(Stream compressedStream, Int64 compressedSize, Stream decompressedStream, Int64 decompressedSize) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCommon/Parser/Files/BundleFile/SevenZipHelper.cs:line 27
   at AssetRipper.Core.Parser.Files.BundleFile.IO.BundleFileBlockReader.ReadEntry(Node entry) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCommon/Parser/Files/BundleFile/IO/BundleFileBlockReader.cs:line 82
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadFileStreamData(Stream stream, Int64 basePosition, Int64 headerSize) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCommon/Parser/Files/BundleFile/BundleFileScheme.cs:line 208
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCommon/Parser/Files/BundleFile/BundleFileScheme.cs:line 60
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCommon/Parser/Files/BundleFile/BundleFileScheme.cs:line 40
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCommon/Structure/SchemeReader.cs:line 54
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCommon/Structure/SchemeReader.cs:line 19
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.AddScheme(String filePath, String fileName) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCommon/Structure/GameStructure/GameStructureProcessor.cs:line 29
   at AssetRipper.Core.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameStructure.cs:line 124
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameStructure.cs:line 59
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameStructure.cs:line 39
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperCore/Structure/GameStructure/GameStructure.cs:line 31
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperLibrary/Ripper.cs:line 116
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in /home/runner/work/AssetRipper/AssetRipper/AssetRipperGUI/Managers/UIImportManager.cs:line 24

**Comment by ds5678** [comment]
Thank you for reporting. I'll check this out

**Comment by ds5678** [comment]
I checked this out, and it's a reading alignment problem. I was able to make AssetRipper read your file, but that broke reading on lots of other files. I suspect this is AssetRipper's fault caused by incomplete reverse engineering, but it's possible this file was created by a custom Unity engine. I'll keep this in mind the next time I load up Ghidra.

**Comment by NoahHahm** [comment]
thank you. We often have this problem because we are getting assets from external designers. If you have confirmed this thread, there is no problem in closing it.

**Comment by ds5678** [comment]
No, I'll keep it open as a reminder to investigate

**Comment by ds5678** [comment]
I found some more information about this:

https://unity3d.com/unity/whats-new/2021.3.2

```
Asset Bundles: Ensure that padding is added after blocks info so that Switch patching works appropriately. This fix implies that loading newly generated AssetBundles will require using this new Unity editor/runtime combination.
```

https://issuetracker.unity3d.com/issues/files-within-assetbundles-do-not-start-on-aligned-boundaries-breaking-patching-on-nintendo-switch

```
Files within Asset Bundles do not start on aligned boundaries, breaking patching on Nintendo Switch.
```

**Comment by NoahHahm** [comment]
I found a new problem. Is this a different issue?

This asset file is giving the above error.

System.Exception: Can't find end of string\n   at AssetRipper.Core.IO.Endian.EndianReader.ReadStringZeroTerm() in /AssetRipper/AssetRipper.Fundamentals/IO/Endian/EndianReader.cs:line 145

[Errors.zip](https://github.com/AssetRipper/AssetRipper/files/8738236/Errors.zip)

**Comment by ds5678** [comment]
> [Errors.zip](https://github.com/AssetRipper/AssetRipper/files/8738236/Errors.zip)

@NoahHahm Those files are encrypted.
