### ISSUE TITLE
[Error]: Log of an Error message

### ISSUE THREAD

**Issue by ChaosWizard99** [AssetRipper/AssetRipper#394]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest pre-release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2017.3.0f3

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

clicked export and show an error: see log

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19044.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.2.0.0
System : AssetRipper Build Type: Release x64 Published
System : UTC Current Time: 15/05/2022 05:15:36 p. m.
System : UTC Compile Time: Thu May 12 17:27:27 UTC 2022
Plugin : Loading plugins...
Plugin : Finished loading plugins.
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: C:\Users\Arcanist\Desktop\AssetRipperGUI_win64\Ripped
General : ExportDependencies: False
General : IgnoreAssetBundleContentPaths: False
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshCoordinateSpace: Unity
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Native
General : TerrainExportMode: Native
General : TextExportMode: Parse
General : Attempting to read files from C:\Users\Arcanist\Desktop\old\HHH\Alien Quest Eve ver.1.01\AlienQuest-EVE_Data
Import : PC data directory found. Setting root to parent directory
Import : PC game structure has been found at 'C:\Users\Arcanist\Desktop\old\HHH\Alien Quest Eve ver.1.01\AlienQuest-EVE_Data'
Import : Collecting game files...
Import : Game file 'mainData' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level2' has been found
Import : Game file 'level3' has been found
Import : Game file 'level4' has been found
Import : Collecting Streaming Assets...
Import : Files use the 'Mono' scripting backend.
Import : During Mono initialization, found 12 assemblies
Import [Error] : Unable to read , because script layout InputField mismatch binary content
General : Finished reading files
General : About to begin export to C:\Users\Arcanist\Desktop\teest\asdf\AlienQuest-EVE
General : Removing any files from a previous export...
Export : Attempting to export assets to C:\Users\Arcanist\Desktop\teest\asdf\AlienQuest-EVE...
Export : Starting pre-export
Export : Starting export
Export : Game files have these Unity versions: 4.6.7f1
Export : Exporting to Unity version 4.6.7f1
Export : Preparing for export...
Export : Can't decode audio clip 'sounds.bif_01075 - Select' with default decoder because it's 'NONE' encoded.
Export : Can't decode audio clip 'UI SCI-FI Confirm Wet (stereo)' with default decoder because it's 'NONE' encoded.
Export : Can't decode audio clip 'sounds.bif_01071 - Move' with default decoder because it's 'NONE' encoded.
Export : Can't decode audio clip 'multimedia_button_click' with default decoder because it's 'NONE' encoded.
Export : Can't decode audio clip 'sounds.bif_01072 - Tab' with default decoder because it's 'NONE' encoded.
Export : Can't decode audio clip 'sounds.bif_01079 - LVUP' with default decoder because it's 'NONE' encoded.
Export : Can't decode audio clip 'Device On 02' with default decoder because it's 'NONE' encoded.
Export : Can't decode audio clip 'UI SCI-FI Confirm Dry (stereo)' with default decoder because it's 'NONE' encoded.
Export : Can't decode audio clip 'They_Are_Here' with default decoder because it's 'NONE' encoded.
[Error] : System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at AssetRipper.Core.SourceGenExtensions.VirtualAnimationFactory.CreateAnimatorStateMachine(VirtualSerializedFile virtualFile, IAnimatorController controller, Int32 stateMachineIndex) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\SourceGenExtensions\VirtualAnimationFactory.cs:line 149
   at AssetRipper.Library.Exporters.AnimatorControllers.AnimatorControllerExportCollection..ctor(IAssetExporter assetExporter, VirtualSerializedFile virtualFile, IAnimatorController asset) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimatorControllers\AnimatorControllerExportCollection.cs:line 41
   at AssetRipper.Library.Exporters.AnimatorControllers.AnimatorControllerExportCollection..ctor(IAssetExporter assetExporter, VirtualSerializedFile virtualFile, IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimatorControllers\AnimatorControllerExportCollection.cs:line 32
   at AssetRipper.Library.Exporters.AnimatorControllers.AnimatorControllerExporter.CreateCollection(VirtualSerializedFile virtualFile, IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimatorControllers\AnimatorControllerExporter.cs:line 18
   at AssetRipper.Core.Project.ProjectExporter.CreateCollection(VirtualSerializedFile file, IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Project\ProjectExporter.cs:line 102
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 126
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 82
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 98
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 162
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 143
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 55

**Comment by ds5678** [comment]
I fixed a bunch of bugs like this since the `0.2.0.0` prerelease. Can you test using the latest alpha build of AssetRipper?

FYI your Unity version is not `2017.3.0f3`. It is `4.6.7f1`.

**Comment by ChaosWizard99** [comment]
where can i get the alpha build? I only see the 1.9.9 and 2.0.0

**Comment by ds5678** [comment]
https://assetripper.github.io/AssetRipper/articles/Downloads.html
