### ISSUE TITLE
[Bug]: Unable to open file. Show error

### ISSUE THREAD

**Issue by swapnilrane24** [AssetRipper/AssetRipper#429]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

No project was created so dint tested on Unity

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

[Error] : System.Exception: Incorrect number of bytes written. -1 instead of 131072
   at AssetRipper.Core.Parser.Files.BundleFile.IO.BundleFileBlockReader.ReadEntry(Node entry) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\IO\BundleFileBlockReader.cs:line 92
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadFileStreamData(Stream stream, Int64 basePosition, Int64 headerSize) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 207
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 59
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 39
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFile.ReadScheme(Stream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFile.cs:line 38
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFile.LoadScheme(String filePath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFile.cs:line 34
   at AssetRipper.Core.Structure.GameStructure.Platforms.PlatformGameStructure.GetUnityVersionFromBundleFile(String filePath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\Platforms\PlatformGameStructure.cs:line 331
   at AssetRipper.Core.Structure.GameStructure.Platforms.PlatformGameStructure.GetUnityVersionFromDataDirectory(String dataDirectoryPath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\Platforms\PlatformGameStructure.cs:line 349
   at AssetRipper.Core.Structure.GameStructure.Platforms.AndroidGameStructure..ctor(String rootPath, String obbPath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\Platforms\AndroidGameStructure.cs:line 40
   at AssetRipper.Core.Structure.GameStructure.Platforms.PlatformChecker.CheckAndroid(List`1 paths, AndroidGameStructure& gameStructure) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\Platforms\PlatformChecker.cs:line 121
   at AssetRipper.Core.Structure.GameStructure.Platforms.PlatformChecker.CheckPlatform(List`1 paths, PlatformGameStructure& platformStructure, MixedGameStructure& mixedStructure) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\Platforms\PlatformChecker.cs:line 19
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructure.cs:line 47
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructure.cs:line 40
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructure.cs:line 30
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 130
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIImportManager.cs:line 22

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8885090/AssetRipper.log)

**Comment by ds5678** [comment]
This usually means the asset bundle is encrypted
