### ISSUE TITLE
[Bug]: AssetRipper export error

### ISSUE THREAD

**Issue by LeoLionGan** [AssetRipper/AssetRipper#436]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Solo Leveling: Hit & Run

### Which Unity version did this occur on?

2021.1.4f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

ExportedFile : 'CharacterWeapon_2' exported
ExportedFile : 'RemoteConfig_7' exported
ExportedFile : 'Locale_16' exported
ExportedFile : 'RemoteConfig_3' exported
ExportedFile : 'ShopCostGroup_1' exported
ExportedFile : 'Locale_14' exported
ExportedFile : 'RemoteConfig_1' exported
ExportedFile : 'Locale_7' exported
ExportedFile : 'Locale_5' exported
ExportedFile : 'Locale_2' exported
ExportedFile : 'BillingMode' exported
ExportedFile : 'Locale_1' exported
ExportedFile : 'Locale_10' exported
ExportedFile : 'CharacterSkin_2' exported
ExportedFile : 'CharacterSkin_1' exported
ExportedFile : 'CharacterWeapon_5' exported
ExportedFile : 'LineBreaking Leading Characters' exported
ExportedFile : 'Locale_9' exported
ExportedFile : 'Upgrade_1' exported
ExportedFile : 'CharacterWeapon_4' exported
ExportedFile : 'Locale_13' exported
ExportedFile : 'Locale_15' exported
ExportedFile : 'LineBreaking Following Characters' exported
ExportedFile : 'RemoteConfig_13' exported
ExportedFile : 'RemoteConfig_8' exported
ExportedFile : 'CharacterColor_2' exported
ExportedFile : 'IdleSnuff' exported
ExportedFile : 'IdleBreath' exported
ExportedFile : 'OrcBoss_Buff' exported
ExportedFile : 'n2017_skill_4' exported
ExportedFile : 'Armature_Intimidate_1' exported
ExportedFile : 'Skill3' exported
ExportedFile : 'Gate_Closed_Loop 1' exported
System.ArgumentException: Binding type 39 not implemented (Parameter 'type')
   at AssetRipper.Library.Exporters.AnimationClips.CustomCurveResolver.ToAttributeName(BindingCustomType type, UInt32 attribute, String path) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimationClips\CustomCurveResolver.cs:line 529
   at AssetRipper.Library.Exporters.AnimationClips.AnimationClipConverter.AddCustomCurve(IAnimationClipBindingConstant bindings, IGenericBinding binding, String path, Single time, Single value) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimationClips\AnimationClipConverter.cs:line 226
   at AssetRipper.Library.Exporters.AnimationClips.AnimationClipConverter.ProcessConstant(IClip clip, IAnimationClipBindingConstant bindings, IReadOnlyDictionary`2 tos, Single lastFrame) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimationClips\AnimationClipConverter.cs:line 205
   at AssetRipper.Library.Exporters.AnimationClips.AnimationClipConverter.ProcessInner() in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimationClips\AnimationClipConverter.cs:line 72
   at AssetRipper.Library.Exporters.AnimationClips.AnimationClipConverter.Process(IAnimationClip clip) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimationClips\AnimationClipConverter.cs:line 51
   at AssetRipper.Library.Exporters.AnimationClips.AnimationClipExportCollection.ExportInner(IProjectAssetContainer container, String filePath, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimationClips\AnimationClipExportCollection.cs:line 22
   at AssetRipper.Core.Project.Collections.AssetExportCollection.Export(IProjectAssetContainer container, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetExportCollection.cs:line 55
   at AssetRipper.Core.Project.ProjectExporter.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporter.cs:line 257
   at AssetRipper.Core.Project.ProjectExporter.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporter.cs:line 168
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructure.cs:line 97
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 173
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 154
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 52

**Comment by LeoLionGan** [comment]
> Thank you for submitting your first issue here. Please be sure you have uploaded your `AssetRipper.log` file. It is in the same folder as the exe file. :)
AssetRipper.log  add. please check the bug

**Comment by ds5678** [comment]
@LeoLionGan I already fixed this in 560a58320156e98b2bd5abca7a6933c1dcbcadc8
