### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Radagon999** [AssetRipper/AssetRipper#481]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Mordheim City of the Damned.

### Which Unity version did this occur on?

unity 5 or earlier.

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

There is a consistent error message that has the data read is vastly under the data expected.  There are several other errors that follow but the data read vs expected is the same every time.

I apologise as well.  I am new to coding and am self teaching.

### Relevant log output

System.Exception: Read 542288 but expected 12716809 bytes while reading the raw/web bundle header.
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadHeader(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 76
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 46
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 39
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\SchemeReader.cs:line 54
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\SchemeReader.cs:line 19
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.AddScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameStructureProcessor.cs:line 28
   at AssetRipper.Core.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructure.cs:line 138
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructure.cs:line 66
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructure.cs:line 42
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructure.cs:line 32
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 130
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIImportManager.cs:line 22

**Comment by ds5678** [comment]
Please upload a full log

**Comment by Radagon999** [comment]
System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19043.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.2.1.0
System : AssetRipper Build Type: Release x64 Published
System : UTC Current Time: 30/07/2022 10:08:34
System : UTC Compile Time: Thu Jul 14 00:45:25 UTC 2022
Plugin : Loading plugins...
Plugin : Finished loading plugins.
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: C:\Users\User\Downloads\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: GroupByBundleName
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshCoordinateSpace: Unity
General : MeshExportFormat: Obj
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Native
General : TerrainExportMode: Native
General : TextExportMode: Parse
General : Attempting to read files from C:\Program Files (x86)\Steam\steamapps\common\mordheim\mordheim_Data
Import : PC data directory found. Setting root to parent directory
Import : PC game structure has been found at 'C:\Program Files (x86)\Steam\steamapps\common\mordheim\mordheim_Data'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level2' has been found
Import : Game file 'level3' has been found
Import : Game file 'level4' has been found
Import : Game file 'level5' has been found
Import : Collecting Streaming Assets...
Import : Asset bundle 'buildings_scene' has been found
Import : Asset bundle 'equipments' has been found
Import : Asset bundle 'fx' has been found
Import : Asset bundle 'grnd_dis_00_proc_00_scene' has been found
Import : Asset bundle 'grnd_dis_01_library_scene' has been found
Import : Asset bundle 'grnd_dis_01_market_scene' has been found
Import : Asset bundle 'grnd_dis_01_proc_01_scene' has been found
Import : Asset bundle 'grnd_dis_01_proc_02_scene' has been found
Import : Asset bundle 'grnd_dis_01_proc_03_scene' has been found
Import : Asset bundle 'grnd_dis_01_proc_04_scene' has been found
Import : Asset bundle 'grnd_dis_01_quayside_scene' has been found
Import : Asset bundle 'grnd_dis_01_temple_scene' has been found
Import : Asset bundle 'grnd_dis_02_ballroom_scene' has been found
Import : Asset bundle 'grnd_dis_02_barracks_scene' has been found
Import : Asset bundle 'grnd_dis_02_midbridge_scene' has been found
Import : Asset bundle 'grnd_dis_02_proc_05_scene' has been found
Import : Asset bundle 'grnd_dis_02_proc_06_scene' has been found
Import : Asset bundle 'grnd_dis_02_proc_07_scene' has been found
Import : Asset bundle 'grnd_dis_02_proc_08_scene' has been found
Import : Asset bundle 'grnd_dis_02_statue_scene' has been found
Import : Asset bundle 'loading' has been found
Import : Asset bundle 'mer_base' has been found
Import : Asset bundle 'mer_captain' has been found
Import : Asset bundle 'mer_champion' has been found
Import : Asset bundle 'mer_marksmen' has been found
Import : Asset bundle 'mer_ogre' has been found
Import : Asset bundle 'mer_priest' has been found
Import : Asset bundle 'mer_warlock' has been found
Import : Asset bundle 'mer_warrior' has been found
Import : Asset bundle 'mer_youngblood' has been found
Import : Asset bundle 'mon_plaguebearer' has been found
Import : Asset bundle 'pos_base' has been found
Import : Asset bundle 'pos_brethren' has been found
Import : Asset bundle 'pos_darksoul' has been found
Import : Asset bundle 'pos_magister' has been found
Import : Asset bundle 'pos_marauder' has been found
Import : Asset bundle 'pos_mutant' has been found
Import : Asset bundle 'pos_possessed' has been found
Import : Asset bundle 'pos_priest' has been found
Import : Asset bundle 'pos_spawn' has been found
Import : Asset bundle 'props' has been found
Import : Asset bundle 'props_scene' has been found
Import : Asset bundle 'scene_prefabs' has been found
Import : Asset bundle 'sis_augur' has been found
Import : Asset bundle 'sis_base' has been found
Import : Asset bundle 'sis_maiden' has been found
Import : Asset bundle 'sis_matriarch' has been found
Import : Asset bundle 'sis_novice' has been found
Import : Asset bundle 'sis_sister' has been found
Import : Asset bundle 'sis_smuggler' has been found
Import : Asset bundle 'sis_superior' has been found
Import : Asset bundle 'sis_zealot' has been found
Import : Asset bundle 'ska_assassin' has been found
Import : Asset bundle 'ska_base' has been found
Import : Asset bundle 'ska_black' has been found
Import : Asset bundle 'ska_globadier' has been found
Import : Asset bundle 'ska_night' has been found
Import : Asset bundle 'ska_ogre' has been found
Import : Asset bundle 'ska_sorcerer' has been found
Import : Asset bundle 'ska_verminkin' has been found
Import : Asset bundle 'ska_warpguard' has been found
Import : Asset bundle 'sounds' has been found
Import : Asset bundle 'standalonewindows64' has been found
Import : Asset bundle 'und_dreg' has been found
Import : Asset bundle 'und_ghoul' has been found
Import : Asset bundle 'und_horror' has been found
Import : Asset bundle 'und_necromancer' has been found
Import : Asset bundle 'und_thrall' has been found
Import : Asset bundle 'und_vampire' has been found
Import : Asset bundle 'und_zombie' has been found
Import : Asset bundle 'wit_base' has been found
Import : Asset bundle 'wit_captain' has been found
Import : Asset bundle 'wit_executioner' has been found
Import : Asset bundle 'wit_flagellant' has been found
Import : Asset bundle 'wit_hunter' has been found
Import : Asset bundle 'wit_knight' has been found
Import : Asset bundle 'wit_priest' has been found
Import : Asset bundle 'wit_zealot' has been found
System.Exception: Read 542288 but expected 12716809 bytes while reading the raw/web bundle header.
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadHeader(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 76
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 46
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 39
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\SchemeReader.cs:line 54
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\SchemeReader.cs:line 19
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.AddScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameStructureProcessor.cs:line 28
   at AssetRipper.Core.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructure.cs:line 138
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructure.cs:line 61
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructure.cs:line 42
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructure.cs:line 32
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 130
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIImportManager.cs:line 22
