### ISSUE TITLE
[Bug]: AssetRIpper

### ISSUE THREAD

**Issue by anarak-duran** [AssetRipper/AssetRipper#489]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

https://drive.google.com/u/0/uc?id=1eDhw_dPzXmi_afnSz7loM2fYkOsAV3P7&export=download

This game is from Hoyovers, It just came out recently. This is a closed beta test.

### Which Unity version did this occur on?

2019.4.32f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I wanted to deliver all files (textures, models, etc.) from the asset ripper

### Relevant log output

...
Import : Asset bundle 'fffc5300f8ca6be0d5d91e6b6413f698' has been found
Import : Asset bundle 'mihoyo_sdk_res' has been found
Import : Asset bundle 'pc' has been found
Import : Mixed game structure has been found at D:\Проект для выебки\ZenlessZoneZero

System.NotImplementedException: Bundle compression '5' isn't supported
   at AssetRipper.Core.Parser.Files.BundleFile.IO.BundleFileBlockReader.ReadEntry(Node entry) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\IO\BundleFileBlockReader.cs:line 98
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadFileStreamData(Stream stream, Int64 basePosition, Int64 headerSize) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 211
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 59
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 39
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\SchemeReader.cs:line 54
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\SchemeReader.cs:line 19
   at AssetRipper.Core.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 136
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 66
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 42
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 32
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Ripper.cs:line 130
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipper.GUI\Managers\UIImportManager.cs:line 22

**Comment by anarak-duran** [comment]
and where do I need to upload this AssetRipper.log file?

**Comment by ds5678** [comment]
The game uses custom compression.

**Comment by anarak-duran** [comment]
And what does this mean, or what should I do?

**Comment by ds5678** [comment]
It means that the files are in a custom format.
