### ISSUE TITLE
[Bug]: Risk of Rain 2 failure to open: "

### ISSUE THREAD

**Issue by uGuardian** [AssetRipper/AssetRipper#494]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Risk of Rain 2

### Which Unity version did this occur on?

2019.4.26

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Attempted to both Open File on the executable and Open Folder on the entire game folder. Error occurs.

### Relevant log output

```
[Error] : SerializedFileException: v:2019.4.26f1 p:StandaloneWin64Player t:MonoBehaviour n:cab-3dd97fed283380efbb62b0ec9f6c0473
Path:F:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\StreamingAssets\aa\StandaloneWindows64\ror2-base-ui_text_assets_all.bundle
Message: Read 284 but expected 392 for asset type MonoBehaviour
StackTrace:    at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 384
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, ObjectInfo info) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 328
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadData(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 260
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 56
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadFile(SerializedFile file) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameProcessorContext.ReadSerializedFiles() in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameProcessorContext.cs:line 32
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.ProcessSchemes(GameCollection fileCollection) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\GameStructureProcessor.cs:line 91
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 87
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 42
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 32
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 130
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIImportManager.cs:line 22
```
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9305132/AssetRipper.log)

**Comment by ds5678** [comment]
You're using an outdated version of AssetRipper

**Comment by uGuardian** [comment]
…My bad, normally it asks me to update automatically so I failed to realize, I'll fix that.
