### ISSUE TITLE
[Bug]:  assetripper crashes on export

### ISSUE THREAD

**Issue by hanicraft** [AssetRipper/AssetRipper#531]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

karlson

### Which Unity version did this occur on?

2019

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

i loaded files but on export it crashed

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.18363.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.2.3.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: 09/01/2022 15:23:27
System : UTC Compile Time: Tue Aug 23 06:05:44 UTC 2022
Plugin : Loading plugins...
Plugin : Finished loading plugins.
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: F:\tools\AssetRipper_win_x64\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: GroupByBundleName
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : Attempting to read files from D:\games\Karlson\Karlson_Data
Import : PC data directory found. Setting root to parent directory
Import : PC game structure has been found at 'D:\games\Karlson\Karlson_Data'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level10' has been found
Import : Game file 'level11' has been found
Import : Game file 'level12' has been found
Import : Game file 'level2' has been found
Import : Game file 'level3' has been found
Import : Game file 'level4' has been found
Import : Game file 'level5' has been found
Import : Game file 'level6' has been found
Import : Game file 'level7' has been found
Import : Game file 'level8' has been found
Import : Game file 'level9' has been found
Import : Collecting Streaming Assets...
Import : Files use the 'Mono' scripting backend.
Import : During Mono initialization, found 93 assemblies
Import [Warning] : Assembly 'Unity.ProBuilder.Editor' hasn't been found
Import [Warning] : Unable to read Default Material Palette, because valid definition for script MaterialPalette wasn't found
General : Finished reading files
General [Error] : Unhandled app-level fatal exception!
System.Runtime.InteropServices.COMException (0x80004005): The parameter is incorrect.
 ---> System.Runtime.InteropServices.COMException (0x80070057): GetDisplayName failed
   at Avalonia.Win32.Win32Com.Impl.__MicroComIShellItemProxy.GetDisplayName(UInt32 sigdnName) in /_/src/Windows/Avalonia.Win32/Win32Com/Win32.Generated.cs:line 151
   at Avalonia.Win32.SystemDialogImpl.GetAbsoluteFilePath(IShellItem shellItem) in /_/src/Windows/Avalonia.Win32/SystemDialogImpl.cs:line 188
   at Avalonia.Win32.SystemDialogImpl.<>c__DisplayClass3_0.<ShowFolderDialogAsync>b__0() in /_/src/Windows/Avalonia.Win32/SystemDialogImpl.cs:line 173
   at Avalonia.Win32.SystemDialogImpl.<>c__DisplayClass3_0.<ShowFolderDialogAsync>b__0() in /_/src/Windows/Avalonia.Win32/SystemDialogImpl.cs:line 181
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at AssetRipper.GUI.MainWindowViewModel.ExportAll() in D:\a\AssetRipper\AssetRipper\AssetRipper.GUI\MainWindow.ViewModel.cs:line 239
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, CancellationToken token) in /_/src/Avalonia.Controls/DesktopApplicationExtensions.cs:line 57
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, Window mainWindow) in /_/src/Avalonia.Controls/DesktopApplicationExtensions.cs:line 46
   at AssetRipper.GUI.App.AppMain(Application app, String[] args) in D:\a\AssetRipper\AssetRipper\AssetRipper.GUI\App.axaml.cs:line 40
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 158
   at AssetRipper.GUI.Program.RunAvalonia() in D:\a\AssetRipper\AssetRipper\AssetRipper.GUI\Program.cs:line 33
   at AssetRipper.GUI.Program.Main(String[] args) in D:\a\AssetRipper\AssetRipper\AssetRipper.GUI\Program.cs:line 18

**Comment by ds5678** [comment]
I wasn't able to reproduce this.

**Comment by ds5678** [comment]
Closed because of inactivity
