### ISSUE TITLE
[Bug]: Crash on some bundles (while other are working)

### ISSUE THREAD

**Issue by amadare42** [AssetRipper/AssetRipper#532]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Console Version Windows x64

### Which game did this occur on?

https://steamdb.info/app/1096530/

### Which Unity version did this occur on?

2019.4.37

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Some asset bundles are not being extracted properly, with following error occurring:
```
System.Exception: Incorrect number of bytes written. -1 instead of 131072
   at AssetRipper.Core.Parser.Files.BundleFile.IO.BundleFileBlockReader.ReadEntry(Node entry) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\IO\BundleFileBlockReader.cs:line 92
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadFileStreamData(Stream stream, Int64 basePosition, Int64 headerSize) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 211
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 59
   at AssetRipper.Core.Parser.Files.BundleFile.BundleFileScheme.ReadScheme(Stream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\BundleFile\BundleFileScheme.cs:line 39
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\SchemeReader.cs:line 54
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\SchemeReader.cs:line 19
   at AssetRipper.Core.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 136
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 61
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 42
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 32
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Ripper.cs:line 139
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipper.GUI\Managers\UIImportManager.cs:line 22
```

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9474085/AssetRipper.log)

**Comment by Steve-Stage** [comment]
I have the same issue. Unity 2018.4.30f1.
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10415810/AssetRipper.log)
