### ISSUE TITLE
[Bug]: The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by abouzia** [AssetRipper/AssetRipper#586]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

https://apkcombo.com/number-io/com.xgame.number.io.stickman.tower/

### Which Unity version did this occur on?

2020.3.41

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

What happened? 
- I got this error when I tried to export all assets

Should something else have happened instead?
- Exportation stopped

Please provide steps to reproduce the issue if possible.
1. Open the data folder of the game (com.xgame.number.io.stickman.tower) in assetripper
2. Export all files
3. The error will appear in the middle of the process

### Relevant log output

[Error] : System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\Bouzzy\Downloads\Number.io_2.0.2_apkcombo.com\assets\assetripper\data\data\ExportedProject\Assets\Resources\Skeleton Prefab Mesh "root (14)".asset'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Create(String path)
   at AssetRipper.Core.Project.Exporters.YamlExporterBase.Export(IExportContainer container, IUnityObjectBase asset, String path) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\Exporters\YamlExporterBase.cs:line 22
   at AssetRipper.Core.Project.Collections.AssetExportCollection.ExportInner(IProjectAssetContainer container, String filePath, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\Collections\AssetExportCollection.cs:line 87
   at AssetRipper.Library.Exporters.YamlStreamedAssetExportCollection.ExportMesh(IProjectAssetContainer container, String filePath, String dirPath, IMesh mesh) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Exporters\YamlStreamedAssetExportCollection.cs:line 57
   at AssetRipper.Library.Exporters.YamlStreamedAssetExportCollection.ExportInner(IProjectAssetContainer container, String filePath, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Exporters\YamlStreamedAssetExportCollection.cs:line 30
   at AssetRipper.Core.Project.Collections.AssetExportCollection.Export(IProjectAssetContainer container, String projectDirectory) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\Collections\AssetExportCollection.cs:line 23
   at AssetRipper.Core.Project.ProjectExporter.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\ProjectExporter.cs:line 251
   at AssetRipper.Core.Project.ProjectExporter.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\ProjectExporter.cs:line 172
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 97
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Ripper.cs:line 181
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Ripper.cs:line 163
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipper.GUI\Managers\UIExportManager.cs:line 52

**Comment by ds5678** [comment]
Already fixed on the latest commit

**Comment by ds5678** [comment]
Commits are not releases

**Comment by DizzyDJW** [comment]
> Commits are not releases

I'm confused how this was helpful. I'm having the exact same issue. Most ppl who use GitHub simply download "releases". How is this being fixed in a commit helpful if it isn't in the release that 90% of people are downloading?

What good is a commit to the people using AssetRipper?

**Comment by ds5678** [comment]
Any new release is made from all the commits that happened since the previous release.

**Comment by DizzyDJW** [comment]
So when will a new release happen with the latest commit that fixed the problem? Or are there instructions somewhere on how to create a release from the latest commit?
