### ISSUE TITLE
[Enhancement]: Read assets with type trees

### ISSUE THREAD

**Issue by Vaxuto** [AssetRipper/AssetRipper#595]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

https://play.google.com/store/apps/details?id=com.dvloper.granny

### Which Unity version did this occur on?

2021.3.11f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

It fails to read shaders from unity default resources upon importing in the latest alpha-build.

This is the error it gives me: 

[Error] : Error during reading of asset type Shader. V: 2021.3.9f1 P: Android N: unity default resources Path: 
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadSByte()
   at AssetRipper.SourceGenerated.Subclasses.MatrixParameter.MatrixParameter.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList`1 value, AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.ConstantBuffer.ConstantBuffer_2021_1_1_f1.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList`1 value, AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.SerializedProgramParameters.SerializedProgramParameters_2021_1_1_f1.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.SerializedProgram.SerializedProgram_2021_2_0_a16.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.SerializedPass.SerializedPass_2021_2_0_a17.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList`1 value, AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.SerializedSubShader.SerializedSubShader_2021_2_0_a17.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList`1 value, AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.SerializedShader.SerializedShader_2021_2_0_a21.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_48.Shader_2021_2_0_a21.ReadRelease(AssetReader reader)
   at AssetRipper.Assets.UnityAssetBase.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Assets\UnityAssetBase.cs:line 27
   at AssetRipper.Core.Structure.GameAssetFactory.ReadNormalObject(IUnityObjectBase asset, AssetReader reader, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameAssetFactory.cs:line 122

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9912664/AssetRipper.log)

**Comment by ds5678** [comment]
## Design concept

```cs
using AssetRipper.Assets.Generics;
using AssetRipper.IO.Files.SerializedFiles.Parser.TypeTrees;
using System.Runtime.CompilerServices;

namespace AssetRipper.Assets.IO.Reading.Fields;

public interface IFieldReader<T> where T : class
{
	void Read(AssetReader reader, TypeTreeNodeStruct fieldNode, T field);
}
public interface IPrimitiveReader<T>
{
	T Read(AssetReader reader, TypeTreeNodeStruct fieldNode);
}
public static class DefaultFieldReader
{
	public static void Read(AssetReader reader, TypeTreeNodeStruct fieldNode)
	{
		//parse fieldNode and use reader
	}
}
public sealed class PrimitiveStructReader<T> : IPrimitiveReader<T> where T : unmanaged
{
	public T Read(AssetReader reader, TypeTreeNodeStruct fieldNode)
	{
		if (typeof(T) == typeof(bool))
		{
			if (fieldNode.IsVector)//IsBoolean
			{
				bool result = reader.ReadBoolean();
				if (fieldNode.AlignBytes)
				{
					reader.AlignStream();
				}
				return Unsafe.As<bool, T>(ref result);
			}
			else
			{
				DefaultFieldReader.Read(reader, fieldNode);
			}
		}
		//etc
		else
		{
			DefaultFieldReader.Read(reader, fieldNode);
		}
		return default;
	}
}
public sealed class PrimitiveArrayReader<T> : IPrimitiveReader<T[]> where T : unmanaged
{
	public T[] Read(AssetReader reader, TypeTreeNodeStruct fieldNode)
	{
		if (typeof(T) == typeof(bool))
		{
			if (fieldNode.IsVector)//IsBoolean
			{
				bool[] result = reader.ReadBooleanArray(false);
				if (fieldNode.AlignBytes)
				{
					reader.AlignStream();
				}
				return Unsafe.As<T[]>(result);
			}
			else
			{
				DefaultFieldReader.Read(reader, fieldNode);
			}
		}
		else
		{
			DefaultFieldReader.Read(reader, fieldNode);
		}
		//etc
		return Array.Empty<T>();
	}
}
public sealed class AssetFieldReader<T> : IFieldReader<T> where T : class, IUnityAssetBase
{
	public void Read(AssetReader reader, TypeTreeNodeStruct fieldNode, T field)
	{
		//field.ReadFromTypeTree(reader, fieldNode);
	}
}
public sealed class ListReader<T> : IFieldReader<AssetList<T>> where T : class, new()
{
	public ListReader(IFieldReader<T> elementReader)
	{
		ElementReader = elementReader;
	}

	public IFieldReader<T> ElementReader { get; }
	public void Read(AssetReader reader, TypeTreeNodeStruct fieldNode, AssetList<T> field)
	{
		if (fieldNode.IsVector)
		{
			TypeTreeNodeStruct arrayNode = fieldNode.SubNodes[0];
			TypeTreeNodeStruct elementNode = arrayNode.SubNodes[1];
			bool align = fieldNode.AlignBytes || arrayNode.AlignBytes;
			ReadList(reader, elementNode, align, field);
		}
		else if (fieldNode.IsArray)
		{
			TypeTreeNodeStruct elementNode = fieldNode.SubNodes[1];
			ReadList(reader, elementNode, fieldNode.AlignBytes, field);
		}
		else
		{
			field.Clear();
			DefaultFieldReader.Read(reader, fieldNode);
		}
	}

	private void ReadList(AssetReader reader, TypeTreeNodeStruct elementNode, bool align, AssetList<T> field)
	{
		field.Clear();
		int size = reader.ReadInt32();
		for (int i = 0; i < size; i++)
		{
			T element = field.AddNew();
			ElementReader.Read(reader, elementNode, element);
		}
		if (align)
		{
			reader.AlignStream();
		}
	}
}
public abstract class PairReaderBase<TKey, TValue> : IFieldReader<AccessPairBase<TKey, TValue>>
	where TKey : notnull where TValue : notnull
{
	public abstract void Read(AssetReader reader, TypeTreeNodeStruct fieldNode, AccessPairBase<TKey, TValue> field);
}
public sealed class PairReader_Field_Field<TKey, TValue> : PairReaderBase<TKey, TValue>
	where TKey : class where TValue : class
{
	public PairReader_Field_Field(IFieldReader<TKey> keyReader, IFieldReader<TValue> valueReader)
	{
		KeyReader = keyReader;
		ValueReader = valueReader;
	}

	public IFieldReader<TKey> KeyReader { get; }
	public IFieldReader<TValue> ValueReader { get; }

	public override void Read(AssetReader reader, TypeTreeNodeStruct fieldNode, AccessPairBase<TKey, TValue> field)
	{
		if (fieldNode.IsVector)//IsPair
		{
			TypeTreeNodeStruct keyNode = fieldNode.SubNodes[0];
			KeyReader.Read(reader, keyNode, field.Key);
			TypeTreeNodeStruct valueNode = fieldNode.SubNodes[1];
			ValueReader.Read(reader, valueNode, field.Value);
			if (fieldNode.AlignBytes)
			{
				reader.AlignStream();
			}
		}
		else
		{
			DefaultFieldReader.Read(reader, fieldNode);
		}
	}
}
public sealed class PairReader_Primitive_Field<TKey, TValue> : PairReaderBase<TKey, TValue>
	where TKey : notnull where TValue : class
{
	public PairReader_Primitive_Field(IPrimitiveReader<TKey> keyReader, IFieldReader<TValue> valueReader)
	{
		KeyReader = keyReader;
		ValueReader = valueReader;
	}

	public IPrimitiveReader<TKey> KeyReader { get; }
	public IFieldReader<TValue> ValueReader { get; }

	public override void Read(AssetReader reader, TypeTreeNodeStruct fieldNode, AccessPairBase<TKey, TValue> field)
	{
		if (fieldNode.IsVector)//IsPair
		{
			TypeTreeNodeStruct keyNode = fieldNode.SubNodes[0];
			field.Key = KeyReader.Read(reader, keyNode);
			TypeTreeNodeStruct valueNode = fieldNode.SubNodes[1];
			ValueReader.Read(reader, valueNode, field.Value);
			if (fieldNode.AlignBytes)
			{
				reader.AlignStream();
			}
		}
		else
		{
			DefaultFieldReader.Read(reader, fieldNode);
		}
	}
}
public sealed class PairReader_Field_Primitive<TKey, TValue> : PairReaderBase<TKey, TValue>
	where TKey : class where TValue : class
{
	public PairReader_Field_Primitive(IFieldReader<TKey> keyReader, IPrimitiveReader<TValue> valueReader)
	{
		KeyReader = keyReader;
		ValueReader = valueReader;
	}

	public IFieldReader<TKey> KeyReader { get; }
	public IPrimitiveReader<TValue> ValueReader { get; }

	public override void Read(AssetReader reader, TypeTreeNodeStruct fieldNode, AccessPairBase<TKey, TValue> field)
	{
		if (fieldNode.IsVector)//IsPair
		{
			TypeTreeNodeStruct keyNode = fieldNode.SubNodes[0];
			KeyReader.Read(reader, keyNode, field.Key);
			TypeTreeNodeStruct valueNode = fieldNode.SubNodes[1];
			field.Value = ValueReader.Read(reader, valueNode);
			if (fieldNode.AlignBytes)
			{
				reader.AlignStream();
			}
		}
		else
		{
			DefaultFieldReader.Read(reader, fieldNode);
		}
	}
}
public sealed class DictionaryReader<TKey, TValue> : IFieldReader<AssetDictionary<TKey, TValue>>
	where TKey : notnull, new() where TValue : notnull, new()
{
	public DictionaryReader(PairReaderBase<TKey, TValue> pairReader)
	{
		PairReader = pairReader;
	}

	public PairReaderBase<TKey, TValue> PairReader { get; }
	public void Read(AssetReader reader, TypeTreeNodeStruct fieldNode, AssetDictionary<TKey, TValue> field)
	{
		field.Clear();
		if (fieldNode.IsVector)//IsMap
		{
			TypeTreeNodeStruct arrayNode = fieldNode.SubNodes[0];
			TypeTreeNodeStruct pairNode = arrayNode.SubNodes[1];
			int size = reader.ReadInt32();
			for (int i = 0; i < size; i++)
			{
				//PairReader.Read(reader, pairNode, field.AddNew());
			}
			if (fieldNode.AlignBytes || arrayNode.AlignBytes)
			{
				reader.AlignStream();
			}
		}
		else
		{
			DefaultFieldReader.Read(reader, fieldNode);
		}
	}
}
```

**Comment by ds5678** [comment]
Another design concept:
```cs
partial interface IUnityAssetBase
{
    IReadOnlyList<PropertyMetadata> Properties { get; }
}
public readonly struct PropertyMetadata
{
    public string? ReleaseName { get; }
    public string? EditorName { get; }
    public string StandardName { get; }
    public PropertyReader Reader { get; }
}
```

**Comment by ds5678** [comment]
With the implementation of 90cd0b1345d7224ca0c3f294bff487e9c077645f, this is no longer aligned with development goals.
