### ISSUE TITLE
[Bug]: AudioMixer export issue

### ISSUE THREAD

**Issue by BasicallyJustBently** [AssetRipper/AssetRipper#596]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Console Version Windows x64

### Which game did this occur on?

Rec Room
https://steamdb.info/depot/471711/manifests/

### Which Unity version did this occur on?

I'm fairly sure it's 5.4.0b17

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I'm still not totally sure but from the log it looks like it has trouble reading a Font asset type from resources.assets and sharedassets0.assets also trips it up with AudioMixerController and another Font. All I did was run the program, load the folder, then try exporting everything.

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19045.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.2.4.2
System : AssetRipper Build Type: Release Published
System : UTC Current Time: 11/04/2022 17:14:05
System : UTC Compile Time: Wed Oct  5 03:22:30 UTC 2022
Plugin : Loading plugins...
Plugin : Finished loading plugins.
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: D:\Programs\Organized\FileRelatedSoftware\Extracting\AssetRipper_win_x64\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : Attempting to read files from D:\RecRoom
Import : PC game structure has been found at 'D:\RecRoom'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level10' has been found
Import : Game file 'level11' has been found
Import : Game file 'level12' has been found
Import : Game file 'level13' has been found
Import : Game file 'level14' has been found
Import : Game file 'level15' has been found
Import : Game file 'level2' has been found
Import : Game file 'level3' has been found
Import : Game file 'level4' has been found
Import : Game file 'level5' has been found
Import : Game file 'level6' has been found
Import : Game file 'level7' has been found
Import : Game file 'level8' has been found
Import : Game file 'level9' has been found
Import : Collecting Streaming Assets...
Import : Files use the 'Mono' scripting backend.
Import : During Mono initialization, found 14 assemblies
[Error] : Error during reading of asset type Font. V: 5.4.0b17 P: StandaloneWin64Player N: unity default resources Path: D:\RecRoom\Recroom_Release_Data\Resources\unity default resources
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Byte(AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.Utf8String.Utf8String.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_Array_Asset[T](AssetList`1 value, AssetReader reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_128.Font_5_4_0_b22.ReadRelease(AssetReader reader)
   at AssetRipper.Core.UnityAssetBase.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\UnityAssetBase.cs:line 27
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 288

[Error] : Error during reading of asset type Font. V: 5.4.0b17 P: StandaloneWin64Player N: sharedassets0.assets Path: D:\RecRoom\Recroom_Release_Data\sharedassets0.assets
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Byte(AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.Utf8String.Utf8String.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_Array_Asset[T](AssetList`1 value, AssetReader reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_128.Font_5_4_0_b22.ReadRelease(AssetReader reader)
   at AssetRipper.Core.UnityAssetBase.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\UnityAssetBase.cs:line 27
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 288

[Error] : Error during reading of asset type Font. V: 5.4.0b17 P: StandaloneWin64Player N: sharedassets0.assets Path: D:\RecRoom\Recroom_Release_Data\sharedassets0.assets
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Byte(AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.Utf8String.Utf8String.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_Array_Asset[T](AssetList`1 value, AssetReader reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_128.Font_5_4_0_b22.ReadRelease(AssetReader reader)
   at AssetRipper.Core.UnityAssetBase.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\UnityAssetBase.cs:line 27
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 288

[Error] : Error during reading of asset type AudioMixerController. V: 5.4.0b17 P: StandaloneWin64Player N: sharedassets0.assets Path: D:\RecRoom\Recroom_Release_Data\sharedassets0.assets
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at AssetRipper.IO.Endian.EndianReader.ReadUInt32() in D:\a\AssetRipper\AssetRipper\AssetRipper.IO.Endian\EndianReader.cs:line 89
   at AssetRipper.SourceGenerated.Subclasses.GUID.GUID.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_Array_Asset[T](AssetList`1 value, AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.AudioMixerConstant.AudioMixerConstant_5_0_0_f4.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_AssetAlign[T](T value, AssetReader reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_241.AudioMixerController_5_3_6_f1.ReadRelease(AssetReader reader)
   at AssetRipper.Core.UnityAssetBase.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\UnityAssetBase.cs:line 27
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 288

[Error] : Error during reading of asset type Font. V: 5.4.0b17 P: StandaloneWin64Player N: resources.assets Path: D:\RecRoom\Recroom_Release_Data\resources.assets
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Byte(AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.Utf8String.Utf8String.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_Array_Asset[T](AssetList`1 value, AssetReader reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_128.Font_5_4_0_b22.ReadRelease(AssetReader reader)
   at AssetRipper.Core.UnityAssetBase.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\UnityAssetBase.cs:line 27
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 288

[Error] : Error during reading of asset type Font. V: 5.4.0b17 P: StandaloneWin64Player N: resources.assets Path: D:\RecRoom\Recroom_Release_Data\resources.assets
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Byte(AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.Utf8String.Utf8String.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_Array_Asset[T](AssetList`1 value, AssetReader reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_128.Font_5_4_0_b22.ReadRelease(AssetReader reader)
   at AssetRipper.Core.UnityAssetBase.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\UnityAssetBase.cs:line 27
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 288

[Error] : Error during reading of asset type Font. V: 5.4.0b17 P: StandaloneWin64Player N: resources.assets Path: D:\RecRoom\Recroom_Release_Data\resources.assets
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Byte(AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.Utf8String.Utf8String.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_Array_Asset[T](AssetList`1 value, AssetReader reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_128.Font_5_4_0_b22.ReadRelease(AssetReader reader)
   at AssetRipper.Core.UnityAssetBase.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\UnityAssetBase.cs:line 27
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 288

[Error] : Error during reading of asset type Font. V: 5.4.0b17 P: StandaloneWin64Player N: resources.assets Path: D:\RecRoom\Recroom_Release_Data\resources.assets
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Byte(AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.Utf8String.Utf8String.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_Array_Asset[T](AssetList`1 value, AssetReader reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_128.Font_5_4_0_b22.ReadRelease(AssetReader reader)
   at AssetRipper.Core.UnityAssetBase.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\UnityAssetBase.cs:line 27
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 288

[Error] : Error during reading of asset type Font. V: 5.4.0b17 P: StandaloneWin64Player N: sharedassets3.assets Path: D:\RecRoom\Recroom_Release_Data\sharedassets3.assets
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Byte(AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.Utf8String.Utf8String.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_Array_Asset[T](AssetList`1 value, AssetReader reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_128.Font_5_4_0_b22.ReadRelease(AssetReader reader)
   at AssetRipper.Core.UnityAssetBase.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\UnityAssetBase.cs:line 27
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 288

[Error] : Error during reading of asset type PlayerSettings. V: 5.4.0b17 P: StandaloneWin64Player N: globalgamemanagers Path: D:\RecRoom\Recroom_Release_Data\globalgamemanagers
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Byte(AssetReader reader)
   at AssetRipper.SourceGenerated.Subclasses.Utf8String.Utf8String.ReadRelease(AssetReader reader)
   at AssetRipper.SourceGenerated.Classes.ClassID_129.PlayerSettings_5_4_0_b22.ReadRelease(AssetReader reader)
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 333

[Error] : Read 232 but expected 236 for asset type GraphicsSettings. V: 5.4.0b17 P: StandaloneWin64Player N: globalgamemanagers Path: D:\RecRoom\Recroom_Release_Data\globalgamemanagers
General : Finished reading files
General : About to begin export to D:\RecRoom\test\Recroom_Release
General : Removing any files from a previous export...
Export : Attempting to export assets to D:\RecRoom\test\Recroom_Release...
Export : Starting pre-export
Export : Starting export
Export : Game files have these Unity versions: 5.4.0b17
Export : Exporting to Unity version 5.4.0b17
Export : Preparing for export...
Import : Resource file 'level7.resS' has been loaded
Import [Warning] : Assembly 'UnityEngine.Advertisements' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Purchasing' hasn't been found
Import : Resource file 'resources.assets.resS' has been loaded
Import : Resource file 'resources.resource' has been loaded
Import : Resource file 'sharedassets0.assets.resS' has been loaded
Import : Resource file 'sharedassets0.resource' has been loaded
[Error] : System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at AssetRipper.Library.Exporters.AudioMixers.AudioMixerExportCollection.ProcessAudioMixerEffects(AssetsProcessingContext& context) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Exporters\AudioMixers\AudioMixerExportCollection.cs:line 97
   at AssetRipper.Library.Exporters.AudioMixers.AudioMixerExportCollection.ProcessAssets(AssetsProcessingContext& context) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Exporters\AudioMixers\AudioMixerExportCollection.cs:line 51
   at AssetRipper.Library.Exporters.AudioMixers.AudioMixerExportCollection..ctor(IAssetExporter assetExporter, VirtualSerializedFile virtualFile, IAudioMixerController mixer) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Exporters\AudioMixers\AudioMixerExportCollection.cs:line 37
   at AssetRipper.Library.Exporters.AudioMixers.AudioMixerExporter.CreateCollection(VirtualSerializedFile virtualFile, IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Exporters\AudioMixers\AudioMixerExporter.cs:line 36
   at AssetRipper.Core.Project.ProjectExporter.CreateCollection(VirtualSerializedFile file, IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\ProjectExporter.cs:line 128
   at AssetRipper.Core.Project.ProjectExporter.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\ProjectExporter.cs:line 207
   at AssetRipper.Core.Project.ProjectExporter.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\ProjectExporter.cs:line 172
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 97
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Ripper.cs:line 181
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Ripper.cs:line 163
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipper.GUI\Managers\UIExportManager.cs:line 52

**Comment by ds5678** [comment]
This should not happen on the latest commit.
