### ISSUE TITLE
[Bug]: Can't decompile without errors and broken scripts

### ISSUE THREAD

**Issue by Grass30** [AssetRipper/AssetRipper#618]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Gorilla tag

### Which Unity version did this occur on?

2021.3.11f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Whenever it reaches to about 85 percent it says there's an error then when I load it in it has 2 broken scripts that I don't know how to fix. Btw if you need to know its a APK file.

### Relevant log output

-- Before compiling
Import [Warning] : Assembly 'Oculus.VR.Editor' hasn't been found
Import [Warning] : Unable to read OVRBuildConfig, because valid definition for script OVRConfig wasn't found
Import [Warning] : Unable to read OVRPlatformToolSettings, because valid definition for script OVRPlatformToolSettings wasn't found
Import [Warning] : Assembly 'SteamVR' hasn't been found
Import [Warning] : Unable to read fallback_fist, because valid definition for script SteamVR_Skeleton_Pose wasn't found
Import [Warning] : Unable to read fallback_point, because valid definition for script SteamVR_Skeleton_Pose wasn't found
Import [Warning] : Unable to read fallback_relaxed, because valid definition for script SteamVR_Skeleton_Pose wasn't found
Import [Warning] : Unable to read ReferencePose_BindPose, because valid definition for script SteamVR_Skeleton_Pose wasn't found
Import [Warning] : Unable to read ReferencePose_Fist, because valid definition for script SteamVR_Skeleton_Pose wasn't found
Import [Warning] : Unable to read ReferencePose_OpenHand, because valid definition for script SteamVR_Skeleton_Pose wasn't found
Import [Warning] : Unable to read SteamVR_Settings, because valid definition for script SteamVR_Settings wasn't found
Import [Warning] : Unable to read , because valid definition for script SteamVR_ExternalCamera wasn't found
Import [Warning] : Unable to read , because valid definition for script SteamVR_Skeleton_Poser wasn't found
Import [Warning] : Unable to read , because valid definition for script SteamVR_Behaviour_Skeleton wasn't found
Import [Warning] : Unable to read , because valid definition for script SteamVR_Skeleton_Poser wasn't found
Import [Warning] : Unable to read , because valid definition for script SteamVR_Behaviour_Skeleton wasn't found

-- During/After compiling

System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\ancut\Downloads\somewherhewhrew\AssetRipperExport638051800656254779\ExportedProject\Assets\Resources\objects\ygg\cosmeticroom\cosmetics room cover|cosmetics roomAction.anim'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at AssetRipper.Core.Project.Exporters.YamlExporterBase.Export(IExportContainer container, IUnityObjectBase asset, String path) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\Exporters\YamlExporterBase.cs:line 29
   at AssetRipper.Library.Exporters.AnimationClips.AnimationClipExportCollection.ExportInner(IProjectAssetContainer container, String filePath, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Exporters\AnimationClips\AnimationClipExportCollection.cs:line 25
   at AssetRipper.Core.Project.Collections.AssetExportCollection.Export(IProjectAssetContainer container, String projectDirectory) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\Collections\AssetExportCollection.cs:line 23
   at AssetRipper.Core.Project.ProjectExporter.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\ProjectExporter.cs:line 251
   at AssetRipper.Core.Project.ProjectExporter.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\ProjectExporter.cs:line 172
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 97
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Ripper.cs:line 181
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Ripper.cs:line 163
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipper.GUI\Managers\UIExportManager.cs:line 52

-- File
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10099131/AssetRipper.log)

**Comment by ds5678** [comment]
Already resolved on the latest commit.

**Comment by starseed12345** [comment]
ds5678 How did you fix it? im currently having the Same issue With Gorilla Tag

**Comment by starseed12345** [comment]
ah sorry i meant Grass30
