### ISSUE TITLE
[Bug]: System.IO.EndOfStreamException: Can't read 778399337-byte string because there are only 540 bytes left in the stream.

### ISSUE THREAD

**Issue by githubexplorer2342** [AssetRipper/AssetRipper#647]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest pre-release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://sonicrunners.com/#/download

Android version

### Which Unity version did this occur on?

4.7.2f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Just wanted to test out if this game exports fine on the 0.3.0.0 pre-release and apparently, it fails on reading 2 monobehaviours.

this is the error it gives me:

Error during reading of MonoBehavior PresenceManager. V: 4.7.2f1 P: Android N: level1.split0 Path:
System.IO.EndOfStreamException: Can't read 778399337-byte string because there are only 540 bytes left in the stream
   at AssetRipper.IO.Endian.EndianReader.ReadString(Int32 length) in D:\a\AssetRipper\AssetRipper\AssetRipper.IO.Endian\EndianReader.cs:line 215
   at AssetRipper.Assets.IO.Reading.AssetReader.ReadString() in D:\a\AssetRipper\AssetRipper\AssetRipper.Assets\IO\Reading\AssetReader.cs:line 32
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableField.Read(AssetReader reader, Int32 depth, Field& etalon) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\Assembly\Serializable\SerializableField.cs:line 20
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableStructure.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\Assembly\Serializable\SerializableStructure.cs:line 24
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableField.Read(AssetReader reader, Int32 depth, Field& etalon) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\Assembly\Serializable\SerializableField.cs:line 20
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableStructure.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\Assembly\Serializable\SerializableStructure.cs:line 24
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableField.Read(AssetReader reader, Int32 depth, Field& etalon) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\Assembly\Serializable\SerializableField.cs:line 20
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableStructure.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\Assembly\Serializable\SerializableStructure.cs:line 24
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableField.Read(AssetReader reader, Int32 depth, Field& etalon) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\Assembly\Serializable\SerializableField.cs:line 20
   at AssetRipper.Core.Structure.Assembly.Serializable.SerializableStructure.Read(AssetReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\Assembly\Serializable\SerializableStructure.cs:line 24
   at AssetRipper.Core.Structure.GameAssetFactory.ReadMonoBehaviour(IMonoBehaviour monoBehaviour, AssetReader reader, Int32 size, IAssemblyManager assemblyManager, SerializedType type) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameAssetFactory.cs:line 94

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10261473/AssetRipper.log)

**Comment by ds5678** [comment]
Did something change?

**Comment by githubexplorer2342** [comment]
> Did something change?

I just realized now that i closed it by accident, reopening right now.

**Comment by ds5678** [comment]
Update: I investigated the issue, and it's caused by `long` not being serializable before Unity 2017 (not sure on the exact version boundary). The `startTimestamp` and `endTimestamp` fields in `DiscordPresence.DiscordRpc.RichPresence` were being deserialized, even though they shouldn't have been.

Fixing this requires a fairly large refactor, so I don't have a solution today. However, now that the problem has been clearly identified, it's on the docket to be resolved.

References:
* https://discussions.unity.com/t/serialization-does-not-work-properly-with-long-type-i-e-int64/553107
* https://discussions.unity.com/t/long-not-serialized/507045/5
* https://discussions.unity.com/t/serializing-long-bug-can-someone-confirm/670314/2
* https://discussions.unity.com/t/why-cant-i-use-uint-for-the-inspector/98112
* https://discussions.unity.com/t/unable-to-serialize-uint-array/88840
* https://discussions.unity.com/t/which-built-ins-are-serializable/155152
