### ISSUE TITLE
[Bug]: Incorrect Number of Bytes Written

### ISSUE THREAD

**Issue by winterbreezesrule** [AssetRipper/AssetRipper#749]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://play.google.com/store/apps/details?id=com.devsisters.ck&hl=en_US&gl=US

### Which Unity version did this occur on?

2021.3.12

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Attempting to open a folder containing the assets from Cookie Run: Kingdom results in the folder not opening. I believe the specific error relates to one in a shader present in the files, as attempting to open the folder in AssetStudio gives a similar error with the Shader as the reason.

The assets for Cookie Run: Kingdom are encrypted, and the decryption tools are not currently publicly available at this time, but I am happy to share relevant files if need be.

### Relevant log output

Import : Files use the 'Unknown' scripting backend.
[Error] : System.Exception: Incorrect number of bytes written. -1 instead of 131072
   at AssetRipper.IO.Files.BundleFiles.FileStream.BundleFileBlockReader.ReadEntry(FileStreamNode entry) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\BundleFiles\FileStream\BundleFileBlockReader.cs:line 124
   at AssetRipper.IO.Files.BundleFiles.FileStream.FileStreamBundleFile.ReadFileStreamData(Stream stream, Int64 basePosition, Int64 headerSize) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\BundleFiles\FileStream\FileStreamBundleFile.cs:line 137
   at AssetRipper.IO.Files.Scheme`1.Read(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\Scheme.cs:line 15
   at AssetRipper.IO.Files.Scheme`1.AssetRipper.IO.Files.IScheme.Read(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\Scheme.cs:line 18
   at AssetRipper.IO.Files.SchemeReader.ReadFile(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\SchemeReader.cs:line 54
   at AssetRipper.Assets.Bundles.GameBundle.LoadAndSortFiles(IEnumerable`1 paths, IDependencyProvider dependencyProvider) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Bundles\GameBundle.FromPaths.cs:line 45
   at AssetRipper.Assets.Bundles.GameBundle.InitializeFromPaths(IEnumerable`1 paths, AssetFactoryBase assetFactory, IDependencyProvider dependencyProvider, IResourceProvider resourceProvider) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Bundles\GameBundle.FromPaths.cs:line 17
   at AssetRipper.Import.Structure.GameStructure.GameStructure.InitializeGameCollection() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure\GameStructure.cs:line 81
   at AssetRipper.Import.Structure.GameStructure.GameStructure..ctor(List`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure\GameStructure.cs:line 40
   at AssetRipper.Import.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure\GameStructure.cs:line 60
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 102
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIImportManager.cs:line 20

**Comment by ds5678** [comment]
> The assets for Cookie Run: Kingdom are encrypted

Out of scope

**Comment by winterbreezesrule** [comment]
My apologies, I wasn't very specific.

The assets are encrypted, but I have a decryption tool that is not public. 

Opening up most of the assets one by one works, but certain files (such as gacha_shop) do not properly open.

I am happy to share the bugged files specifically, but I am not at liberty to release the entire tool itself.

**Comment by ds5678** [comment]
I do not waste development time on games that were encrypted at any point before being loaded into AssetRipper.
