### ISSUE TITLE
[Bug]: Invalid version format: 2017.4.30f1

### ISSUE THREAD

**Issue by haiyang3-98** [AssetRipper/AssetRipper#759]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

A chinese mobile game released 2020 or so. Shut down long ago. 

### Which Unity version did this occur on?

2017.4.30f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

It seems that this version of unity is not supported. Please consider adding support for this version. 

### Relevant log output

System.ArgumentException: Invalid version format: 2017.4.30f1
2 (Parameter 'version')
   at AssetRipper.VersionUtilities.UnityVersion.Parse(String version)
   at AssetRipper.IO.Files.SerializedFiles.Parser.SerializedFileMetadata.Read(SerializedReader reader) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\SerializedFiles\Parser\SerializedFileMetadata.cs:line 99
   at AssetRipper.IO.Files.SerializedFiles.Parser.SerializedFileMetadata.Read(SmartStream stream, SerializedFileHeader header) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\SerializedFiles\Parser\SerializedFileMetadata.cs:line 53
   at AssetRipper.IO.Files.SerializedFiles.SerializedFile.Read(SmartStream stream) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\SerializedFiles\SerializedFile.cs:line 115
   at AssetRipper.IO.Files.Scheme`1.Read(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\Scheme.cs:line 14
   at AssetRipper.IO.Files.Scheme`1.AssetRipper.IO.Files.IScheme.Read(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\Scheme.cs:line 18
   at AssetRipper.IO.Files.SchemeReader.ReadFile(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\SchemeReader.cs:line 49
   at AssetRipper.IO.Files.SchemeReader.ReadFile(ResourceFile file) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\SchemeReader.cs:line 58
   at AssetRipper.IO.Files.FileContainer.ReadContents() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\FileContainer.cs:line 74
   at AssetRipper.IO.Files.FileContainer.ReadContentsRecursively() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\FileContainer.cs:line 81
   at AssetRipper.Assets.Bundles.GameBundle.LoadAndSortFiles(IEnumerable`1 paths, IDependencyProvider dependencyProvider) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Bundles\GameBundle.FromPaths.cs:line 46
   at AssetRipper.Assets.Bundles.GameBundle.InitializeFromPaths(IEnumerable`1 paths, AssetFactoryBase assetFactory, IDependencyProvider dependencyProvider, IResourceProvider resourceProvider) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Bundles\GameBundle.FromPaths.cs:line 17
   at AssetRipper.Import.Structure.GameStructure.GameStructure.InitializeGameCollection() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure\GameStructure.cs:line 81
   at AssetRipper.Import.Structure.GameStructure.GameStructure..ctor(List`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure\GameStructure.cs:line 40
   at AssetRipper.Import.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure\GameStructure.cs:line 60
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 102
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIImportManager.cs:line 20

**Comment by ds5678** [comment]
I'm fairly sure this is a duplicate, but I couldn't find the original. In any case, this has already been fixed upstream.
