### ISSUE TITLE
[Bug]: segfault when extracting from TOEM/TOEM_Data/sharedassets1.assets

### ISSUE THREAD

**Issue by sparr** [AssetRipper/AssetRipper#795]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Linux x64

### Which game did this occur on?

TOEM
https://steamdb.info/app/1307580/

### Which Unity version did this occur on?

Wasn't able to determine

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

`AssetRipper -q -o tmp --logFile tmp/log sharedassets1.assets`

### Relevant log output

```
[~1000 successful export lines skipped]
ExportedFile : 'TextIcon' exported
ExportedFile : 'WelcomeTo' exported
ExportedFile : 'WelcomeToHidden' exported
ExportedFile : 'CameraView' exported
About to unpack unity crunch...
Segmentation fault (core dumped)
```

backtrace from gdb:
```
Thread 1 "AssetRipper" received signal SIGSEGV, Segmentation fault.
0x00007ffff4cc1429 in unitycrnd::crn_unpacker::unpack_level(void const*, unsigned int, void**, unsigned int, unsigned int, unsigned int) () from /home/sparr/src/AssetRipper/Bins/AssetRipper/Debug/runtimes/linux-x64/native/libTexture2DDecoderNative.so
(gdb) bt
#0  0x00007ffff4cc1429 in unitycrnd::crn_unpacker::unpack_level(void const*, unsigned int, void**, unsigned int, unsigned int, unsigned int) ()
   from /home/sparr/src/AssetRipper/Bins/AssetRipper/Debug/runtimes/linux-x64/native/libTexture2DDecoderNative.so
#1  0x00007ffff4cc09d6 in unitycrnd::crnd_unpack_level(void*, void**, unsigned int, unsigned int, unsigned int) ()
   from /home/sparr/src/AssetRipper/Bins/AssetRipper/Debug/runtimes/linux-x64/native/libTexture2DDecoderNative.so
#2  0x00007ffff4cc0bf3 in unity_crunch_unpack_level(unsigned char const*, unsigned int, unsigned int, void**, unsigned int*) ()
   from /home/sparr/src/AssetRipper/Bins/AssetRipper/Debug/runtimes/linux-x64/native/libTexture2DDecoderNative.so
#3  0x00007ffff4cb5198 in UnpackUnityCrunch () from /home/sparr/src/AssetRipper/Bins/AssetRipper/Debug/runtimes/linux-x64/native/libTexture2DDecoderNative.so
#4  0x00007fff7f82393e in ?? ()
```

**Comment by ds5678** [comment]
I have no control over that library.

**Comment by sparr** [comment]
Looks like the library (https://github.com/KiruyaMomochi/Texture2DDecoder) comes from an upstream (https://github.com/Perfare/AssetStudio) that has been archived and is no longer under development. I've posted at https://github.com/KiruyaMomochi/Texture2DDecoder/issues/2 to see if they want this sort of issue there or if perhaps they will shift their upstream to the most active fork of the upstream repo, where I've also reproduced the problem and reported it https://github.com/aelurum/AssetStudio/issues/3

**Comment by ds5678** [comment]
Duplicate of #448
