### ISSUE TITLE
[Bug]: System.Exception: Incorrect number of bytes written.

### ISSUE THREAD

**Issue by LudovicMalot** [AssetRipper/AssetRipper#818]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

call of dragons

### Which Unity version did this occur on?

2021.3.2f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

While extracting the game assets an error got thrown (cf log) ending the exxtract

### Relevant log output

`Cpp2IL : Initializing Metadata...
Cpp2IL : Using actual IL2CPP Metadata version 29
Cpp2IL : Initialized Metadata in 315ms
Cpp2IL : Using binary type Portable Executable (from LibCpp2IL)
Cpp2IL : Searching Binary for Required Data...
Cpp2IL : Got Binary codereg: 0x181CBF730, metareg: 0x181FFCB90 in 98ms.
Cpp2IL : Initializing Binary...
Cpp2IL : Initialized Binary in 227ms
Cpp2IL : Mapping pointers to Il2CppMethodDefinitions...
Cpp2IL : Processed 88799 OK (149ms)
Cpp2IL : Creating application model...
Cpp2IL : Application model created in 1218.5193ms
System.Exception: Incorrect number of bytes written. -1 instead of 84608
   at AssetRipper.IO.Files.BundleFiles.FileStream.BundleFileBlockReader.ReadEntry(FileStreamNode entry) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\BundleFiles\FileStream\BundleFileBlockReader.cs:line 90
   at AssetRipper.IO.Files.BundleFiles.FileStream.FileStreamBundleFile.ReadFileStreamData(Stream stream, Int64 basePosition, Int64 headerSize) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\BundleFiles\FileStream\FileStreamBundleFile.cs:line 134
   at AssetRipper.IO.Files.BundleFiles.FileStream.FileStreamBundleFile.Read(SmartStream stream) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\BundleFiles\FileStream\FileStreamBundleFile.cs:line 33
   at AssetRipper.IO.Files.Scheme`1.Read(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\Scheme.cs:line 14
   at AssetRipper.IO.Files.Scheme`1.AssetRipper.IO.Files.IScheme.Read(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\Scheme.cs:line 18
   at AssetRipper.IO.Files.SchemeReader.ReadFile(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\SchemeReader.cs:line 49
   at AssetRipper.IO.Files.SchemeReader.LoadFile(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\SchemeReader.cs:line 34
   at AssetRipper.IO.Files.SchemeReader.LoadFile(String filePath) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.IO.Files\SchemeReader.cs:line 29

   at AssetRipper.Assets.Bundles.GameBundle.LoadFilesAndDependencies(IEnumerable`1 paths, IDependencyProvider dependencyProvider) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Bundles\GameBundle.FromPaths.cs:line 53
   at AssetRipper.Assets.Bundles.GameBundle.InitializeFromPaths(IEnumerable`1 paths, AssetFactoryBase assetFactory, IDependencyProvider dependencyProvider, IResourceProvider resourceProvider) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Bundles\GameBundle.FromPaths.cs:line 17
   at AssetRipper.Import.Structure.GameStructure.GameStructure.InitializeGameCollection() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure\GameStructure.cs:line 81
   at AssetRipper.Import.Structure.GameStructure.GameStructure..ctor(List`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure\GameStructure.cs:line 40
   at AssetRipper.Import.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure\GameStructure.cs:line 60
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 102
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIImportManager.cs:line 20
`
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11362240/AssetRipper.log)

**Comment by ds5678** [comment]
I pushed a commit making the error messages more clear.

https://nightly.link/AssetRipper/AssetRipper/workflows/publish/master/AssetRipper_win_x64.zip
