### ISSUE TITLE
[Bug]: Rewired.dll decompile issue

### ISSUE THREAD

**Issue by oldsportsgit** [AssetRipper/AssetRipper#837]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Baldi's basics full game public demo

### Which Unity version did this occur on?

2019.2.2f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

i tried the latest alpha and when i tried to decompile said game i got a bunch of errors when trying to export the project this
didn't happen in previous version of assetripper

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.22621.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.3.1.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Mon May 29 07:32:53 UTC 2023
System : UTC Compile Time: Tue May 23 13:33:25 UTC 2023
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: C:\Users\Valentino\Desktop\AssetRipper_win_x64 (1)\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: False
General : IgnoreEngineAssets: False
General : Attempting to read files from C:\Users\Valentino\Desktop\baldiing around\Baldi's Basics Demo 1.1 Windows
Import : PC game structure has been found at 'C:\Users\Valentino\Desktop\baldiing around\Baldi's Basics Demo 1.1 Windows'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level2' has been found
Import : Game file 'level3' has been found
Import : Game file 'level4' has been found
Import : Collecting Streaming Assets...
Import : Files use the 'Mono' scripting backend.
Import : During Mono initialization, found 99 assemblies
General : Finished reading files
General : Processing assemblies...
General : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Lighting Data Assets
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
General : Finished processing assets
Import : Asset collection has versions probably incompatible with each other. Here they are:
Import : 2019.2.2f1
Import : 2019.2.0a7
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: C:\Users\Valentino\Desktop\AssetRipper_win_x64 (1)\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: False
General : IgnoreEngineAssets: False
General : Attempting to read files from C:\Users\Valentino\Desktop\baldiing around\gmma
Import : Mixed game structure has been found at C:\Users\Valentino\Desktop\baldiing around\gmma
Import : Files use the 'Unknown' scripting backend.
Import : The game structure processor could not find any valid assets.
General : Finished reading files
General : Processing assemblies...
General : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Lighting Data Assets
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
General : Finished processing assets
General : About to begin export to C:\Users\Valentino\Desktop\baldiing around\gmma
General : Removing any files from a previous export...
Export : Attempting to export assets to C:\Users\Valentino\Desktop\baldiing around\gmma...
Export : Starting export
Export : Game files have these Unity versions: 0.0.0a0
Export : Exporting to Unity version 0.0.0a0
Export : Preparing for export...
Export : Preparation complete. Starting to export now...
Export : Finished exporting assets
Export : Saving game assemblies...
Export : Finished post-export
General : Export Complete!
General : UI Reset
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: C:\Users\Valentino\Desktop\baldiing around\gmma
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: False
General : IgnoreEngineAssets: False
General : Attempting to read files from C:\Users\Valentino\Desktop\baldiing around\Baldi's Basics Demo 1.1 Windows
Import : PC game structure has been found at 'C:\Users\Valentino\Desktop\baldiing around\Baldi's Basics Demo 1.1 Windows'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level2' has been found
Import : Game file 'level3' has been found
Import : Game file 'level4' has been found
Import : Collecting Streaming Assets...
Import : Files use the 'Mono' scripting backend.
Import : During Mono initialization, found 99 assemblies
General : Finished reading files
General : Processing assemblies...
General : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Lighting Data Assets
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
General : Finished processing assets
Import : Asset collection has versions probably incompatible with each other. Here they are:
Import : 2019.2.2f1
Import : 2019.2.0a7
General : About to begin export to C:\Users\Valentino\Desktop\baldiing around\na\Baldi's Basics Demo 1.1
General : Removing any files from a previous export...
Export : Attempting to export assets to C:\Users\Valentino\Desktop\baldiing around\na\Baldi's Basics Demo 1.1...
Export : Starting export
Export : Game files have these Unity versions: 2019.2.2f1 2019.2.0a7
Export : Exporting to Unity version 2019.2.2f1
Export : Preparing for export...
Import : Resource file 'sharedassets4.assets.resS' has been loaded
Import : Resource file 'sharedassets1.assets.resS' has been loaded
Import : Resource file 'sharedassets1.resource' has been loaded
Import : Resource file 'UnityEngine.UI.Tests.dll' hasn't been found
Import : Assembly 'UnityEngine.UI.Tests' hasn't been found
Import : Resource file 'com.unity.multiplayer-hlapi.Tests.dll' hasn't been found
Import : Assembly 'com.unity.multiplayer-hlapi.Tests' hasn't been found
Import : Resource file 'UnityEngine.TestRunner.dll' hasn't been found
Import : Assembly 'UnityEngine.TestRunner' hasn't been found
Import : Resource file 'UnityEngine.SpatialTracking.Tests.dll' hasn't been found
Import : Assembly 'UnityEngine.SpatialTracking.Tests' hasn't been found
Import : Resource file 'Unity.Analytics.DataPrivacy.Tests.dll' hasn't been found
Import : Assembly 'Unity.Analytics.DataPrivacy.Tests' hasn't been found
Import : Resource file 'Unity.ProGrids.RuntimeTests.dll' hasn't been found
Import : Assembly 'Unity.ProGrids.RuntimeTests' hasn't been found
Import : Resource file 'Unity.TextMeshPro.Tests.dll' hasn't been found
Import : Assembly 'Unity.TextMeshPro.Tests' hasn't been found
Import : Resource file 'Unity.IAP.Purchasing.RunTimeTests.dll' hasn't been found
Import : Assembly 'Unity.IAP.Purchasing.RunTimeTests' hasn't been found
Import : Resource file 'Unity.Timeline.Package.Tests.dll' hasn't been found
Import : Assembly 'Unity.Timeline.Package.Tests' hasn't been found
Import : Resource file 'Unity.Analytics.Editor.dll' hasn't been found
Import : Assembly 'Unity.Analytics.Editor' hasn't been found
Import : Resource file 'resources.assets.resS' has been loaded
Import : Resource file 'resources.resource' has been loaded
Import : Resource file 'sharedassets0.assets.resS' has been loaded
Import : Resource file 'sharedassets3.assets.resS' has been loaded
Import : Resource file 'sharedassets3.resource' has been loaded
Import : Resource file 'sharedassets2.assets.resS' has been loaded
Import : Resource file 'sharedassets2.resource' has been loaded
Import : Resource file 'level2.resS' has been loaded
Export : Preparation complete. Starting to export now...
ExportProgress : Exporting 'UpCloseGlitch'
ExportProgress : Exporting 'UpCloseOpen'
ExportProgress : Exporting 'UpCloseClosed'
ExportProgress : Exporting 'DemoWinAnm'
ExportProgress : Exporting 'Image'
ExportProgress : Exporting 'UpCloseGlitch'
ExportProgress : Exporting 'UpCloseOpen'
ExportProgress : Exporting 'UpCloseClosed'
ExportProgress : Exporting 'COMIC_Pro Material'
ExportProgress : Exporting 'COMIC_Pro Atlas'
ExportProgress : Exporting 'mus_party'
ExportProgress : Exporting 'COMIC_Pro'
ExportProgress : Exporting 'Engine 2019.2.2f1'
ExportProgress : Exporting 'ScriptExportCollection'
Export : Exporting scripts...
Export : Decompiling Assembly-CSharp
Export : Could not resolve assembly: System.Runtime.InteropServices
Export : Could not resolve assembly: System.Runtime.CompilerServices.Unsafe
Export : Decompiling com.unity.multiplayer-hlapi.Runtime
Export : Could not resolve assembly: System.Runtime.CompilerServices.Unsafe
Export : Could not resolve assembly: System.Runtime.InteropServices
Export : Decompiling NavMeshComponents
Export : Could not resolve assembly: System.Runtime.CompilerServices.Unsafe
Export : Could not resolve assembly: System.Runtime.InteropServices
Export : Decompiling Rewired_Core
System.AggregateException: One or more errors occurred. (Error decompiling @0600084A Rewired.ControllerWithAxes.PollForAllElementsDown)
 ---> Error decompiling @0600084A Rewired.ControllerWithAxes.PollForAllElementsDown
in assembly "Rewired_Core"
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.IL.ControlFlow.YieldReturnDecompiler.<ConvertBody>g__ConvertBranchAfterYieldReturn|35_0(Block newBlock, Block oldBlock, Int32 pos, <>c__DisplayClass35_0&) in YieldReturnDecompiler.cs:line 1016
   at ICSharpCode.Decompiler.IL.ControlFlow.YieldReturnDecompiler.ConvertBody(BlockContainer oldBody, StateRangeAnalysis rangeAnalysis) in YieldReturnDecompiler.cs:line 894
   at ICSharpCode.Decompiler.IL.ControlFlow.YieldReturnDecompiler.AnalyzeMoveNext(ILFunction function) in YieldReturnDecompiler.cs:line 786
   at ICSharpCode.Decompiler.IL.ControlFlow.YieldReturnDecompiler.Run(ILFunction function, ILTransformContext context) in YieldReturnDecompiler.cs:line 152
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1733
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1770
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1619
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.<>c__DisplayClass74_0.<DoDecompile>g__DoDecompileMember|0(IEntity entity, RecordDecompiler recordDecompiler, PartialTypeInfo partialType) in CSharpDecompiler.cs:line 1486
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1367
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in CSharpDecompiler.cs:line 650
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 949   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 35
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 body)
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>g__ProcessFiles|3(List`1 files) in /_/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs:line 255
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.WriteCodeFilesInProject(PEFile module, IList`1 partialTypes, CancellationToken cancellationToken) in /_/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs:line 221
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken) in /_/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs:line 154
   at AssetRipper.Export.UnityProjects.Scripts.ScriptDecompiler.DecompileWholeProject(WholeProjectDecompiler decompiler, AssemblyDefinition assembly, String outputFolder) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Scripts\ScriptDecompiler.cs:line 44
   at AssetRipper.Export.UnityProjects.Scripts.ScriptDecompiler.DecompileWholeProject(AssemblyDefinition assembly, String outputFolder) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Scripts\ScriptDecompiler.cs:line 39
   at AssetRipper.Export.UnityProjects.Scripts.ScriptExporter.Export(IExportContainer container, IEnumerable`1 assets, String assetsDirectoryPath, Action`3 callback) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Scripts\ScriptExporter.cs:line 95
   at AssetRipper.Export.UnityProjects.Scripts.ScriptExportCollection.Export(IExportContainer container, String projectDirectory) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Scripts\ScriptExportCollection.cs:line 49
   at AssetRipper.Export.UnityProjects.Project.ProjectExporter.Export(GameBundle fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Project\ProjectExporter.cs:line 273
   at AssetRipper.Export.UnityProjects.Project.ProjectExporter.Export(GameBundle fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Project\ProjectExporter.cs:line 179
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Func`2 filter, Action`1 onBeforeExport) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 185
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Action`1 onBeforeExport) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 164
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, MainWindowViewModel vm, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIExportManager.cs:line 47

**Comment by ds5678** [comment]
Upstream ILSpy problem
