### ISSUE TITLE
[Bug]: A new bug about IO！

### ISSUE THREAD

**Issue by Q4st** [AssetRipper/AssetRipper#857]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

2020.3.18f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

[Error] : System.IO.IOException: The file name, directory name, or volume label syntax is incorrect. : 'F:\Unity Project\huoban\6257e848\ExportedProject\Assets\PhysicMaterial\ (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) (Instance) _100.physicMaterial.meta'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at AssetRipper.Export.UnityProjects.Project.Collections.ExportCollection.ExportMeta(IExportContainer container, Meta meta, String filePath) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Project\Collections\ExportCollection.cs:line 48
   at AssetRipper.Export.UnityProjects.Project.Collections.AssetExportCollection.Export(IExportContainer container, String projectDirectory) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Project\Collections\AssetExportCollection.cs:line 24
   at AssetRipper.Export.UnityProjects.Project.ProjectExporter.Export(GameBundle fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Project\ProjectExporter.cs:line 261
   at AssetRipper.Export.UnityProjects.Project.ProjectExporter.Export(GameBundle fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Project\ProjectExporter.cs:line 179
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Func`2 filter, Action`1 onBeforeExport) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 174
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Action`1 onBeforeExport) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 155
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, MainWindowViewModel vm, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIExportManager.cs:line 49

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11732521/AssetRipper.log)

**Comment by ds5678** [comment]
Maybe it doesn't like the space at the beginning of the file name.

**Comment by Q4st** [comment]
@ds5678 1-99 are all normal, and an error will be reported when the 100th is exported. When I debugged, I found that _100.physicMaterial was not exported, and an error was reported when creating .meta

Here is a problem file：
[6257e848.zip](https://github.com/AssetRipper/AssetRipper/files/11737006/6257e848.zip)

**Comment by Q4st** [comment]
@ds5678 I tested the latest build today and this error still occurs

**Comment by ds5678** [comment]
I just pushed a commit that might help you

**Comment by Q4st** [comment]
@ds5678 Thank you very much, all problems solved
