### ISSUE TITLE
[Bug]: crash exporting game 0.3.2.0

### ISSUE THREAD

**Issue by moral3jo** [AssetRipper/AssetRipper#871]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

little misfortune

### Which Unity version did this occur on?

2018.3.5f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

when export all files in 0.3.2.0 when start with scripts crash
with 0.3.1.0. not crash

if export only scripts with 0.3.2.0 not crash

Note: D: in my pc is nothing and D:\a not exist

### Relevant log output

Export : Decompiling Rewired_Core
[Error] : System.AggregateException: One or more errors occurred. (Error decompiling @06000C2B Rewired.Data.Mapping.ActionCategoryMap.ActionIdsInCategory)
 ---> Error decompiling @06000C2B Rewired.Data.Mapping.ActionCategoryMap.ActionIdsInCategory
in assembly "Rewired_Core"
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.IL.ControlFlow.YieldReturnDecompiler.<ConvertBody>g__ConvertBranchAfterYieldReturn|35_0(Block newBlock, Block oldBlock, Int32 pos, <>c__DisplayClass35_0&) in YieldReturnDecompiler.cs:line 1016
   at ICSharpCode.Decompiler.IL.ControlFlow.YieldReturnDecompiler.ConvertBody(BlockContainer oldBody, StateRangeAnalysis rangeAnalysis) in YieldReturnDecompiler.cs:line 894
   at ICSharpCode.Decompiler.IL.ControlFlow.YieldReturnDecompiler.AnalyzeMoveNext(ILFunction function) in YieldReturnDecompiler.cs:line 786
   at ICSharpCode.Decompiler.IL.ControlFlow.YieldReturnDecompiler.Run(ILFunction function, ILTransformContext context) in YieldReturnDecompiler.cs:line 152
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1733
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1770
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1619
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.<>c__DisplayClass74_0.<DoDecompile>g__DoDecompileMember|0(IEntity entity, RecordDecompiler recordDecompiler, PartialTypeInfo partialType) in CSharpDecompiler.cs:line 1486
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(ITypeDefinition typeDef, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in CSharpDecompiler.cs:line 1367
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompileTypes(IEnumerable`1 types, DecompileRun decompileRun, ITypeResolveContext decompilationContext, SyntaxTree syntaxTree) in CSharpDecompiler.cs:line 650
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileTypes(IEnumerable`1 types) in CSharpDecompiler.cs:line 949
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>b__5(IGrouping`2 file) in WholeProjectDecompiler.cs:line 274
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 259
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in offset 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) in offset 0
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in offset 609
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in offset 35
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 body)
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.<>c__DisplayClass46_0.<WriteCodeFilesInProject>g__ProcessFiles|3(List`1 files) in /_/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs:line 255
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.WriteCodeFilesInProject(PEFile module, IList`1 partialTypes, CancellationToken cancellationToken) in /_/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs:line 221
   at ICSharpCode.Decompiler.CSharp.ProjectDecompiler.WholeProjectDecompiler.DecompileProject(PEFile moduleDefinition, String targetDirectory, TextWriter projectFileWriter, CancellationToken cancellationToken) in /_/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs:line 154
   at AssetRipper.Export.UnityProjects.Scripts.ScriptDecompiler.DecompileWholeProject(WholeProjectDecompiler decompiler, AssemblyDefinition assembly, String outputFolder) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Scripts\ScriptDecompiler.cs:line 44
   at AssetRipper.Export.UnityProjects.Scripts.ScriptDecompiler.DecompileWholeProject(AssemblyDefinition assembly, String outputFolder) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Scripts\ScriptDecompiler.cs:line 39
   at AssetRipper.Export.UnityProjects.Scripts.ScriptExporter.Export(IExportContainer container, IEnumerable`1 assets, String assetsDirectoryPath, Action`3 callback) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Scripts\ScriptExporter.cs:line 95
   at AssetRipper.Export.UnityProjects.Scripts.ScriptExportCollection.Export(IExportContainer container, String projectDirectory) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Scripts\ScriptExportCollection.cs:line 51
   at AssetRipper.Export.UnityProjects.Project.ProjectExporter.Export(GameBundle fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Project\ProjectExporter.cs:line 273
   at AssetRipper.Export.UnityProjects.Project.ProjectExporter.Export(GameBundle fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Project\ProjectExporter.cs:line 179
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Func`2 filter, Action`1 onBeforeExport) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 186
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Action`1 onBeforeExport) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 165
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, MainWindowViewModel vm, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIExportManager.cs:line 47

**Comment by ds5678** [comment]
I think I need to downgrade the ILSpy version.
