### ISSUE TITLE
[Bug]: Script export assertion failure `Debug.Assert(GetScriptsFolderName(assemblyName) is "Scripts")`

### ISSUE THREAD

**Issue by sparr** [AssetRipper/AssetRipper#906]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Linux x64

### Which game did this occur on?

FAR Lone Sails
https://steamdb.info/app/609320/

### Which Unity version did this occur on?

Unable to determine

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Crash after `Export : Exporting scripts...` when assertion fails.

Adding debug output to the program reveals that the following `assemblyName`s produce a `GetScriptsFolderName(assemblyName)` of `Scripts`:

```
VacuumShaders.TerrainToMesh
EpicGamesStore
Assembly-CSharp
InControl
FMODUnity
nn
```

And then for `assemblyName == "Assembly-CSharp-firstpass"` we get `GetScriptsFolderName(assemblyName) == "Plugins"` which triggers the assertion failure.

### Relevant log output

`AssetRipper -o out --log-file out/AssetRipper.log -v -q "FAR Lone Sails/Game/FarLoneSails_Data/sharedassets0.assets"`

```
Export : Exporting scripts...
Process terminated. Assertion failed.
   at AssetRipper.Export.UnityProjects.Scripts.ScriptExportCollection.Export(IExportContainer container, String projectDirectory) in /home/sparr/src/AssetRipper/Source/AssetRipper.Export.UnityProjects/Scripts/ScriptExportCollection.cs:line 110
   at AssetRipper.Export.UnityProjects.Project.ProjectExporter.Export(GameBundle fileCollection, IEnumerable`1 files, CoreConfiguration options) in /home/sparr/src/AssetRipper/Source/AssetRipper.Export.UnityProjects/Project/ProjectExporter.cs:line 268
   at AssetRipper.Export.UnityProjects.Project.ProjectExporter.Export(GameBundle fileCollection, CoreConfiguration options) in /home/sparr/src/AssetRipper/Source/AssetRipper.Export.UnityProjects/Project/ProjectExporter.cs:line 183
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Func`2 filter, Action`1 onBeforeExport) in /home/sparr/src/AssetRipper/Source/AssetRipper.Export.UnityProjects/Ripper.cs:line 186
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Action`1 onBeforeExport) in /home/sparr/src/AssetRipper/Source/AssetRipper.Export.UnityProjects/Ripper.cs:line 165
   at AssetRipper.GUI.ConsoleApp.Run(IReadOnlyList`1 filesToExport, String outputDirectory) in /home/sparr/src/AssetRipper/Source/AssetRipper.GUI/ConsoleApp.cs:line 126
   at AssetRipper.GUI.ConsoleApp.<>c.<Parse>b__6_4(List`1 filesToExport, DirectoryInfo outputDirectory, FileInfo logFile, Boolean verbose, Boolean quit) in /home/sparr/src/AssetRipper/Source/AssetRipper.GUI/ConsoleApp.cs:line 82
   at System.CommandLine.Handler.<>c__DisplayClass6_0`5.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<BuildInvocationChain>b__0(InvocationContext invocationContext, Func`2 _)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<UseParseErrorReporting>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<UseHelp>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<UseVersionOption>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<UseTypoCorrections>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<UseParseDirective>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<RegisterWithDotnetSuggest>b__5_0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<CancelOnProcessTermination>b__1_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<CancelOnProcessTermination>b__1_0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<Invoke>g__FullInvocationChain|3_0(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(IConsole console)
   at System.CommandLine.Parsing.ParseResultExtensions.Invoke(ParseResult parseResult, IConsole console)
   at System.CommandLine.Parsing.ParserExtensions.Invoke(Parser parser, String[] args, IConsole console)
   at AssetRipper.GUI.ConsoleApp.Parse(String[] args) in /home/sparr/src/AssetRipper/Source/AssetRipper.GUI/ConsoleApp.cs:line 87
   at AssetRipper.GUI.ConsoleApp.ParseArgumentsAndRun(String[] args) in /home/sparr/src/AssetRipper/Source/AssetRipper.GUI/ConsoleApp.cs:line 23
   at AssetRipper.GUI.Program.Main(String[] args) in /home/sparr/src/AssetRipper/Source/AssetRipper.GUI/Program.cs:line 22
```

**Comment by ds5678** [comment]
Are you sure you're on the latest alpha build? Your line numbers don't match up with the current files.

**Comment by sparr** [comment]
I believe I was running git master HEAD as of a few minutes before the issues was reported, but that question doesn't have an option for that.

**Comment by ds5678** [comment]
I suggest you try again on the latest commit.

**Comment by sparr** [comment]
Updated OP with stack trace from commit c6958d7abf5a1a0f69a2c015aaf2cc2660c97a5c

**Comment by ds5678** [comment]
I'll fix it 👍
